Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2018-10, with the labels that each got.

#625 Enhancement - IgxExpansionPanelComponent - Samples
  live-editing/configs/ExpansionPanelConfigGenerator.ts
  live-editing/generators/SampleAssetsGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/expansion-panel/expansion-sample-1/expansion-sample-1.component.html
  src/app/expansion-panel/expansion-sample-1/expansion-sample-1.component.scss
  src/app/expansion-panel/expansion-sample-1/expansion-sample-1.component.ts
  src/app/expansion-panel/expansion-sample-2/expansion-sample-2.component.html
  src/app/expansion-panel/expansion-sample-2/expansion-sample-2.component.scss
  src/app/expansion-panel/expansion-sample-2/expansion-sample-2.component.ts
  src/app/expansion-panel/expansion-sample-3/expansion-sample-3.component.html
  src/app/expansion-panel/expansion-sample-3/expansion-sample-3.component.scss
  src/app/expansion-panel/expansion-sample-3/expansion-sample-3.component.ts
  src/app/expansion-panel/expansion-sample-4/expansion-sample-4.component.html
  src/app/expansion-panel/expansion-sample-4/expansion-sample-4.component.scss
  src/app/expansion-panel/expansion-sample-4/expansion-sample-4.component.ts
  src/app/expansion-panel/expansion-sample-5/expansion-sample-5.component.html
  src/app/expansion-panel/expansion-sample-5/expansion-sample-5.component.scss
  src/app/expansion-panel/expansion-sample-5/expansion-sample-5.component.ts
  src/app/expansion-panel/expansion-sample-6/expansion-sample-6.component.html
  src/app/expansion-panel/expansion-sample-6/expansion-sample-6.component.scss
  src/app/expansion-panel/expansion-sample-6/expansion-sample-6.component.ts
Labels: enhancement, expansion-panel, status: completed

#630 Adding switch to show the "keepItem" feature of the list item panning
  live-editing/configs/ListConfigGenerator.ts
  src/app/list/list-sample-7/list-sample-7.component.html
  src/app/list/list-sample-7/list-sample-7.component.ts
Labels: list, status: verified

#655 Fixed layout manager sample to be scrollable
  src/app/layout/layout.component.scss
  src/app/layout/layout.component.ts
Labels: status: verified

#658 Configuring theme setting for IgxCalendarComponent.
  src/app/theming/styles/themes.scss
  src/app/theming/theme-chooser/theme-chooser-sample.component.html
  src/app/theming/theme-chooser/theme-chooser-sample.component.ts
Labels: grid, status: verified, theming

#652 Add tooltip samples
  live-editing/configs/TooltipConfigGenerator.ts
  live-editing/generators/SampleAssetsGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/tooltip/tooltip-rich/tooltip-rich.component.html
  src/app/tooltip/tooltip-rich/tooltip-rich.component.scss
  src/app/tooltip/tooltip-rich/tooltip-rich.component.ts
  src/app/tooltip/tooltip-simple/tooltip-simple.component.html
  src/app/tooltip/tooltip-simple/tooltip-simple.component.scss
  src/app/tooltip/tooltip-simple/tooltip-simple.component.ts
  src/assets/images/card/avatars/igLogo.png
  src/assets/images/card/media/infragisticsMap.png
Labels: status: verified

#660 Fixed grid editing sample "reorder level" cell to be editable.
  src/app/grid/grid-editing-sample/grid-editing-sample.component.html
  src/app/grid/grid-editing-sample/grid-editing-sample.component.scss
Labels: status: verified

#661 Removing Icons' Name Property.
  src/app/buttons/buttons-sample-1/buttons-sample-1.component.html
  src/app/buttons/buttons-sample-6/buttons-sample-6.component.html
  src/app/buttons/buttons-sample-7/buttons-sample-7.component.html
  src/app/card/card-sample-3/card-sample-3.component.html
  src/app/card/card.component.html
  src/app/circular-progressbar/circular-progressbar.component.html
  src/app/combo/cascading-combos/cascading-combos.component.html
  src/app/expansion-panel/expansion-sample-4/expansion-sample-4.component.html
  src/app/expansion-panel/expansion-sample-5/expansion-sample-5.component.html
  src/app/expansion-panel/expansion-sample-6/expansion-sample-6.component.html
  src/app/grid/grid-crm/grid-crm.component.html
  src/app/grid/grid-groupby-sample/grid-groupby-sample.component.html
  src/app/grid/grid-remote-paging-sample/remote-paging-sample.component.html
  src/app/grid/grid-search-sample/grid-search-sample.component.html
  src/app/grid/grid-sorting-sample/grid-contextmenu/grid-contextmenu.component.html
  src/app/icon/icon-sample-1/icon-sample-1.component.html
  src/app/icon/icon-sample2/icon-sample2.component.html
  src/app/index/index.component.html
  src/app/input-group/input-group-sample-3/input-group-sample-3.component.html
  src/app/input-group/input-group-sample-4/input-group-sample-4.component.html
  src/app/input-group/input-group-sample-5/input-group-sample-5.component.html
  src/app/input-group/input-group-sample-6/input-group-sample-6.component.html
  src/app/input-group/reactive-forms/reactive-forms.component.html
  src/app/linear-progressbar/linear-progressbar-sample-1/linear-progressbar-sample-1.component.html
  src/app/linear-progressbar/linear-progressbar-sample-2/linear-progressbar-sample-2.component.html
  src/app/linear-progressbar/linear-progressbar.component.html
  src/app/list/list-chat-sample/list-chat-sample.component.html
  src/app/list/list-sample-4/list-sample-4.component.html
  src/app/list/list-sample-7/list-sample-7.component.html
  src/app/navbar/navbar.component.html
  src/app/navdrawer/nav-drawer-mini/nav-drawer-mini.component.html
  src/app/navdrawer/nav-drawer-pin/nav-drawer-pin.component.html
  src/app/navdrawer/nav-drawer-simple/nav-drawer-simple.component.html
  src/app/navdrawer/navdrawer.component.html
  src/app/overlay/overlay-scroll-1/overlay-scroll-sample-1.component.html
  src/app/overlay/overlay-scroll-2/overlay-scroll-sample-2.component.html
  src/app/ripple/ripple-sample-1/ripple-sample-1.component.html
  src/app/tabbar/tabbar.component.html
  src/app/tabs/tabs-sample-2/tabs-sample-2.component.html
  src/app/text-highlight/text-highlight-sample-1/text-highlight-sample-1.component.html
  src/app/text-highlight/text-highlight-sample-2/text-highlight-sample-2.component.html
  src/app/tooltip/tooltip-rich/tooltip-rich.component.html
  src/index.html
Labels: icon, status: verified

#662 docs(icon): Added sample for SVG icons #2661
  live-editing/configs/IconConfigGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/grid/grid-crm/grid-crm.component.html
  src/app/grid/grid-moving-sample/grid-moving-sample.component.html
  src/app/grid/grid-sample-pinning/grid-pinning.component.html
  src/app/icon/svg-icon-sample/svg-icon-sample.component.html
  src/app/icon/svg-icon-sample/svg-icon-sample.component.scss
  src/app/icon/svg-icon-sample/svg-icon-sample.component.ts
  src/assets/images/svg/contains.svg
  src/assets/images/svg/does_not_contain.svg
  src/assets/images/svg/does_not_equal.svg
  src/assets/images/svg/ends_with.svg
  src/assets/images/svg/equals.svg
  src/assets/images/svg/is_empty.svg
  src/assets/images/svg/starts_with.svg
Labels: status: verified

#657 Created a drag and drop sample.
  live-editing/configs/DragAndDropConfigGenerator.ts
  live-editing/generators/SampleAssetsGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/drag-drop/drag-drop.component.html
  src/app/drag-drop/drag-drop.component.scss
  src/app/drag-drop/drag-drop.component.ts
  src/assets/images/drag-drop/infragistics-logo00.jpeg
  src/assets/images/drag-drop/infragistics-logo01.jpeg
  src/assets/images/drag-drop/infragistics-logo02.jpeg
  src/assets/images/drag-drop/infragistics-logo10.jpeg
  src/assets/images/drag-drop/infragistics-logo11.jpeg
  src/assets/images/drag-drop/infragistics-logo12.jpeg
  src/assets/images/drag-drop/infragistics-logo20.jpeg
  src/assets/images/drag-drop/infragistics-logo21.jpeg
  src/assets/images/drag-drop/infragistics-logo22.jpeg
Labels: status: verified

#667 Fix rich tooltip sample image paths
  src/app/tooltip/tooltip-rich/tooltip-rich.component.html
  src/app/tooltip/tooltip-rich/tooltip-rich.component.scss
Labels: status: verified

#665 Add weather sample using igxExpansionPanel
  angular.json
  live-editing/configs/ExpansionPanelConfigGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/expansion-panel/expansion-sample-7/expansion-sample-7.component.html
  src/app/expansion-panel/expansion-sample-7/expansion-sample-7.component.scss
  src/app/expansion-panel/expansion-sample-7/expansion-sample-7.component.ts
  src/app/expansion-panel/expansion-sample-7/weather-data.ts
Labels: status: verified

#672 Input group sample update
  src/app/input-group/input-group-sample-6/input-group-sample-6.component.ts
Labels: input group, status: verified

#671 docs(tabs): Removing tabs routing samples from navigation tree #668
  src/app/app-routing.module.ts
Labels: status: verified

#664 Add a finance grid demo sample
  live-editing/configs/GridConfigGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/grid/grid-finjs-demo/grid-finjs-demo.component.html
  src/app/grid/grid-finjs-demo/grid-finjs-demo.component.scss
  src/app/grid/grid-finjs-demo/grid-finjs-demo.component.ts
  src/app/grid/services/financialData.ts
  src/app/grid/services/localData.service.ts
  src/styles.scss
  src/themes.scss
Labels: status: verified

#676 Importing the IgxComboModule for IgxGridEditingSample.
  live-editing/configs/GridConfigGenerator.ts
Labels: status: verified

#677 packages upgarded to DV v6.2.0-beta.1
  package-lock.json
  package.json
Labels: status: verified

#679 set body overflow to auto for the finjs demo sample
  src/app/app-routing.module.ts
  src/app/grid/grid-finjs-demo/grid-finjs-demo.component.html
  src/app/grid/grid-finjs-demo/grid-finjs-demo.component.ts
Labels: status: verified

#680 Refactor code
  src/app/grid/grid-finjs-demo/grid-finjs-demo.component.ts
  src/app/grid/services/financialData.ts
  src/app/grid/services/localData.service.ts
Labels: status: verified

#685 fix(samples): Removing unnecessary copies of object that seem to bott…
  src/app/grid/grid-finjs-demo/grid-finjs-demo.component.ts
Labels: status: verified

#682 docs(drag-drop): Added a sample for onSelection event args #2031
  live-editing/configs/DropDownConfigGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/dropdown/dropdown-menu/dropdown-menu.component.html
  src/app/dropdown/dropdown-menu/dropdown-menu.component.scss
  src/app/dropdown/dropdown-menu/dropdown-menu.component.ts
Labels: dropdown, status: verified

#684 Samples for shadow customization
  live-editing/configs/ShadowsConfigGenerator.ts
  live-editing/generators/SampleAssetsGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/shadows/shadows-sample-1/shadows-sample.component.html
  src/app/shadows/shadows-sample-1/shadows-sample.component.scss
  src/app/shadows/shadows-sample-1/shadows-sample.component.ts
  src/app/shadows/shadows-sample-2/shadows-sample-2.component.html
  src/app/shadows/shadows-sample-2/shadows-sample-2.component.scss
  src/app/shadows/shadows-sample-2/shadows-sample-2.component.ts
Labels: status: verified, styling

#678 Resize avatars inside the chip sample to not overflow out of the chip.
  src/app/chip/chip.component.html
  src/app/chip/chip.component.scss
  src/app/chip/chip.component.ts
Labels: chip, status: verified

#690 Updating igniteui-angular to 6.2.0-beta.6
  package-lock.json
  package.json
  src/app/combo/combo-template/combo-template.component.html
  src/app/grid/grid-finjs-demo/grid-finjs-demo.component.scss
Labels: status: verified

#694 re-added mikeH's samples for chart's annotations
  src/app/app-routing.module.ts
  src/app/category-chart/annotations/category-chart-annotations.component.html
  src/app/category-chart/annotations/category-chart-annotations.component.scss
  src/app/category-chart/annotations/category-chart-annotations.component.ts
  src/app/category-chart/category-chart-samples.module.ts
  src/app/financial-chart/annotations/financial-chart-annotations.component.html
  src/app/financial-chart/annotations/financial-chart-annotations.component.scss
  src/app/financial-chart/annotations/financial-chart-annotations.component.ts
  src/app/financial-chart/financial-chart-samples.module.ts
  src/app/utilities/keys-pipe.ts
  src/app/utilities/utilities.module.ts
Labels: status: verified

#691 docs(*): Sample for display density #2692
  live-editing/configs/DensityConfigGenerator.ts
  live-editing/generators/SampleAssetsGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/display-density/display-density.component.html
  src/app/display-density/display-density.component.scss
  src/app/display-density/display-density.component.ts
Labels: input group, status: verified

#696 Updating igniteui-angular to 6.2.0-beta.7
  live-editing/generators/SampleAssetsGenerator.ts
  package-lock.json
  package.json
Labels: status: verified

#670 Grid row editing and transaction samples
  live-editing/configs/GridConfigGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/grid/grid-row-editing-sample/data.ts
  src/app/grid/grid-row-editing-sample/grid-row-editing-sample.component.html
  src/app/grid/grid-row-editing-sample/grid-row-editing-sample.component.scss
  src/app/grid/grid-row-editing-sample/grid-row-editing-sample.component.ts
  src/app/grid/grid-transaction/data.ts
  src/app/grid/grid-transaction/grid-transaction-sample.component.html
  src/app/grid/grid-transaction/grid-transaction-sample.component.scss
  src/app/grid/grid-transaction/grid-transaction-sample.component.ts
  src/app/grid/grid-transaction/grid-transaction.component.ts
Labels: status: verified

#704 Sass.js compile checker
  gulpfile.js
  live-editing/services/SassCompiler.ts
  live-editing/services/SassJsCompileChecker.ts
  package-lock.json
  package.json
Labels: status: verified
