Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2018-04, with the labels that each got.

#144 Adding some additional styles for igxGrid Performance sample.
  src/app/grid/grid-sample-2/grid-sample-2.component.html
  src/app/grid/grid-sample-2/grid-sample-2.component.scss
Labels: enhancement, status: verified

#146 Input group samples
  live-editing/SampleAssetsGenerator.ts
  live-editing/configs/DialogConfigGenerator.ts
  live-editing/configs/GridConfigGenerator.ts
  live-editing/configs/InputGroupConfigGenerator.ts
  live-editing/configs/LabelAndInputConfigGenerator.ts
  live-editing/configs/ListConfigGenerator.ts
  live-editing/configs/MaskConfigGenerator.ts
  live-editing/configs/SliderConfigGenerator.ts
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/dialog/dialog-sample-3/dialog-sample-3.component.html
  src/app/dialog/dialog.component.html
  src/app/grid/grid.component.html
  src/app/igxFor/igxFor.component.html
  src/app/input-group/input-group-sample-1/input-group-sample-1.component.html
  src/app/input-group/input-group-sample-1/input-group-sample-1.component.scss
  src/app/input-group/input-group-sample-1/input-group-sample-1.component.ts
  src/app/input-group/input-group-sample-2/input-group-sample-2.component.html
  src/app/input-group/input-group-sample-2/input-group-sample-2.component.scss
  src/app/input-group/input-group-sample-2/input-group-sample-2.component.ts
  src/app/input-group/input-group-sample-3/input-group-sample-3.component.html
  src/app/input-group/input-group-sample-3/input-group-sample-3.component.scss
  src/app/input-group/input-group-sample-3/input-group-sample-3.component.ts
  src/app/input-group/input-group-sample-4/input-group-sample-4.component.html
  src/app/input-group/input-group-sample-4/input-group-sample-4.component.scss
  src/app/input-group/input-group-sample-4/input-group-sample-4.component.ts
  src/app/input-group/input-group-sample-5/input-group-sample-5.component.html
  src/app/input-group/input-group-sample-5/input-group-sample-5.component.scss
  src/app/input-group/input-group-sample-5/input-group-sample-5.component.ts
  src/app/input-group/input-group-sample-6/input-group-sample-6.component.html
  src/app/input-group/input-group-sample-6/input-group-sample-6.component.scss
  src/app/input-group/input-group-sample-6/input-group-sample-6.component.ts
  src/app/label-input/label-input.component.html
  src/app/label-input/label-input.component.scss
  src/app/label-input/label-input.component.spec.ts
  src/app/label-input/label-input.component.ts
  src/app/list/list-sample-4/list-sample-4.component.html
  src/app/list/list.component.html
  src/app/mask/mask-sample-1/mask-sample-1.component.html
  src/app/mask/mask-sample-1/mask-sample-1.component.scss
  src/app/mask/mask-sample-2/mask-sample-2.component.html
  src/app/mask/mask-sample-3/mask-sample-3.component.html
  src/app/slider/slider-sample-1/slider-sample-1.component.html
  src/app/slider/slider-sample-2/slider-sample-2.component.html
  src/app/slider/slider-sample-3/slider-sample-3.component.html
  src/app/snackbar/snackbar-sample-4/snackbar-sample-4.component.html
  src/app/timepicker/timepicker-sample-1/timepicker-sample-1.component.ts
  src/app/timepicker/timepicker-sample-2/timepicker-sample-2.component.ts
  src/app/timepicker/timepicker-sample-3/timepicker-sample-3.component.ts
  src/app/timepicker/timepicker-sample-4/timepicker-sample-4.component.ts
Labels: status: verified

#152 update arrow icons based on the rank of the user
  src/app/grid/grid.component.ts
Labels: status: verified

#153 style(grid sample): Remove the unnecessary margins
  src/app/grid/grid.component.scss
Labels: status: verified

#163 Updated samples for multiple components related to 5.3.x changes
  package-lock.json
  src/app/dialog/dialog-sample-1/dialog-sample-1.component.html
  src/app/dialog/dialog-sample-1/dialog-sample-1.component.scss
  src/app/dialog/dialog-sample-1/dialog-sample-1.component.ts
  src/app/dialog/dialog-sample-2/dialog-sample-2.component.html
  src/app/dialog/dialog-sample-2/dialog-sample-2.component.scss
  src/app/dialog/dialog-sample-2/dialog-sample-2.component.ts
  src/app/dialog/dialog-sample-3/dialog-sample-3.component.html
  src/app/dialog/dialog-sample-3/dialog-sample-3.component.scss
  src/app/dialog/dialog-sample-3/dialog-sample-3.component.ts
  src/app/dialog/dialog.component.html
  src/app/dialog/dialog.component.scss
  src/app/form-elements/checkbox/checkbox-sample-1/checkbox-sample-1.component.html
  src/app/form-elements/checkbox/checkbox-sample-1/checkbox-sample-1.component.scss
  src/app/form-elements/checkbox/checkbox-sample-1/checkbox-sample-1.component.ts
  src/app/form-elements/checkbox/checkbox-sample-2/checkbox-sample-2.component.scss
  src/app/form-elements/checkbox/checkbox-sample-2/checkbox-sample-2.component.ts
  src/app/igxFor/igxFor.component.html
  src/app/igxFor/igxFor.component.scss
  src/app/igxFor/igxFor.component.ts
  src/app/list/list-sample-4/list-sample-4.component.html
  src/app/list/list-sample-4/list-sample-4.component.scss
  src/app/list/list.component.html
  src/app/list/list.component.scss
  src/app/list/list.component.ts
  src/app/mask/mask-sample-1/mask-sample-1.component.html
  src/app/mask/mask-sample-1/mask-sample-1.component.scss
  src/app/mask/mask-sample-2/mask-sample-2.component.html
  src/app/mask/mask-sample-3/mask-sample-3.component.html
  src/app/mask/mask-sample-3/mask-sample-3.component.scss
  src/app/snackbar/snackbar-sample-4/snackbar-sample-4.component.html
  src/app/snackbar/snackbar-sample-4/snackbar-sample-4.component.scss
Labels: status: verified

#147 Adding samples for the exporters.
  live-editing/SharedAssetsGenerator.ts
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/export-csv/csv-export-sample-1/csv-export-sample-1.component.html
  src/app/export-csv/csv-export-sample-1/csv-export-sample-1.component.scss
  src/app/export-csv/csv-export-sample-1/csv-export-sample-1.component.spec.ts
  src/app/export-csv/csv-export-sample-1/csv-export-sample-1.component.ts
  src/app/export-csv/csv-export.component.html
  src/app/export-csv/csv-export.component.scss
  src/app/export-csv/csv-export.component.spec.ts
  src/app/export-csv/csv-export.component.ts
  src/app/export-excel/excel-export-sample-1/excel-export-sample-1.component.html
  src/app/export-excel/excel-export-sample-1/excel-export-sample-1.component.scss
  src/app/export-excel/excel-export-sample-1/excel-export-sample-1.component.spec.ts
  src/app/export-excel/excel-export-sample-1/excel-export-sample-1.component.ts
  src/app/export-excel/excel-export.component.html
  src/app/export-excel/excel-export.component.scss
  src/app/export-excel/excel-export.component.spec.ts
  src/app/export-excel/excel-export.component.ts
Labels: status: verified

#165 Category chart samples
  src/app/category-chart/category-chart-samples.module.ts
  src/app/category-chart/overview/category-chart-overview-sample.component.html
  src/app/category-chart/overview/category-chart-overview-sample.component.scss
  src/app/category-chart/overview/category-chart-overview-sample.component.ts
  src/app/category-chart/services/data.service.ts
Labels: status: verified

#162 Added input group sample 2 live editing configuration
  live-editing/configs/InputGroupConfigGenerator.ts
Labels: status: verified

#170 new samples for grid filtering nd paging topics
  live-editing/configs/GridConfigGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/grid/grid-filtering-sample/employeesData.ts
  src/app/grid/grid-filtering-sample/grid-filtering-sample.component.html
  src/app/grid/grid-filtering-sample/grid-filtering-sample.component.scss
  src/app/grid/grid-filtering-sample/grid-filtering-sample.component.ts
  src/app/grid/grid-paging-sample/grid-paging-sample.component.html
  src/app/grid/grid-paging-sample/grid-paging-sample.component.scss
  src/app/grid/grid-paging-sample/grid-paging-sample.component.ts
Labels: status: verified

#145 Adding igx-grid row selection sample (single/multiple)
  live-editing/configs/GridConfigGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/grid/grid-sample-selection/financialData.ts
  src/app/grid/grid-sample-selection/grid-selection.component.html
  src/app/grid/grid-sample-selection/grid-selection.component.scss
  src/app/grid/grid-sample-selection/grid-selection.component.ts
Labels: status: verified

#184 Enhance filtering and paging samples
  .vscode/settings.json
  live-editing/configs/GridConfigGenerator.ts
  src/app/grid/grid-filtering-sample/employeesData.ts
  src/app/grid/grid-filtering-sample/grid-filtering-sample.component.html
  src/app/grid/grid-filtering-sample/grid-filtering-sample.component.ts
  src/app/grid/grid-filtering-sample/nwindData.ts
  src/app/grid/grid-paging-sample/grid-paging-sample.component.html
  src/app/grid/grid-paging-sample/grid-paging-sample.component.scss
  src/app/grid/grid-paging-sample/grid-paging-sample.component.ts
  src/app/grid/grid.component.html
  src/assets/images/grid/active.png
  src/assets/images/grid/expired.png
Labels: status: verified

#188 Make filtering sample respond to frame shrinking/expanding
  src/app/grid/grid-filtering-sample/grid-filtering-sample.component.html
  src/app/grid/grid-paging-sample/grid-paging-sample.component.html
Labels: status: verified

#202 fix styling issues on grid samples
  src/app/grid/grid-filtering-sample/grid-filtering-sample.component.html
  src/app/grid/grid-paging-sample/grid-paging-sample.component.scss
  src/app/grid/grid.component.html
  src/app/grid/grid.component.scss
Labels: status: verified

#191 Updating the igniteui-angular package to RC1
  package-lock.json
  package.json
Labels: status: verified

#185 docs(tabs): Demo samples for tabs #167
  live-editing/SampleAssetsGenerator.ts
  live-editing/configs/TabsConfigGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/tabs/tabs-sample-1/tabs-sample-1.component.html
  src/app/tabs/tabs-sample-1/tabs-sample-1.component.scss
  src/app/tabs/tabs-sample-1/tabs-sample-1.component.ts
  src/app/tabs/tabs-sample-2/tabs-sample-2.component.html
  src/app/tabs/tabs-sample-2/tabs-sample-2.component.scss
  src/app/tabs/tabs-sample-2/tabs-sample-2.component.ts
  src/app/tabs/tabs-sample-3/tabs-sample-3.component.html
  src/app/tabs/tabs-sample-3/tabs-sample-3.component.scss
  src/app/tabs/tabs-sample-3/tabs-sample-3.component.ts
Labels: status: verified

#208 Add sample for sorting and adding contextmenu
  live-editing/configs/GridConfigGenerator.ts
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/grid/grid-sorting-sample/grid-contextmenu/grid-contextmenu.component.html
  src/app/grid/grid-sorting-sample/grid-contextmenu/grid-contextmenu.component.scss
  src/app/grid/grid-sorting-sample/grid-contextmenu/grid-contextmenu.component.ts
  src/app/grid/grid-sorting-sample/grid-sorting-sample.component.html
  src/app/grid/grid-sorting-sample/grid-sorting-sample.component.scss
  src/app/grid/grid-sorting-sample/grid-sorting-sample.component.ts
  src/app/grid/grid-sorting-sample/nwindData.ts
Labels: enhancement, status: verified

#171 Add grid samples for columns pinning and remote virtualization
  live-editing/configs/GridConfigGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/grid/grid-sample-3/grid-sample-3.component.html
  src/app/grid/grid-sample-4/grid-sample-4.component.html
  src/app/grid/grid-sample-4/grid-sample-4.component.scss
  src/app/grid/grid-sample-4/grid-sample-4.component.ts
  src/app/grid/grid-sample-pinning/data.ts
  src/app/grid/grid-sample-pinning/grid-pinning.component.html
  src/app/grid/grid-sample-pinning/grid-pinning.component.scss
  src/app/grid/grid-sample-pinning/grid-pinning.component.ts
Labels: status: verified

#217 Remove auto opening of the date and time pickers
  src/app/datepicker/datepicker-sample-1/datepicker-sample-1.component.ts
  src/app/datepicker/datepicker-sample-2/datepicker-sample-2.component.ts
  src/app/datepicker/datepicker-sample-3/datepicker-sample-3.component.ts
  src/app/datepicker/datepicker-sample-4/datepicker-sample-4.component.ts
  src/app/datepicker/datepicker-sample-5/datepicker-sample-5.component.ts
  src/app/tabs/tabs-sample-3/tabs-sample-3.component.html
  src/app/timepicker/timepicker-sample-1/timepicker-sample-1.component.ts
  src/app/timepicker/timepicker-sample-2/timepicker-sample-2.component.ts
  src/app/timepicker/timepicker-sample-3/timepicker-sample-3.component.ts
  src/app/timepicker/timepicker-sample-4/timepicker-sample-4.component.ts
Labels: enhancement, status: verified

#219 fix(marathon-grid): when cell click text disappear
  src/app/grid/grid.component.html
  src/app/grid/grid.component.ts
Labels: status: verified

#207 Introduce consistency across grid samples
  live-editing/configs/GridConfigGenerator.ts
  src/app/grid/grid-filtering-sample/grid-filtering-sample.component.html
  src/app/grid/grid-filtering-sample/grid-filtering-sample.component.scss
  src/app/grid/grid-filtering-sample/grid-filtering-sample.component.ts
  src/app/grid/grid-paging-sample/grid-paging-sample.component.html
  src/app/grid/grid-paging-sample/grid-paging-sample.component.scss
  src/app/grid/grid-resizing-sample/grid-resizing-sample.component.html
  src/app/grid/grid-resizing-sample/grid-resizing-sample.component.scss
  src/app/grid/grid-sample-2/grid-sample-2.component.html
  src/app/grid/grid-sample-2/grid-sample-2.component.scss
  src/app/grid/grid-sample-3/grid-sample-3.component.html
  src/app/grid/grid-sample-3/grid-sample-3.component.scss
  src/app/grid/grid-sample-selection/grid-selection.component.html
  src/app/grid/grid-sample-selection/grid-selection.component.scss
  src/app/grid/grid-sorting-sample/grid-sorting-sample.component.scss
  src/styles.scss
Labels: status: verified

#227 Fix crm-grid styling
  src/app/grid/grid-crm/grid-crm.component.html
  src/app/grid/grid-crm/grid-crm.component.scss
Labels: enhancement, status: awaiting-test

#233 remove date column from awesome grid sample
  src/app/grid/grid.component.html
Labels: status: verified

#237 Grid samples update
  src/app/grid/grid-filtering-sample/grid-filtering-sample.component.html
  src/app/grid/grid-filtering-sample/grid-filtering-sample.component.ts
  src/app/grid/grid-paging-sample/grid-paging-sample.component.html
  src/app/grid/grid-paging-sample/grid-paging-sample.component.scss
  src/app/grid/grid-resizing-sample/grid-resizing-sample.component.html
  src/app/grid/grid-sample-2/grid-sample-2.component.scss
  src/app/grid/grid-sample-selection/grid-selection.component.scss
Labels: status: verified

#238 Fix(Summaries): Removing swith and adding summary icon in the title
  live-editing/configs/GridConfigGenerator.ts
  src/app/grid/grid-sample-3/grid-sample-3.component.html
  src/app/grid/grid-sample-3/grid-sample-3.component.scss
  src/app/grid/grid-sample-3/grid-sample-3.component.ts
Labels: enhancement, status: verified

#228 Adding Stackblitz generators for the exporters services.
  live-editing/SampleAssetsGenerator.ts
  live-editing/configs/ExportCsvConfigGenerator.ts
  live-editing/configs/ExportExcelConfigGenerator.ts
Labels: status: verified

#236 Grid selection sample improvement
  live-editing/configs/GridConfigGenerator.ts
  src/app/grid/grid-sample-selection/grid-selection.component.html
  src/app/grid/grid-sample-selection/grid-selection.component.scss
Labels: status: verified

#218 Live Editing Documentation & TS lint fixes
  live-editing/DependencyResolver.ts
  live-editing/README.md
  live-editing/SampleAssetsGenerator.ts
  live-editing/SampleDefinitionFile.ts
  live-editing/SharedAssetsFile.ts
  live-editing/SharedAssetsGenerator.ts
  live-editing/TsImportsService.ts
  live-editing/configs/AvatarConfigGenerator.ts
  live-editing/configs/BadgeConfigGenerator.ts
  live-editing/configs/ButtonConfigGenerator.ts
  live-editing/configs/ButtonGroupConfigGenerator.ts
  live-editing/configs/CalendarConfigGenerator.ts
  live-editing/configs/CardConfigGenerator.ts
  live-editing/configs/CarouselConfigGenerator.ts
  live-editing/configs/CategoryChartConfigGenerator.ts
  live-editing/configs/CheckboxConfigGenerator.ts
  live-editing/configs/CircularProgressbarConfigGenerator.ts
  live-editing/configs/DatePickerConfigGenerator.ts
  live-editing/configs/DialogConfigGenerator.ts
  live-editing/configs/FinancialChartConfigGenerator.ts
  live-editing/configs/ForConfigGenerator.ts
  live-editing/configs/GridConfigGenerator.ts
  live-editing/configs/IconConfigGenerator.ts
  live-editing/configs/InputGroupConfigGenerator.ts
  live-editing/configs/LayoutConfigGenerator.ts
  live-editing/configs/LinearProgressbarConfigGenerator.ts
  live-editing/configs/ListConfigGenerator.ts
  live-editing/configs/MaskConfigGenerator.ts
  live-editing/configs/NavDrawerConfigGenerator.ts
  live-editing/configs/NavbarConfigGenerator.ts
  live-editing/configs/RadioConfigGenerator.ts
  live-editing/configs/RippleConfigGenerator.ts
  live-editing/configs/SliderConfigGenerator.ts
  live-editing/configs/SnackbarConfigGenerator.ts
  live-editing/configs/SwitchConfigGenerator.ts
  live-editing/configs/TabBarConfigGenerator.ts
  live-editing/configs/TabsConfigGenerator.ts
  live-editing/configs/TimePickerConfigGenerator.ts
  live-editing/configs/ToastConfigGenerator.ts
  live-editing/configs/ToggleConfigGenerator.ts
  live-editing/configs/core/AppModuleConfig.ts
  live-editing/configs/core/Config.ts
  live-editing/configs/core/IConfigGenerator.ts
Labels: status: verified

#213 Add summaries to Marathon grid
  src/app/grid/grid.component.html
  src/app/grid/grid.component.ts
Labels: status: verified

#245 Add missing module imports and remove some shorten paths
  live-editing/configs/CalendarConfigGenerator.ts
  live-editing/configs/CardConfigGenerator.ts
  live-editing/configs/CarouselConfigGenerator.ts
  live-editing/configs/DatePickerConfigGenerator.ts
  live-editing/configs/DialogConfigGenerator.ts
  live-editing/configs/ForConfigGenerator.ts
  live-editing/configs/MaskConfigGenerator.ts
  live-editing/configs/ToggleConfigGenerator.ts
Labels: enhancement

#243 Fix column resizing sample
  src/app/grid/grid-resizing-sample/grid-resizing-sample.component.html
Labels: enhancement, status: verified

#260 Adding a height to the igxGrid to fix an issue in the exporters samples.
  src/app/export-csv/csv-export-sample-1/csv-export-sample-1.component.html
  src/app/export-excel/excel-export-sample-1/excel-export-sample-1.component.html
Labels: status: verified

#270 docs(grid): Adding support for forRoot with 1 param
  live-editing/SampleAssetsGenerator.ts
Labels: status: verified

#262 Fix vertical scrollbar in igxForOf demo not displaying properly.
  src/app/igxFor/igxFor.component.html
Labels: status: verified

#261 increase Rank and Number columns width, add selection handler
  src/app/grid/grid-paging-sample/grid-paging-sample.component.html
  src/app/grid/grid-paging-sample/grid-paging-sample.component.ts
Labels: status: verified

#271 Adding width to the igxGrid exporters samples.
  src/app/export-csv/csv-export-sample-1/csv-export-sample-1.component.html
  src/app/export-csv/csv-export-sample-1/csv-export-sample-1.component.scss
  src/app/export-excel/excel-export-sample-1/excel-export-sample-1.component.html
  src/app/export-excel/excel-export-sample-1/excel-export-sample-1.component.scss
Labels: status: verified

#267 docs(grid): Adding Remote Virtualization sample with In Memory Web API
  live-editing/configs/GridConfigGenerator.ts
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/grid/grid-sample-2/grid-sample-2.component.ts
  src/app/grid/grid-sample-4/grid-sample-4.component.html
  src/app/grid/grid-sample-4/grid-sample-4.component.scss
  src/app/grid/grid-sample-4/grid-sample-4.component.ts
  src/app/grid/services/financialData.ts
  src/app/grid/services/mock-data.service.ts
Labels: status: verified

#276 Polish CRM sample
  src/app/grid/grid-crm/grid-crm.component.scss
  src/app/grid/grid-crm/grid-crm.component.ts
Labels: enhancement, grid

#265 Enhance some of the grid samples
  package-lock.json
  package.json
  src/app/grid/grid-filtering-sample/grid-filtering-sample.component.html
  src/app/grid/grid-paging-sample/grid-paging-sample.component.html
  src/app/grid/grid-sample-3/grid-sample-3.component.html
  src/app/grid/grid-sorting-sample/grid-sorting-sample.component.html
Labels: enhancement, status: verified

#288 Added immediate package to CSV/Excel live editing samples
  live-editing/DependencyResolver.ts
  live-editing/configs/ExportCsvConfigGenerator.ts
  live-editing/configs/ExportExcelConfigGenerator.ts
  live-editing/configs/GridConfigGenerator.ts
  package.json
Labels: severity: medium, status: verified

#293 Dsiabled XSS protection
  web.config
Labels: status: verified

#301 Added dependencies type in live editing
  live-editing/DependenciesType.ts
  live-editing/DependencyResolver.ts
  live-editing/README.md
  live-editing/SampleAssetsGenerator.ts
  live-editing/configs/CategoryChartConfigGenerator.ts
  live-editing/configs/DialogConfigGenerator.ts
  live-editing/configs/ExportCsvConfigGenerator.ts
  live-editing/configs/ExportExcelConfigGenerator.ts
  live-editing/configs/FinancialChartConfigGenerator.ts
  live-editing/configs/ForConfigGenerator.ts
  live-editing/configs/GridConfigGenerator.ts
  live-editing/configs/core/Config.ts
Labels: status: verified
