Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2018-03, with the labels that each got.

#127 Make grid-sample responsive
  src/app/grid/grid.component.html
  src/app/grid/grid.component.scss
Labels: status: verified

#129 Live editing to TypeScript
  .editorconfig
  gulpfile.js
  live-editing/LiveEditingFile.ts
  live-editing/LiveEditingManager.ts
  live-editing/SampleAssetsGenerator.ts
  live-editing/SharedAssetsFile.ts
  live-editing/SharedAssetsGenerator.ts
  live-editing/TsImportsService.ts
  live-editing/configs/AvatarConfigGenerator.ts
  live-editing/configs/BadgeConfigGenerator.ts
  live-editing/configs/ButtonConfigGenerator.ts
  live-editing/configs/ButtonGroupConfigGenerator.ts
  live-editing/configs/CalendarConfigGenerator.ts
  live-editing/configs/CardConfigGenerator.ts
  live-editing/configs/CarouselConfigGenerator.ts
  live-editing/configs/CheckboxConfigGenerator.ts
  live-editing/configs/CircularProgressbarConfigGenerator.ts
  live-editing/configs/DatePickerConfigGenerator.ts
  live-editing/configs/DialogConfigGenerator.ts
  live-editing/configs/ForConfigGenerator.ts
  live-editing/configs/GridConfigGenerator.ts
  live-editing/configs/IconConfigGenerator.ts
  live-editing/configs/LabelAndInputConfigGenerator.ts
  live-editing/configs/LayoutConfigGenerator.ts
  live-editing/configs/LinearProgressbarConfigGenerator.ts
  live-editing/configs/ListConfigGenerator.ts
  live-editing/configs/NavDrawerConfigGenerator.ts
  live-editing/configs/NavbarConfigGenerator.ts
  live-editing/configs/RadioConfigGenerator.ts
  live-editing/configs/RippleConfigGenerator.ts
  live-editing/configs/SliderConfigGenerator.ts
  live-editing/configs/SnackbarConfigGenerator.ts
  live-editing/configs/SwitchConfigGenerator.ts
  live-editing/configs/TabBarConfigGenerator.ts
  live-editing/configs/ToastConfigGenerator.ts
  live-editing/configs/ToggleConfigGenerator.ts
  live-editing/configs/core/AppModuleConfig.ts
  live-editing/configs/core/Config.ts
  live-editing/configs/core/IConfigGenerator.ts
  live-editing/file.js
  live-editing/sample-asset.handler.js
  live-editing/samples.conf.js
  live-editing/shared-asset.handler.js
  live-editing/templates/main.ts.template
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/progressbar/progressbar.component.html
  src/app/progressbar/progressbar.component.scss
  src/app/progressbar/progressbar.component.spec.ts
  src/app/progressbar/progressbar.component.ts
Labels: status: verified

#138 Calendar template parts parsing for browser not supporting Intl
  src/app/calendar/calendar-sample-1/calendar-sample-1.component.scss
  src/app/calendar/calendar-sample-2/calendar-sample-2.component.scss
  src/app/calendar/calendar-sample-4/calendar-sample-4.component.html
  src/app/calendar/calendar-sample-4/calendar-sample-4.component.scss
  src/app/calendar/calendar-sample-4/calendar-sample-4.component.ts
  src/app/calendar/calendar-sample-5/calendar-sample-5.component.scss
  src/app/date-parser.ts
  src/app/datepicker/datepicker-sample-5/datepicker-sample-5.component.html
  src/app/datepicker/datepicker-sample-5/datepicker-sample-5.component.ts
Labels: status: verified

#140 Bind correaclty closeOnOutsideSelect property
  src/app/dialog/dialog-sample-3/dialog-sample-3.component.html
Labels: status: verified

#136 Add samples for timepicker
  live-editing/SampleAssetsGenerator.ts
  live-editing/configs/TimePickerConfigGenerator.ts
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/timepicker/timepicker-sample-1/timepicker-sample-1.component.html
  src/app/timepicker/timepicker-sample-1/timepicker-sample-1.component.scss
  src/app/timepicker/timepicker-sample-1/timepicker-sample-1.component.ts
  src/app/timepicker/timepicker-sample-2/timepicker-sample-2.component.html
  src/app/timepicker/timepicker-sample-2/timepicker-sample-2.component.scss
  src/app/timepicker/timepicker-sample-2/timepicker-sample-2.component.ts
  src/app/timepicker/timepicker-sample-3/timepicker-sample-3.component.html
  src/app/timepicker/timepicker-sample-3/timepicker-sample-3.component.scss
  src/app/timepicker/timepicker-sample-3/timepicker-sample-3.component.ts
  src/app/timepicker/timepicker-sample-4/timepicker-sample-4.component.html
  src/app/timepicker/timepicker-sample-4/timepicker-sample-4.component.scss
  src/app/timepicker/timepicker-sample-4/timepicker-sample-4.component.ts
Labels: enhancement, status: in-test

#134 Added samples for mask directive
  live-editing/SampleAssetsGenerator.ts
  live-editing/configs/MaskConfigGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/mask/mask-sample-1/mask-sample-1.component.html
  src/app/mask/mask-sample-1/mask-sample-1.component.scss
  src/app/mask/mask-sample-1/mask-sample-1.component.ts
  src/app/mask/mask-sample-2/mask-sample-2.component.html
  src/app/mask/mask-sample-2/mask-sample-2.component.scss
  src/app/mask/mask-sample-2/mask-sample-2.component.ts
  src/app/mask/mask-sample-3/mask-sample-3.component.html
  src/app/mask/mask-sample-3/mask-sample-3.component.scss
  src/app/mask/mask-sample-3/mask-sample-3.component.ts
  src/app/mask/model/person.ts
Labels: enhancement, status: verified
