Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2018-05, with the labels that each got.

#303 igniteui-angular #1138 [igxList sample] Fixed an issue with wrong item getting updated after filtering.
  src/app/list/list-sample-4/list-sample-4.component.html
  src/app/list/list-sample-4/list-sample-4.component.ts
Labels: bug, severity: medium, status: verified

#300 Fixed the IE11 XSS prevention
  src/app/grid/grid.component.html
Labels: status: verified

#302 Fixed live editing watcher
  gulpfile.js
  package.json
Labels: status: verified

#309 Adding readme.md and contributing.md files
  .github/CONTRIBUTING.md
  README.md
Labels: enhancement, status: verified

#310 Fixed CC tooltips and span formatting above slider
  src/app/category-chart/custom-tooltips/category-chart-custom-tooltips-sample.component.html
  src/app/category-chart/high-frequency/category-chart-high-frequency-sample.component.ts
  src/app/category-chart/high-volume/category-chart-high-volume-sample.component.ts
Labels: status: verified

#313 Setting width 15% to the last column in grid-summary sample
  src/app/grid/grid-sample-3/grid-sample-3.component.html
Labels: status: verified

#312 Setting width 15% to the last column in grid-summary sample
  src/app/grid/grid-sample-3/grid-sample-3.component.html
Labels: status: verified

#327 fix(grid-filtering): set percentage width to the last column
  src/app/grid/grid-filtering-sample/grid-filtering-sample.component.html
Labels: status: verified

#328 fix(grid-sample): return where is no data for summaries
  src/app/grid/grid.component.ts
Labels: status: verified

#330 fix(grid-sample): return where is no data for summaries
  src/app/grid/grid.component.ts
Labels: status: verified

#333 Changed the column pinning icon to fa-thumbtack in the grid-column-pinning sample
  .angular-cli.json
  package-lock.json
  package.json
  src/app/grid/grid-crm/grid-crm.component.html
  src/app/grid/grid-crm/grid-crm.component.scss
  src/app/grid/grid-sample-pinning/grid-pinning.component.html
  src/app/grid/grid-sample-pinning/grid-pinning.component.scss
  src/app/grid/grid-sample-pinning/grid-pinning.component.ts
  src/styles.scss
Labels: status: verified

#334 Changed the column pinning icon to fa-thumbtack in the grid-column-pinning sample - 5.3.x
  .angular-cli.json
  package-lock.json
  package.json
  src/app/grid/grid-crm/grid-crm.component.html
  src/app/grid/grid-crm/grid-crm.component.scss
  src/app/grid/grid-sample-pinning/grid-pinning.component.html
  src/app/grid/grid-sample-pinning/grid-pinning.component.scss
  src/app/grid/grid-sample-pinning/grid-pinning.component.ts
  src/styles.scss
Labels: status: verified

#332 fix(marahon-grid): check whether data exist more safety
  src/app/grid/grid.component.ts
Labels: status: verified

#340 IE 11 support
  README.md
  live-editing/LiveEditingManager.ts
  live-editing/README.md
  live-editing/SampleAssetsGenerator.ts
  live-editing/SharedAssetsGenerator.ts
  live-editing/configs/CategoryChartConfigGenerator.ts
  live-editing/configs/ExportCsvConfigGenerator.ts
  live-editing/configs/ExportExcelConfigGenerator.ts
  live-editing/configs/FinancialChartConfigGenerator.ts
  live-editing/configs/GridConfigGenerator.ts
  live-editing/configs/MaskConfigGenerator.ts
  live-editing/configs/core/Config.ts
  live-editing/generators/Generator.ts
  live-editing/generators/LiveEditingFile.ts
  live-editing/generators/SampleAssetsGenerator.ts
  live-editing/generators/SampleDefinitionFile.ts
  live-editing/generators/SharedAssetsFile.ts
  live-editing/generators/SharedAssetsGenerator.ts
  live-editing/generators/SharedAssetsGeneratorArgs.ts
  live-editing/generators/StyleSyntax.ts
  live-editing/services/DependenciesType.ts
  live-editing/services/DependencyResolver.ts
  live-editing/services/SassCompiler.ts
  live-editing/services/TsImportsService.ts
  live-editing/templates/angular-cli-css-support.json.template
  package.json
  src/app/buttons/buttons-sample-1/buttons-sample-1.component.html
  src/app/buttons/buttons-sample-1/buttons-sample-1.component.scss
  src/app/card/card.component.html
  src/app/card/card.component.scss
  src/app/input-group/input-group-sample-5/input-group-sample-5.component.html
  src/app/input-group/input-group-sample-5/input-group-sample-5.component.ts
  src/app/ripple/ripple-sample-1/ripple-sample-1.component.html
  src/app/ripple/ripple-sample-1/ripple-sample-1.component.scss
Labels: status: verified

#344 Remove 'cellAlignStyle' from header templates
  src/app/grid/grid-sample-2/grid-sample-2.component.html
  src/app/grid/grid-sample-4/grid-sample-4.component.html
  src/app/grid/grid-sample-selection/grid-selection.component.html
Labels: grid, status: verified

#342 align items in the pager template
  src/app/grid/grid-paging-sample/grid-paging-sample.component.scss
  src/app/grid/grid-paging-sample/grid-paging-sample.component.ts
  src/app/grid/grid.component.scss
Labels: status: verified

#345 Add grid searching API sample
  live-editing/configs/GridConfigGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/grid/grid-search-sample/data.ts
  src/app/grid/grid-search-sample/grid-search-sample.component.html
  src/app/grid/grid-search-sample/grid-search-sample.component.scss
  src/app/grid/grid-search-sample/grid-search-sample.component.ts
Labels: status: verified

#358 Adding search box to igxGrid on IgniteUI for Angular landing page
  package-lock.json
  src/app/grid/grid-crm/grid-crm.component.html
  src/app/grid/grid-crm/grid-crm.component.scss
  src/app/grid/grid-crm/grid-crm.component.ts
Labels: status: awaiting-test

#364 change card samples images and celebrities names
  src/app/card/card-sample-1/card-sample-1.component.html
  src/app/card/card-sample-2/card-sample-2.component.html
  src/app/card/card-sample-3/card-sample-3.component.html
  src/app/card/card.component.html
  src/app/card/card.component.ts
  src/app/tabs/tabs-sample-3/tabs-sample-3.component.html
  src/assets/images/card/avatars/alicia_keys.jpg
  src/assets/images/card/avatars/brad_stanley.jpg
  src/assets/images/card/avatars/mellow_d.jpg
  src/assets/images/card/media/here_media.jpg
  src/styles.scss
Labels: enhancement, status: verified

#365 change card samples images and celebrities names
  src/app/card/card-sample-1/card-sample-1.component.html
  src/app/card/card-sample-2/card-sample-2.component.html
  src/app/card/card-sample-3/card-sample-3.component.html
  src/app/card/card.component.html
  src/app/card/card.component.ts
  src/app/tabs/tabs-sample-3/tabs-sample-3.component.html
  src/assets/images/card/avatars/alicia_keys.jpg
  src/assets/images/card/avatars/brad_stanley.jpg
  src/assets/images/card/avatars/mellow_d.jpg
  src/assets/images/card/media/here_media.jpg
  src/styles.scss
Labels: enhancement, status: verified

#369 set body overflow to hidden, enhance the card sample
  src/app/card/card.component.html
  src/app/card/card.component.scss
  src/styles.scss
Labels: status: verified
