Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2018-06, with the labels that each got.

#375 styles(tabbar-list) Fix misaligned list items in IE
  src/app/tabbar/tabbar.component.scss
Labels: bug, status: verified

#377 Remove Intl polyfills, remove forEach usage in grid sample
  src/app/grid/grid.component.ts
  src/polyfills.ts
Labels: status: verified

#383 Fix flickering search input
  src/app/grid/grid-crm/grid-crm.component.scss
Labels: bug, status: verified

#382 fix(crm-grid): Fix filtering dialog input
  src/app/grid/grid-crm/grid-crm.component.scss
Labels: bug, status: verified

#381 remove unnessesary styles
  src/app/grid/grid-paging-sample/grid-paging-sample.component.scss
Labels: status: verified

#385 Pinning icon missing
  angular.json
  live-editing/services/DependencyResolver.ts
  package-lock.json
  package.json
  src/app/grid/grid-crm/grid-crm.component.scss
  src/app/grid/grid-sample-pinning/grid-pinning.component.scss
  src/styles.scss
Labels: status: verified

#386 Updated angular-in-memory-web-api
  package-lock.json
  package.json
Labels: status: verified

#366 Replace the toast with custom cell template when loading remote data
  src/app/grid/grid-sample-4/grid-sample-4.component.html
  src/app/grid/grid-sample-4/grid-sample-4.component.scss
  src/app/grid/grid-sample-4/grid-sample-4.component.ts
Labels: enhancement, grid, status: verified

#392 increase paging sample grid height to get rid of vertical scrollbar
  src/app/grid/grid-paging-sample/grid-paging-sample.component.html
Labels: status: verified

#397 Update live editing packages
  live-editing/services/DependencyResolver.ts
Labels: status: verified

#412 docs(grid): Filtering samples updated with the latest changes #1355
  package-lock.json
  package.json
  src/app/grid/grid-filtering-sample/grid-filtering-sample.component.ts
  src/app/grid/grid-remote-filtering-sample/remote-filtering-sample.component.ts
  src/app/grid/grid.component.ts
  src/app/grid/services/remoteFilteringService.ts
  src/app/toggle/toggle-sample-3/toggle-sample-3.component.html
Labels: grid, status: verified

#417 Grid editing sample
  live-editing/configs/GridConfigGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/grid/grid-editing-sample/data.ts
  src/app/grid/grid-editing-sample/grid-editing-sample.component.html
  src/app/grid/grid-editing-sample/grid-editing-sample.component.scss
  src/app/grid/grid-editing-sample/grid-editing-sample.component.spec.ts
  src/app/grid/grid-editing-sample/grid-editing-sample.component.ts
  src/app/grid/grid-editing-sample/product.ts
Labels: status: verified

#409 Multi column headers sample
  live-editing/configs/GridConfigGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/grid/multi-column-headers/data.ts
  src/app/grid/multi-column-headers/multi-column-headers.html
  src/app/grid/multi-column-headers/multi-column-headers.scss
  src/app/grid/multi-column-headers/multi-column-headers.ts
Labels: status: verified

#401 Adding grid-groupby-sample
  live-editing/configs/GridConfigGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/grid/grid-groupby-sample/data.ts
  src/app/grid/grid-groupby-sample/grid-groupby-sample.component.html
  src/app/grid/grid-groupby-sample/grid-groupby-sample.component.scss
  src/app/grid/grid-groupby-sample/grid-groupby-sample.component.spec.ts
  src/app/grid/grid-groupby-sample/grid-groupby-sample.component.ts
Labels: status: verified

#400 docs(grid): Added a sample for the column moving feature #935
  live-editing/configs/GridConfigGenerator.ts
  package-lock.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/grid/grid-moving-sample/grid-moving-sample.component.html
  src/app/grid/grid-moving-sample/grid-moving-sample.component.scss
  src/app/grid/grid-moving-sample/grid-moving-sample.component.ts
Labels: status: verified

#416 Add overlay samples
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/overlay/overlay-sample.component.html
  src/app/overlay/overlay-sample.component.scss
  src/app/overlay/overlay-sample.component.ts
  src/assets/images/overlay/all_directions.png
  src/assets/images/overlay/bottom_center.png
  src/assets/images/overlay/bottom_left.png
  src/assets/images/overlay/bottom_right.png
  src/assets/images/overlay/center.png
  src/assets/images/overlay/center_left.png
  src/assets/images/overlay/center_right.png
  src/assets/images/overlay/down.png
  src/assets/images/overlay/down_left.png
  src/assets/images/overlay/down_right.png
  src/assets/images/overlay/left.png
  src/assets/images/overlay/right.png
  src/assets/images/overlay/top_center.png
  src/assets/images/overlay/top_left.png
  src/assets/images/overlay/top_right.png
  src/assets/images/overlay/up.png
  src/assets/images/overlay/up_left.png
  src/assets/images/overlay/up_right.png
Labels: enhancement, overlay, status: verified

#411 Combo samples
  live-editing/configs/ComboConfigGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/combo/cascading-combos/cascading-combos.component.html
  src/app/combo/cascading-combos/cascading-combos.component.scss
  src/app/combo/cascading-combos/cascading-combos.component.ts
  src/app/combo/cascading-combos/local-data.ts
  src/app/combo/combo-features/combo-features.component.html
  src/app/combo/combo-features/combo-features.component.scss
  src/app/combo/combo-features/combo-features.component.ts
  src/app/combo/combo-features/local-data.ts
  src/app/grid/services/remote.service.ts
  src/app/input-group/input-group-sample-6/input-group-sample-6.component.html
  src/app/input-group/input-group-sample-6/input-group-sample-6.component.scss
  src/app/input-group/input-group-sample-6/input-group-sample-6.component.ts
Labels: combo, status: verified

#418 Add dropdown for new proj structure using overlay
  live-editing/configs/DropDownConfigGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/dropdown/dropdown-sample-1/dropdown-sample-1.component.html
  src/app/dropdown/dropdown-sample-1/dropdown-sample-1.component.scss
  src/app/dropdown/dropdown-sample-1/dropdown-sample-1.component.ts
  src/app/dropdown/dropdown-sample-2/dropdown-sample-2.component.html
  src/app/dropdown/dropdown-sample-2/dropdown-sample-2.component.scss
  src/app/dropdown/dropdown-sample-2/dropdown-sample-2.component.ts
  src/app/dropdown/dropdown-sample-3/dropdown-sample-3.component.html
  src/app/dropdown/dropdown-sample-3/dropdown-sample-3.component.scss
  src/app/dropdown/dropdown-sample-3/dropdown-sample-3.component.ts
Labels: status: verified

#415 docs(radio-group): Added a sample for radio-group
  live-editing/configs/RadioConfigGenerator.ts
  package-lock.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/form-elements/radio/radio-group-sample/radio-group-sample.component.html
  src/app/form-elements/radio/radio-group-sample/radio-group-sample.component.scss
  src/app/form-elements/radio/radio-group-sample/radio-group-sample.component.ts
Labels: radio, status: verified

#422 Fix cut off look
  src/app/grid/multi-column-headers/multi-column-headers.html
  src/app/grid/multi-column-headers/multi-column-headers.scss
Labels: status: verified

#398 docs(toolbar): adding samples for the igxGrid toolbar
  live-editing/configs/GridConfigGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/grid/grid-toolbar-sample/grid-toolbar-sample-1.component.html
  src/app/grid/grid-toolbar-sample/grid-toolbar-sample-1.component.scss
  src/app/grid/grid-toolbar-sample/grid-toolbar-sample-1.component.ts
  src/app/grid/grid-toolbar-sample/grid-toolbar-sample-2.component.html
  src/app/grid/grid-toolbar-sample/grid-toolbar-sample-2.component.scss
  src/app/grid/grid-toolbar-sample/grid-toolbar-sample-2.component.ts
  src/app/grid/grid-toolbar-sample/grid-toolbar-sample-3.component.html
  src/app/grid/grid-toolbar-sample/grid-toolbar-sample-3.component.scss
  src/app/grid/grid-toolbar-sample/grid-toolbar-sample-3.component.ts
Labels: enhancement, status: verified

#403 docs(columnHiding): adding samples for the igxGrid columnHiding
  live-editing/configs/GridConfigGenerator.ts
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/grid/grid-column-hiding-sample/data.ts
  src/app/grid/grid-column-hiding-sample/grid-column-hiding-sample.component.html
  src/app/grid/grid-column-hiding-sample/grid-column-hiding-sample.component.scss
  src/app/grid/grid-column-hiding-sample/grid-column-hiding-sample.component.ts
  src/app/grid/grid-column-hiding-toolbar-sample/data.ts
  src/app/grid/grid-column-hiding-toolbar-sample/grid-column-hiding-toolbar-sample.component.html
  src/app/grid/grid-column-hiding-toolbar-sample/grid-column-hiding-toolbar-sample.component.scss
  src/app/grid/grid-column-hiding-toolbar-sample/grid-column-hiding-toolbar-sample.component.ts
Labels: enhancement, status: verified

#425 Fix misaligned icon
  src/app/grid/grid-sample-3/grid-sample-3.component.scss
Labels: status: verified

#424 docs(groupby): Fixing PK in GroupBy sample
  src/app/grid/grid-groupby-sample/grid-groupby-sample.component.html
Labels: status: verified

#402 fix(grid-crm): Make the avatar column of grid-crm unsearchable and adjust grid's height
  src/app/grid/grid-crm/grid-crm.component.html
Labels: enhancement, grid, status: verified

#436 add stackblitz button
  live-editing/configs/DropDownConfigGenerator.ts
  live-editing/generators/SampleAssetsGenerator.ts
  src/app/dropdown/dropdown-sample-1/dropdown-sample-1.component.ts
  src/app/dropdown/dropdown-sample-2/dropdown-sample-2.component.ts
  src/app/dropdown/dropdown-sample-3/dropdown-sample-3.component.ts
Labels: status: in-test

#441 fix(groupbysample): Removing primaryKey
  src/app/grid/grid-groupby-sample/grid-groupby-sample.component.html
Labels: grid, group by, status: verified

#439 docs(grid): Fixes in column moving demo - added pinned columns
  live-editing/configs/GridConfigGenerator.ts
  src/app/grid/grid-moving-sample/grid-moving-sample.component.html
  src/app/grid/grid-moving-sample/grid-moving-sample.component.scss
  src/app/grid/grid-moving-sample/grid-moving-sample.component.ts
Labels: grid, status: verified

#432 Fix for misaligned cup image and filtered empty summary
  src/app/grid/grid.component.scss
  src/app/grid/grid.component.ts
Labels: grid, status: verified, summaries

#437 Making all columns of the Grid CRM sample movable
  src/app/grid/grid-crm/grid-crm.component.html
Labels: status: verified

#454 Add missing Badge module
  live-editing/configs/GridConfigGenerator.ts
Labels: grid, status: verified

#451 docs(chip): Adding Chip Stackblitz configuration.
  live-editing/configs/ChipConfigGenerator.ts
  live-editing/generators/SampleAssetsGenerator.ts
Labels: chip, status: verified

#455 Fix stackblitz config and other issues
  live-editing/configs/ComboConfigGenerator.ts
  live-editing/configs/InputGroupConfigGenerator.ts
  live-editing/generators/SampleAssetsGenerator.ts
  src/app/combo/cascading-combos/cascading-combos.component.html
  src/app/combo/combo-features/combo-features.component.html
  src/app/combo/combo-features/combo-features.component.ts
  src/app/input-group/reactive-forms/reactive-forms.component.ts
Labels: combo, status: verified

#452 I ganchev add dropdown new proj structure
  src/app/dropdown/dropdown-sample-1/dropdown-sample-1.component.html
  src/app/dropdown/dropdown-sample-2/dropdown-sample-2.component.html
  src/app/dropdown/dropdown-sample-3/dropdown-sample-3.component.html
Labels: status: verified

#460 Added live editing entry components support
  live-editing/configs/core/AppModuleConfig.ts
  live-editing/generators/SampleAssetsGenerator.ts
  live-editing/templates/app.module.ts.template
Labels: status: verified
