Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2018-02, with the labels that each got.

#55 Icon samples rework.
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/icon/icon-sample-1/icon-sample-1.component.css
  src/app/icon/icon-sample-1/icon-sample-1.component.html
  src/app/icon/icon-sample-1/icon-sample-1.component.ts
Labels: enhancement

#50 Demos refactoring
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/form-elements/checkbox/checkbox-sample-1/checkbox-sample-1.component.css
  src/app/form-elements/checkbox/checkbox-sample-1/checkbox-sample-1.component.html
  src/app/form-elements/checkbox/checkbox-sample-1/checkbox-sample-1.component.ts
  src/app/form-elements/checkbox/checkbox-sample-2/checkbox-sample-2.component.css
  src/app/form-elements/checkbox/checkbox-sample-2/checkbox-sample-2.component.html
  src/app/form-elements/checkbox/checkbox-sample-2/checkbox-sample-2.component.ts
  src/app/form-elements/radio/radio-sample-1/radio-sample-1.component.css
  src/app/form-elements/radio/radio-sample-1/radio-sample-1.component.html
  src/app/form-elements/radio/radio-sample-1/radio-sample-1.component.ts
  src/app/form-elements/radio/radio-sample-2/radio-sample-2.component.css
  src/app/form-elements/radio/radio-sample-2/radio-sample-2.component.html
  src/app/form-elements/radio/radio-sample-2/radio-sample-2.component.ts
  src/app/form-elements/switch/switch-sample-1/switch-sample-1.component.css
  src/app/form-elements/switch/switch-sample-1/switch-sample-1.component.html
  src/app/form-elements/switch/switch-sample-1/switch-sample-1.component.ts
  src/app/form-elements/switch/switch-sample-2/switch-sample-2.component.css
  src/app/form-elements/switch/switch-sample-2/switch-sample-2.component.html
  src/app/form-elements/switch/switch-sample-2/switch-sample-2.component.ts
Labels: enhancement

#69 Changed demo app to reflect the badge modifications
  src/app/badge/badge-sample-3/badge-sample-3.component.css
  src/app/badge/badge-sample-3/badge-sample-3.component.html
Labels: bug

#71 igxAvatar demo refactoring
  live-editing/samples.conf.js
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/avatar/avatar-sample-1/avatar-sample-1.component.css
  src/app/avatar/avatar-sample-1/avatar-sample-1.component.html
  src/app/avatar/avatar-sample-1/avatar-sample-1.component.ts
  src/app/avatar/avatar-sample-2/avatar-sample-2.component.css
  src/app/avatar/avatar-sample-2/avatar-sample-2.component.html
  src/app/avatar/avatar-sample-2/avatar-sample-2.component.ts
  src/app/avatar/avatar-sample-3/avatar-sample-3.component.css
  src/app/avatar/avatar-sample-3/avatar-sample-3.component.html
  src/app/avatar/avatar-sample-3/avatar-sample-3.component.ts
  src/app/avatar/avatar.component.html
  src/app/avatar/avatar.component.spec.ts
  src/app/avatar/avatar.component.ts
  src/app/badge/badge.component.css
  src/app/badge/badge.component.html
  src/app/badge/badge.component.spec.ts
  src/app/badge/badge.component.ts
  src/app/form-elements/form-elements.component.css
  src/app/form-elements/form-elements.component.html
  src/app/form-elements/form-elements.component.spec.ts
  src/app/form-elements/form-elements.component.ts
  src/app/navbar/navbar.component.ts
Labels: enhancement

#81 Fixes for badge sample in stackblitz
  live-editing/samples.conf.js
Labels: bug

#96 add new calendar samples
  live-editing/samples.conf.js
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/calendar/calendar-sample-1/calendar-sample-1.component.css
  src/app/calendar/calendar-sample-1/calendar-sample-1.component.html
  src/app/calendar/calendar-sample-1/calendar-sample-1.component.ts
  src/app/calendar/calendar-sample-2/calendar-sample-2.component.css
  src/app/calendar/calendar-sample-2/calendar-sample-2.component.html
  src/app/calendar/calendar-sample-2/calendar-sample-2.component.ts
  src/app/calendar/calendar-sample-3/calendar-sample-3.component.css
  src/app/calendar/calendar-sample-3/calendar-sample-3.component.html
  src/app/calendar/calendar-sample-3/calendar-sample-3.component.ts
  src/app/calendar/calendar-sample-4/calendar-sample-4.component.css
  src/app/calendar/calendar-sample-4/calendar-sample-4.component.html
  src/app/calendar/calendar-sample-4/calendar-sample-4.component.ts
  src/app/calendar/calendar-sample-5/calendar-sample-5.component.css
  src/app/calendar/calendar-sample-5/calendar-sample-5.component.html
  src/app/calendar/calendar-sample-5/calendar-sample-5.component.ts
  src/app/carousel/carousel-sample-1/carousel-sample-1.component.css
  src/app/carousel/carousel-sample-2/carousel-sample-2.component.css
  src/app/carousel/carousel-sample-3/carousel-sample-3.component.css
  src/app/carousel/carousel-sample-4/carousel-sample-4.component.css
Labels: status: in-test

#100 remove igxscroll samples
  live-editing/samples.conf.js
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/scroll/scroll.component.css
  src/app/scroll/scroll.component.html
  src/app/scroll/scroll.component.spec.ts
  src/app/scroll/scroll.component.ts
Labels: status: verified

#99 Datepicker samples update
  .gitignore
  live-editing/sample-asset.handler.js
  live-editing/samples.conf.js
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/datepicker/datepicker-sample-1/datepicker-sample-1.component.css
  src/app/datepicker/datepicker-sample-1/datepicker-sample-1.component.html
  src/app/datepicker/datepicker-sample-1/datepicker-sample-1.component.ts
  src/app/datepicker/datepicker-sample-2/datepicker-sample-2.component.css
  src/app/datepicker/datepicker-sample-2/datepicker-sample-2.component.html
  src/app/datepicker/datepicker-sample-2/datepicker-sample-2.component.ts
  src/app/datepicker/datepicker-sample-3/datepicker-sample-3.component.css
  src/app/datepicker/datepicker-sample-3/datepicker-sample-3.component.html
  src/app/datepicker/datepicker-sample-3/datepicker-sample-3.component.ts
  src/app/datepicker/datepicker-sample-4/datepicker-sample-4.component.css
  src/app/datepicker/datepicker-sample-4/datepicker-sample-4.component.html
  src/app/datepicker/datepicker-sample-4/datepicker-sample-4.component.ts
  src/app/datepicker/datepicker-sample-5/datepicker-sample-5.component.css
  src/app/datepicker/datepicker-sample-5/datepicker-sample-5.component.html
  src/app/datepicker/datepicker-sample-5/datepicker-sample-5.component.ts
  src/app/datepicker/datepicker.component.css
  src/app/datepicker/datepicker.component.html
  src/app/datepicker/datepicker.component.spec.ts
  src/app/datepicker/datepicker.component.ts
Labels: status: verified

#94 Adding Button Group Samples.
  live-editing/samples.conf.js
  package-lock.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/buttonGroup/button-group-sample-1/button-group-sample-1.component.css
  src/app/buttonGroup/button-group-sample-1/button-group-sample-1.component.html
  src/app/buttonGroup/button-group-sample-1/button-group-sample-1.component.ts
  src/app/buttonGroup/button-group-sample-2/button-group-sample-2.component.css
  src/app/buttonGroup/button-group-sample-2/button-group-sample-2.component.html
  src/app/buttonGroup/button-group-sample-2/button-group-sample-2.component.ts
  src/app/buttonGroup/button-group-sample-3/button-group-sample-3.component.css
  src/app/buttonGroup/button-group-sample-3/button-group-sample-3.component.html
  src/app/buttonGroup/button-group-sample-3/button-group-sample-3.component.ts
Labels: status: verified

#97 Adding new samples for the TabBar demo page
  live-editing/samples.conf.js
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/tabbar/tabbar-sample-1/tabbar-sample-1.component.css
  src/app/tabbar/tabbar-sample-1/tabbar-sample-1.component.html
  src/app/tabbar/tabbar-sample-1/tabbar-sample-1.component.ts
  src/app/tabbar/tabbar-sample-2/tabbar-sample-2.component.css
  src/app/tabbar/tabbar-sample-2/tabbar-sample-2.component.html
  src/app/tabbar/tabbar-sample-2/tabbar-sample-2.component.ts
  src/app/tabbar/tabbar.component.css
  src/app/tabbar/tabbar.component.html
  src/app/tabbar/tabbar.component.ts
Labels: status: verified

#87 Fix for theme and fonts
  .angular-cli.json
  live-editing/shared-asset.handler.js
  live-editing/templates/angular-cli.json.template
  package-lock.json
  src/app/app.module.ts
  src/app/calendar/calendar.component.html
  src/app/calendar/calendar.component.ts
  src/app/calendar/themes/google.scss
  src/app/card/card.component.ts
  src/app/carousel/carousel-details/carousel-details.component.ts
  src/app/carousel/carousel-sample-2/carousel-sample-2.component.ts
  src/app/carousel/carousel-sample-3/carousel-sample-3.component.ts
  src/app/carousel/carousel-sample-4/carousel-sample-4.component.ts
  src/app/carousel/carousel.component.ts
  src/app/dialog/dialog.component.ts
  src/app/grid/grid.component.ts
  src/app/label-input/label-input.component.ts
  src/app/layout/layout.component.ts
  src/app/list/list.component.ts
  src/app/navbar/navbar.component.ts
  src/app/progressbar/progressbar.component.ts
  src/index.html
  src/styles.scss
  src/themes.scss
Labels: status: in-test

#102 Boston sample marathon update
  src/app/grid/grid.component.css
  src/app/grid/grid.component.html
  src/app/grid/grid.component.ts
Labels: status: in-test

#101 igniteui-docfx#122 igxNavbar demo update
  live-editing/samples.conf.js
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/navbar/navbar-sample-1/navbar-sample-1.component.css
  src/app/navbar/navbar-sample-1/navbar-sample-1.component.html
  src/app/navbar/navbar-sample-1/navbar-sample-1.component.spec.ts
  src/app/navbar/navbar-sample-1/navbar-sample-1.component.ts
  src/app/navbar/navbar.component.html
  src/app/navbar/navbar.component.ts
Labels: status: in-test

#92 Updated samples for Linear and Circular Progressbars
  live-editing/samples.conf.js
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/circular-progressbar/circular-progressbar.component.css
  src/app/circular-progressbar/circular-progressbar.component.html
  src/app/circular-progressbar/circular-progressbar.component.spec.ts
  src/app/circular-progressbar/circular-progressbar.component.ts
  src/app/linear-progressbar/linear-progressbar-sample-1/linear-progressbar-sample-1.component.css
  src/app/linear-progressbar/linear-progressbar-sample-1/linear-progressbar-sample-1.component.html
  src/app/linear-progressbar/linear-progressbar-sample-1/linear-progressbar-sample-1.component.spec.ts
  src/app/linear-progressbar/linear-progressbar-sample-1/linear-progressbar-sample-1.component.ts
  src/app/linear-progressbar/linear-progressbar-sample-2/linear-progressbar-sample-2.component.css
  src/app/linear-progressbar/linear-progressbar-sample-2/linear-progressbar-sample-2.component.html
  src/app/linear-progressbar/linear-progressbar-sample-2/linear-progressbar-sample-2.component.spec.ts
  src/app/linear-progressbar/linear-progressbar-sample-2/linear-progressbar-sample-2.component.ts
  src/app/linear-progressbar/linear-progressbar.component.css
  src/app/linear-progressbar/linear-progressbar.component.html
  src/app/linear-progressbar/linear-progressbar.component.spec.ts
  src/app/linear-progressbar/linear-progressbar.component.ts
Labels: status: in-test

#106 Added routing to toggle sample 3.
  src/app/app-routing.module.ts
Labels: status: verified

#110 Update Grid Sample
  src/app/grid/grid.component.css
  src/app/grid/grid.component.html
  src/app/grid/grid.component.ts
Labels: status: verified

#114 Fix calendar samples height
  src/app/calendar/calendar-sample-1/calendar-sample-1.component.css
  src/app/calendar/calendar-sample-1/calendar-sample-1.component.html
  src/app/calendar/calendar-sample-5/calendar-sample-5.component.css
  src/app/carousel/carousel-sample-1/carousel-sample-1.component.css
Labels: bug, status: verified

#115 Calendar samples
  src/app/carousel/carousel-sample-1/carousel-sample-1.component.css
  src/app/carousel/carousel-sample-2/carousel-sample-2.component.css
  src/app/carousel/carousel-sample-3/carousel-sample-3.component.css
  src/app/carousel/carousel-sample-4/carousel-sample-4.component.css
Labels: status: verified

#116 Configure igxFor sample to work using the Stackblitz button
  live-editing/samples.conf.js
  src/app/igxFor/igxFor.component.spec.ts
Labels: status: verified

#123 Update Grid sample
  src/app/grid/grid.component.css
  src/app/grid/grid.component.html
  src/app/grid/grid.component.ts
  src/app/grid/services/data.ts
Labels: status: verified
