Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2018-07, with the labels that each got.

#444 IgxOverlay samples refactor
  live-editing/configs/OverlayConfigGenerator.ts
  package-lock.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/overlay/overlay-dynamic-card/overlay-dynamic-card.component.html
  src/app/overlay/overlay-dynamic-card/overlay-dynamic-card.component.scss
  src/app/overlay/overlay-dynamic-card/overlay-dynamic-card.component.ts
  src/app/overlay/overlay-main-1/overlay-main-sample-1.component.html
  src/app/overlay/overlay-main-1/overlay-main-sample-1.component.scss
  src/app/overlay/overlay-main-1/overlay-main-sample-1.component.ts
  src/app/overlay/overlay-main-2/overlay-main-sample-2.component.html
  src/app/overlay/overlay-main-2/overlay-main-sample-2.component.scss
  src/app/overlay/overlay-main-2/overlay-main-sample-2.component.ts
  src/app/overlay/overlay-main-3/overlay-main-sample-3.component.html
  src/app/overlay/overlay-main-3/overlay-main-sample-3.component.scss
  src/app/overlay/overlay-main-3/overlay-main-sample-3.component.ts
  src/app/overlay/overlay-positioning-1/overlay-position-sample-1.component.html
  src/app/overlay/overlay-positioning-1/overlay-position-sample-1.component.scss
  src/app/overlay/overlay-positioning-1/overlay-position-sample-1.component.ts
  src/app/overlay/overlay-positioning-2/overlay-position-sample-2.component.html
  src/app/overlay/overlay-positioning-2/overlay-position-sample-2.component.scss
  src/app/overlay/overlay-positioning-2/overlay-position-sample-2.component.ts
  src/app/overlay/overlay-sample.component.html
  src/app/overlay/overlay-sample.component.ts
  src/app/overlay/overlay-scroll-1/overlay-scroll-sample-1.component.html
  src/app/overlay/overlay-scroll-1/overlay-scroll-sample-1.component.scss
  src/app/overlay/overlay-scroll-1/overlay-scroll-sample-1.component.ts
  src/app/overlay/overlay-scroll-2/overlay-scroll-sample-2.component.html
  src/app/overlay/overlay-scroll-2/overlay-scroll-sample-2.component.scss
  src/app/overlay/overlay-scroll-2/overlay-scroll-sample-2.component.ts
Labels: enhancement, overlay, status: verified

#468 Add remote filtering capabilities to combo sample
  src/app/combo/combo-features/combo-features.component.html
  src/app/combo/combo-features/combo-features.component.ts
  src/app/grid/services/remote.service.ts
Labels: bug, combo, status: verified

#473 style(crm-grid): fix text color for selected row
  src/app/grid/grid-crm/grid-crm.component.scss
Labels: grid, status: verified

#472 style(crm-grid): Fix the problem with ng-deep for CRM sample
  src/app/grid/grid-crm/grid-crm.component.scss
Labels: bug, overlay, status: verified

#461 fix: Update igxToggle samples
  src/app/toggle/toggle-sample-1/toggle-sample-1.component.scss
  src/app/toggle/toggle.component.html
  src/app/toggle/toggle.component.scss
  src/app/toggle/toggle.component.ts
Labels: status: verified

#471 fix #434: Ensure container has size initially since FireFox applie…
  src/app/grid/grid-sample-pinning/grid-pinning.component.html
Labels: status: verified

#475 Typo in combo sample
  src/app/combo/combo-features/combo-features.component.html
Labels: combo

#481 Add scroll to Scrolling sample, add AutoPosition to demo
  src/app/overlay/overlay-positioning-1/overlay-position-sample-1.component.html
  src/app/overlay/overlay-positioning-1/overlay-position-sample-1.component.scss
  src/app/overlay/overlay-positioning-1/overlay-position-sample-1.component.ts
  src/app/overlay/overlay-scroll-1/overlay-scroll-sample-1.component.scss
  src/app/overlay/overlay-scroll-2/overlay-scroll-sample-2.component.scss
Labels: enhancement, overlay, status: in-test, status: verified

#476 provide parent element for linear-bar in templated cells
  src/app/grid/grid-paging-sample/grid-paging-sample.component.html
  src/app/grid/grid-paging-sample/grid-paging-sample.component.scss
  src/app/grid/grid.component.html
  src/app/grid/grid.component.scss
Labels: status: verified

#480 fix(igxChip): Resolves selecting chips is not working in chips sample
  src/app/chip/chip.component.html
  src/app/chip/chip.component.ts
Labels: chip, status: verified

#465 Adding column templates so that images can be displayed #464
  src/app/grid/grid-toolbar-sample/grid-toolbar-sample-1.component.html
  src/app/grid/grid-toolbar-sample/grid-toolbar-sample-1.component.scss
  src/app/grid/grid-toolbar-sample/grid-toolbar-sample-2.component.html
  src/app/grid/grid-toolbar-sample/grid-toolbar-sample-2.component.scss
  src/app/grid/grid-toolbar-sample/grid-toolbar-sample-3.component.html
  src/app/grid/grid-toolbar-sample/grid-toolbar-sample-3.component.scss
Labels: status: verified, toolbar

#486 fix(igxGrid): Implement positioning strategy for igxToggle #482
  src/app/grid/grid-crm/grid-crm.component.html
  src/app/grid/grid-crm/grid-crm.component.ts
Labels: status: verified

#489 Updated cellEditing sample
  src/app/grid/grid-editing-sample/grid-editing-sample.component.ts
Labels: status: verified

#459 docs(list): adding sample demonstrating the loading template
  live-editing/configs/ListConfigGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/list/list-sample-6/list-sample-6.component.html
  src/app/list/list-sample-6/list-sample-6.component.scss
  src/app/list/list-sample-6/list-sample-6.component.ts
Labels: enhancement, list, status: verified

#456 Optimize module imports
  live-editing/configs/GridConfigGenerator.ts
Labels: status: verified

#498 docs(grid): Fixed styling issue in the column moving sample #492
  src/app/grid/grid-moving-sample/grid-moving-sample.component.ts
Labels: grid, status: verified

#497 fixing margin so the igxGrid can occupy more space
  src/app/grid/grid-column-hiding-toolbar-sample/grid-column-hiding-toolbar-sample.component.scss
Labels: grid, status: verified, version: 6.1.x

#500 Combo - Remote Data Sample - Get data on opening
  src/app/combo/combo-features/combo-features.component.html
Labels: combo, status: verified

#504 Adding the missing IgxAvatarModule module
  live-editing/configs/GridConfigGenerator.ts
Labels: status: verified, toolbar

#507 Small fixes in samples - mask, button-group
  src/app/buttonGroup/button-group-sample-1/button-group-sample-1.component.ts
  src/app/mask/mask-sample-1/mask-sample-1.component.ts
Labels: bug, status: verified

#512 Temporary remove the remote data-bind sample of the combo
  src/app/combo/combo-features/combo-features.component.html
  src/app/combo/combo-features/combo-features.component.ts
Labels: combo, status: verified

#505 Overlay - Adjust positioning strategy in scroll demo
  src/app/app.module.ts
  src/app/overlay/overlay-dynamic-card/overlay-dynamic-card.component.ts
  src/app/overlay/overlay-scroll-2/overlay-scroll-sample-2.component.html
  src/app/overlay/overlay-scroll-2/overlay-scroll-sample-2.component.ts
Labels: overlay, status: verified, version: 6.1.x

#514 Added root redirect
  web.config
Labels: status: verified

#515 Overlay - Scroll Strategy Sample - Fix Stackblitz Demo
  live-editing/configs/OverlayConfigGenerator.ts
Labels: overlay, status: verified

#511 fix(samples): Fix dragging chip selects all the text in StackBlitz
  src/app/chip/chip.component.scss
Labels: chip, status: verified

#519 Grid Display Density Sample
  live-editing/configs/GridConfigGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/grid/grid-displaydensity-sample/data.ts
  src/app/grid/grid-displaydensity-sample/grid-displaydensity-sample.component.html
  src/app/grid/grid-displaydensity-sample/grid-displaydensity-sample.component.scss
  src/app/grid/grid-displaydensity-sample/grid-displaydensity-sample.component.spec.ts
  src/app/grid/grid-displaydensity-sample/grid-displaydensity-sample.component.ts
  src/app/grid/grid-editing-sample/grid-editing-sample.component.html
Labels: status: verified

#521 updated styling of gauges
  src/app/gauges/bullet-graph-sample/bullet-graph-sample.component.html
  src/app/gauges/bullet-graph-sample/bullet-graph-sample.component.ts
  src/app/gauges/linear-gauge-sample/linear-gauge-sample.component.html
  src/app/gauges/linear-gauge-sample/linear-gauge-sample.component.ts
  src/app/gauges/radial-gauge-sample/radial-gauge-sample.component.html
  src/app/gauges/radial-gauge-sample/radial-gauge-sample.component.ts
Labels: status: awaiting-test

#522 Update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: enhancement, status: verified

#523 Grid Display Density sample
  src/app/grid/grid-displaydensity-sample/grid-displaydensity-sample.component.html
  src/app/grid/grid-displaydensity-sample/grid-displaydensity-sample.component.ts
Labels: status: verified

#524 Grid crm modifications
  src/app/grid/grid-crm/grid-crm.component.html
  src/app/grid/grid-crm/grid-crm.component.scss
  src/app/grid/grid-crm/grid-crm.component.ts
  src/assets/images/grid/propeller-logo.svg
Labels: grid, status: verified

#526 Updated gauge samples
  src/app/gauges/bullet-graph-sample/bullet-graph-sample.component.html
  src/app/gauges/bullet-graph-sample/bullet-graph-sample.component.scss
  src/app/gauges/bullet-graph-sample/bullet-graph-sample.component.ts
  src/app/gauges/linear-gauge-sample/linear-gauge-sample.component.html
  src/app/gauges/linear-gauge-sample/linear-gauge-sample.component.scss
  src/app/gauges/linear-gauge-sample/linear-gauge-sample.component.ts
  src/app/gauges/radial-gauge-sample/radial-gauge-sample.component.html
  src/app/gauges/radial-gauge-sample/radial-gauge-sample.component.ts
Labels: status: in-test

#527 updated angular DV packages to beta.2 version
  package-lock.json
  package.json
Labels: status: awaiting-test

#542 Adding basic paste from excel sample - 6.1.x
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/grid/grid-paste/data.ts
  src/app/grid/grid-paste/grid-paste-sample.component.html
  src/app/grid/grid-paste/grid-paste-sample.component.scss
  src/app/grid/grid-paste/grid-paste-sample.component.ts
  src/app/grid/grid-paste/paste-handler.directive.ts
Labels: status: verified

#541 Add icon size sample
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/icon/icon-sample-1/icon-sample-1.component.html
  src/app/icon/icon-sample2/icon-sample2.component.html
  src/app/icon/icon-sample2/icon-sample2.component.scss
  src/app/icon/icon-sample2/icon-sample2.component.ts
Labels: enhancement, status: verified

#549 Adding handling for Cmd+V for Mac
  src/app/grid/grid-paste/paste-handler.directive.ts
Labels: status: verified, version: 6.1.x

#520 Adding basic paste from excel sample.
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/grid/grid-paste/data.ts
  src/app/grid/grid-paste/grid-paste-sample.component.html
  src/app/grid/grid-paste/grid-paste-sample.component.scss
  src/app/grid/grid-paste/grid-paste-sample.component.ts
  src/app/grid/grid-paste/paste-handler.directive.ts
Labels: status: verified

#539 fix(columnHiding): adjust columnHiding's height for all browsers #538
  src/app/grid/grid-column-hiding-sample/grid-column-hiding-sample.component.scss
Labels: status: verified

#548 fix(grid): Fixed cut-off samples
  src/app/grid/grid-remote-filtering-sample/remote-filtering-sample.component.html
  src/app/grid/grid-remote-filtering-sample/remote-filtering-sample.component.scss
  src/app/grid/grid-sample-4/grid-sample-4.component.html
  src/app/grid/grid-sample-4/grid-sample-4.component.scss
Labels: grid, status: verified

#552 increased DV packages to 6.1.1
  package-lock.json
  package.json
Labels: status: in-test

#531 Add combo with remote data
  src/app/combo/combo-features/combo-features.component.html
  src/app/combo/combo-features/combo-features.component.ts
Labels: combo, status: verified, version: 6.1.x

#554 Add combo with remote data
  src/app/combo/combo-features/combo-features.component.html
  src/app/combo/combo-features/combo-features.component.ts
Labels: combo, status: verified

#525 fix(*): visualize templated progressbar
  src/app/grid/grid-crm/grid-crm.component.html
Labels: grid, status: verified

#551 Create UI navigation for the samples' components
  live-editing/generators/SampleAssetsGenerator.ts
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/carousel/carousel-sample-1/carousel-sample-1.component.scss
  src/app/carousel/carousel-sample-2/carousel-sample-2.component.scss
  src/app/carousel/carousel-sample-3/carousel-sample-3.component.scss
  src/app/carousel/carousel-sample-4/carousel-sample-4.component.scss
  src/app/category-chart/axis-options/category-chart-axis-options-sample.component.scss
  src/app/category-chart/config-options/category-chart-config-options-sample.component.scss
  src/app/category-chart/custom-tooltips/category-chart-custom-tooltips-sample.component.scss
  src/app/category-chart/overview/category-chart-overview-sample.component.scss
  src/app/export-csv/csv-export-sample-1/csv-export-sample-1.component.scss
  src/app/export-excel/excel-export-sample-1/excel-export-sample-1.component.scss
  src/app/grid/grid-crm/grid-crm.component.html
  src/app/grid/grid-crm/grid-crm.component.scss
  src/app/home/home.component.html
  src/app/home/home.component.scss
  src/app/home/home.component.ts
  src/app/index/docs-layout.component.ts
  src/app/index/index.component.html
  src/app/index/index.component.scss
  src/app/index/index.component.ts
  src/app/slider/slider-sample-4/slider-sample-4.component.scss
  src/app/slider/slider-sample-5/slider-sample-5.component.scss
  src/app/snackbar/snackbar-sample-4/snackbar-sample-4.component.scss
  src/app/tabbar/tabbar.component.html
  src/app/tabbar/tabbar.component.scss
  src/assets/images/rsrcs/igniteui-angular_logo.svg
Labels: status: verified

#555 Update to 6.1.2 version
  package-lock.json
  package.json
Labels: build, status: verified

#546 Fix grid propeller performance
  src/app/grid/grid-crm/grid-crm.component.ts
Labels: status: verified

#567 Combo - Remote Data - Add loading indicator - 6.1.x
  live-editing/configs/ComboConfigGenerator.ts
  src/app/combo/combo-features/combo-features.component.html
  src/app/combo/combo-features/combo-features.component.ts
Labels: combo, status: verified, version: 6.1.x

#566 Combo - Remote Data - Add loading indicator
  live-editing/configs/ComboConfigGenerator.ts
  src/app/combo/combo-features/combo-features.component.html
  src/app/combo/combo-features/combo-features.component.ts
Labels: combo, status: verified

#571 CRM- sample summaries misalignment fix
  src/app/grid/grid-crm/grid-crm.component.html
  src/app/grid/grid-crm/grid-crm.component.ts
Labels: status: verified

#556 Modify home page and add new images
  README.html
  assets/IgniteASCII.png
  assets/Play.svg
  assets/angular-image.png
  assets/angular-logo.png
  assets/background.png
  assets/components-icon.svg
  assets/ig-logo.svg
  assets/installing-CLI.gif
  assets/nodeJS-logo.png
  assets/responsive-icon.svg
  assets/usage-CLI.gif
  assets/vscode.png
  assets/window-bar.svg
  readmeStyle.css
  src/app/home/home.component.html
  src/app/home/home.component.scss
  src/app/home/home.component.ts
  src/app/index/index.component.html
  src/app/index/index.component.scss
  src/assets/images/home/Play.svg
  src/assets/images/home/angular-image.png
  src/assets/images/home/angular-logo.png
  src/assets/images/home/hero-background.png
  src/assets/images/home/ig-logo.svg
  src/assets/images/home/installing-CLI.gif
  src/assets/images/home/usage-CLI.gif
Labels: status: verified
