Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2019-02, with the labels that each got.

#924 fix(date-picker): Updated date picker selector in samples #2386
  src/app/data-entries/input-group/input-group-sample-6/input-group-sample-6.component.html
  src/app/data-entries/input-group/reactive-forms/reactive-forms.component.html
  src/app/data-entries/input-group/reactive-forms/reactive-forms.component.scss
  src/app/grid/grid-editing-sample/grid-editing-sample.component.html
  src/app/scheduling/datepicker/datepicker-sample-1/datepicker-sample-1.component.html
  src/app/scheduling/datepicker/datepicker-sample-2/datepicker-sample-2.component.html
  src/app/scheduling/datepicker/datepicker-sample-3/datepicker-sample-3.component.html
  src/app/scheduling/datepicker/datepicker-sample-4/datepicker-sample-4.component.html
  src/app/scheduling/datepicker/datepicker-sample-5/datepicker-sample-5.component.html
  src/app/theming/dark-theme-sample/dark-theme-sample.component.html
  src/app/theming/default-theme-sample/default-theme-sample.component.html
  src/app/theming/theme-chooser/theme-chooser-sample.component.html
Labels: date picker, status: verified, version: 7.2.x

#932 Live editing refactoring
  .vscode/launch.json
  README.md
  live-editing/LiveEditingManager.ts
  live-editing/README.md
  live-editing/configs/LocalizationConfigGenerator.ts
  live-editing/generators/ConfigGenerators.ts
  live-editing/generators/Generator.ts
  live-editing/generators/Routes.ts
  live-editing/generators/SampleAssetsGenerator.ts
  live-editing/services/DependencyResolver.ts
  live-editing/services/TsImportsService.ts
  package-lock.json
  package.json
Labels: status: verified

#935 Fixing badges samples
  src/app/data-display/badge/badge-sample-3/badge-sample-3.component.html
  src/app/data-display/badge/badge-sample-3/badge-sample-3.component.scss
Labels: status: verified

#929 Changing ripple target for tabbar sample
  src/app/layouts/tabbar/tabbar.component.html
Labels: status: verified

#930 Removing explicitly column widths set in PRs 842 838 800
  src/app/grid/grid-conditional-cell-style/grid-conditional-cell-style.component.html
  src/app/grid/grid-custom-filtering/grid-custom-filtering.component.html
  src/app/grid/grid-filtering-sample/grid-filtering-sample.component.html
  src/app/grid/grid-paging-sample/grid-paging-sample.component.html
  src/app/grid/grid-paste/grid-paste-sample.component.html
  src/app/grid/grid-remote-filtering-sample/remote-filtering-sample.component.html
  src/app/grid/grid-resizing-sample/grid-resizing-sample.component.html
  src/app/grid/grid-row-editing-sample/grid-row-editing-sample.component.html
  src/app/grid/grid-search-sample/grid-search-sample.component.html
  src/app/grid/grid-sorting-sample/grid-sorting-sample.component.html
  src/app/grid/grid-toolbar-sample/grid-toolbar-sample-1.component.html
  src/app/grid/grid-toolbar-sample/grid-toolbar-sample-1.component.scss
  src/app/grid/grid-toolbar-sample/grid-toolbar-sample-2.component.html
  src/app/grid/grid-toolbar-sample/grid-toolbar-sample-2.component.scss
  src/app/grid/grid-toolbar-sample/grid-toolbar-sample-3.component.html
  src/app/grid/grid-toolbar-sample/grid-toolbar-sample-3.component.scss
  src/app/grid/multi-column-headers/multi-column-headers.html
  src/app/services/export-excel/excel-export-sample-1/excel-export-sample-1.component.html
  src/app/services/localization-samples/localization-sample-1/localization-sample-1.component.html
  src/app/services/localization-samples/localization-sample-2/localization-sample-2.component.html
  src/app/services/localization-samples/localization-sample-3/localization-sample-3.component.html
  src/app/theming/dark-theme-sample/dark-theme-sample.component.html
  src/app/theming/default-theme-sample/default-theme-sample.component.html
  src/app/theming/theme-chooser/theme-chooser-sample.component.html
  src/app/tree-grid/tree-grid-childdatakey-sample/tree-grid-childdatakey-sample.component.html
  src/app/tree-grid/tree-grid-primaryforeignkey-sample/tree-grid-primaryforeignkey-sample.component.html
  src/app/tree-grid/tree-grid-row-edit/tree-grid-row-editing-sample.component.html
Labels: status: verified

#943 Clear intervals and subscriptions when the component is destroyed
  src/app/grid-finjs/grid-finjs-demo.component.ts
  src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
Labels: status: verified

#945 Update ignite ui angular to 7.1.5
  package-lock.json
  package.json
  src/app/grid-finjs/grid-finjs-demo.component.html
  src/app/layouts/expansion-panel/expansion-sample-7/expansion-sample-7.component.html
  src/app/treegrid-finjs/tree-grid-finjs-sample.component.html
Labels: status: verified

#967 xsharp - updated packages and fixed DC styles
  .vscode/settings.json
  package-lock.json
  package.json
  src/app/charts/data-chart/data-chart-axis-locations/data-chart-axis-locations.component.scss
  src/app/charts/data-chart/data-chart-axis-settings/data-chart-axis-settings.component.html
  src/app/charts/data-chart/data-chart-axis-settings/data-chart-axis-settings.component.scss
  src/app/charts/data-chart/data-chart-axis-sharing/data-chart-axis-sharing.component.scss
  src/app/charts/data-chart/data-chart-axis-types/data-chart-axis-types.component.html
  src/app/charts/data-chart/data-chart-axis-types/data-chart-axis-types.component.scss
  src/app/charts/data-chart/data-chart-axis-types/data-chart-axis-types.component.ts
  src/app/charts/data-chart/data-chart-legends/data-chart-legends.component.html
  src/app/charts/data-chart/data-chart-legends/data-chart-legends.component.scss
  src/app/charts/data-chart/data-chart-navigation/data-chart-navigation.component.html
  src/app/charts/data-chart/data-chart-navigation/data-chart-navigation.component.scss
  src/app/charts/data-chart/data-chart-overview/data-chart-overview.component.html
  src/app/charts/data-chart/data-chart-overview/data-chart-overview.component.scss
  src/app/charts/data-chart/data-chart-performance/data-chart-performance.component.scss
  src/app/charts/data-chart/data-chart-series-animations/data-chart-series-animations.component.scss
  src/app/charts/data-chart/data-chart-series-annotations/data-chart-series-annotations.component.html
  src/app/charts/data-chart/data-chart-series-annotations/data-chart-series-annotations.component.scss
  src/app/charts/data-chart/data-chart-series-highlighting/data-chart-series-highlighting.component.html
  src/app/charts/data-chart/data-chart-series-highlighting/data-chart-series-highlighting.component.scss
  src/app/charts/data-chart/data-chart-series-markers/data-chart-series-markers.component.scss
  src/app/charts/data-chart/data-chart-series-tooltips/data-chart-series-tooltips.component.html
  src/app/charts/data-chart/data-chart-series-tooltips/data-chart-series-tooltips.component.scss
  src/app/charts/data-chart/data-chart-series-trendlines/data-chart-series-trendlines.component.html
  src/app/charts/data-chart/data-chart-series-trendlines/data-chart-series-trendlines.component.scss
  src/app/charts/data-chart/data-chart-synchronization/data-chart-synchronization.component.scss
  src/app/charts/data-chart/data-chart-titles/data-chart-titles.component.html
  src/app/charts/data-chart/data-chart-titles/data-chart-titles.component.scss
  src/app/charts/data-chart/data-chart-type-category-series/data-chart-type-category-series.component.scss
  src/app/charts/data-chart/data-chart-type-financial-series/data-chart-type-financial-series.component.html
  src/app/charts/data-chart/data-chart-type-financial-series/data-chart-type-financial-series.component.scss
  src/app/charts/data-chart/data-chart-type-polar-series/data-chart-type-polar-series.component.scss
  src/app/charts/data-chart/data-chart-type-radial-series/data-chart-type-radial-series.component.scss
  src/app/charts/data-chart/data-chart-type-range-series/data-chart-type-range-series.component.scss
  src/app/charts/data-chart/data-chart-type-scatter-area-series/data-chart-type-scatter-area-series.component.scss
  src/app/charts/data-chart/data-chart-type-scatter-contour-series/data-chart-type-scatter-contour-series.component.html
  src/app/charts/data-chart/data-chart-type-scatter-contour-series/data-chart-type-scatter-contour-series.component.scss
  src/app/charts/data-chart/data-chart-type-scatter-density-series/data-chart-type-scatter-density-series.component.scss
  src/app/charts/data-chart/data-chart-type-scatter-series/data-chart-type-scatter-series.component.scss
  src/app/charts/data-chart/data-chart-type-scatter-shape-series/data-chart-type-scatter-shape-series.component.scss
  src/app/charts/data-chart/data-chart-type-stacked-series/data-chart-type-stacked-series.component.scss
  src/app/charts/data-chart/data-chart-type-value-overlay/data-chart-type-value-overlay.component.scss
Labels: status: in-review

#969 Updating igniteui-angular version to 7.2.0-beta.3
  package-lock.json
  package.json
  src/app/grid-crm/grid-crm/grid-crm.component.scss
Labels: build

#968 xsharp - fixed config generator for DataChart
  live-editing/LiveEditingManager.ts
  live-editing/configs/DataChartConfigGenerator.ts
  live-editing/configs/DoughnutChartConfigGenerator.ts
  live-editing/generators/MetaDataGenerator.ts
  live-editing/generators/SampleAssetsGenerator.ts
  live-editing/generators/SharedAssetsGenerator.ts
Labels: status: in-review

#973 xsharp - fixed lint/codacy issues in DC configs
  live-editing/LiveEditingManager.ts
  live-editing/configs/DataChartConfigGenerator.ts
  live-editing/configs/DoughnutChartConfigGenerator.ts
  live-editing/generators/SampleAssetsGenerator.ts
  src/app/charts/data-chart/SampleCategoryData.ts
  src/app/charts/data-chart/SampleDensityData.ts
  src/app/charts/data-chart/SampleFinancialData.ts
  src/app/charts/data-chart/SamplePolarData.ts
  src/app/charts/data-chart/SampleRadialData.ts
  src/app/charts/data-chart/SampleRangeData.ts
  src/app/charts/data-chart/SampleScatterData.ts
  src/app/charts/data-chart/SampleScatterStats.ts
  src/app/charts/data-chart/SampleShapeData.ts
  src/app/charts/data-chart/SharedData.ts
  src/app/charts/data-chart/data-chart-overview/data-chart-overview.component.ts
  src/app/charts/data-chart/data-chart-samples-module.ts
Labels: status: in-review

#972 Increased the RAM limit to 8 GB
  .vscode/settings.json
  package.json
Labels: status: verified

#876 Updating dependencies
  gulpfile.js
  live-editing/README.md
  live-editing/configs/GridCRMConfigGenerator.ts
  live-editing/configs/GridConfigGenerator.ts
  live-editing/configs/GridFinjsConfigGenerator.ts
  live-editing/configs/LocalizationConfigGenerator.ts
  live-editing/configs/ThemingConfigGenerator.ts
  live-editing/configs/TreeGridFinjsConfigGenerator.ts
  live-editing/generators/SampleAssetsGenerator.ts
  package-lock.json
  package.json
  src/app/charts/category-chart/category-chart-performance-samples.module.ts
  src/app/charts/category-chart/category-chart-samples.module.ts
  src/app/charts/charts-routing.module.ts
  src/app/charts/doughnut-chart/doughnut-chart-samples.module.ts
  src/app/charts/financial-chart/financial-chart-samples.module.ts
  src/app/charts/pie-chart/pie-chart-samples.module.ts
  src/app/data-entries/input-group/input-group-sample-5/input-group-sample-5.component.ts
Labels: status: verified

#914 Updating the fixing the Chip sample
  src/app/data-display/chip/chip.component.html
  src/app/data-display/chip/chip.component.ts
Labels: chip, status: verified

#978 Updating igniteui-angular version to 7.2.0-beta.3
  package-lock.json
  package.json
  src/main.ts
Labels: status: verified

#970 IgxSelect samples
  live-editing/configs/SelectConfigGenerator.ts
  live-editing/generators/ConfigGenerators.ts
  src/app/data-entries/data-entries-routes-data.ts
  src/app/data-entries/data-entries-routing.module.ts
  src/app/data-entries/data-entries.module.ts
  src/app/data-entries/select/select-sample-1/select-sample-1.component.html
  src/app/data-entries/select/select-sample-1/select-sample-1.component.scss
  src/app/data-entries/select/select-sample-1/select-sample-1.component.ts
  src/app/data-entries/select/select-sample-2/select-sample-2.component.html
  src/app/data-entries/select/select-sample-2/select-sample-2.component.scss
  src/app/data-entries/select/select-sample-2/select-sample-2.component.ts
  src/app/data-entries/select/select-sample-3/select-sample-3.component.html
  src/app/data-entries/select/select-sample-3/select-sample-3.component.scss
  src/app/data-entries/select/select-sample-3/select-sample-3.component.ts
  src/app/data-entries/select/select-sample-4/select-sample-4.component.html
  src/app/data-entries/select/select-sample-4/select-sample-4.component.scss
  src/app/data-entries/select/select-sample-4/select-sample-4.component.ts
Labels: select, status: verified, version: 7.2.x

#939 Add exporting services to the Grid modules
  live-editing/configs/GridFinjsConfigGenerator.ts
  live-editing/configs/TreeGridConfigGenerator.ts
  live-editing/configs/TreeGridFinjsConfigGenerator.ts
Labels: status: verified

#980 Introduced new command npm run start:live-editing
  README.md
  package.json
Labels: status: verified

#810 Samples - Overlay - Add ElasticStrategy to Position + Scroll samples
  src/app/interactions/overlay/overlay-positioning-1/overlay-position-sample-1.component.html
  src/app/interactions/overlay/overlay-positioning-1/overlay-position-sample-1.component.scss
  src/app/interactions/overlay/overlay-positioning-1/overlay-position-sample-1.component.ts
  src/app/interactions/overlay/overlay-positioning-2/overlay-position-sample-2.component.scss
  src/app/interactions/overlay/overlay-scroll-1/overlay-scroll-sample-1.component.html
  src/app/interactions/overlay/overlay-scroll-1/overlay-scroll-sample-1.component.scss
  src/app/interactions/overlay/overlay-scroll-1/overlay-scroll-sample-1.component.ts
  src/app/interactions/overlay/overlay-scroll-2/overlay-scroll-sample-2.component.scss
Labels: overlay, status: in-test

#918 Prefixing css styles for every sample
  live-editing/services/SassCompiler.ts
Labels: StackBlitz, enhancement, status: verified

#983 Adding remote pagin sample with custom template
  live-editing/configs/GridConfigGenerator.ts
  src/app/grid/grid-remote-paging-sample/remote-paging-sample.component.html
  src/app/grid/grid-remote-paging-sample/remote-paging-sample.component.scss
  src/app/grid/grid-remote-paging-sample/remote-paging-sample.component.ts
Labels: status: verified

#928 Autocomplete samples
  live-editing/configs/AutocompleteConfigGenerator.ts
  live-editing/configs/ComboConfigGenerator.ts
  live-editing/configs/InputGroupConfigGenerator.ts
  live-editing/generators/ConfigGenerators.ts
  src/app/data-display/data-display.module.ts
  src/app/data-entries/autocomplete/autocomplete-remote/autocomplete-remote.component.html
  src/app/data-entries/autocomplete/autocomplete-remote/autocomplete-remote.component.scss
  src/app/data-entries/autocomplete/autocomplete-remote/autocomplete-remote.component.ts
  src/app/data-entries/autocomplete/autocomplete/autocomplete.component.html
  src/app/data-entries/autocomplete/autocomplete/autocomplete.component.scss
  src/app/data-entries/autocomplete/autocomplete/autocomplete.component.ts
  src/app/data-entries/autocomplete/movie/movie.component.html
  src/app/data-entries/autocomplete/movie/movie.component.scss
  src/app/data-entries/autocomplete/movie/movie.component.ts
  src/app/data-entries/data-entries-routes-data.ts
  src/app/data-entries/data-entries-routing.module.ts
  src/app/data-entries/data-entries.module.ts
  src/app/data-entries/input-group/input-group-sample-6/input-group-sample-6.component.html
  src/app/data-entries/input-group/input-group-sample-6/input-group-sample-6.component.scss
  src/app/data-entries/input-group/input-group-sample-6/input-group-sample-6.component.ts
  src/app/data-entries/input-group/reactive-forms/reactive-forms.component.html
  src/app/data-entries/input-group/reactive-forms/reactive-forms.component.scss
  src/app/data-entries/input-group/reactive-forms/reactive-forms.component.ts
  src/app/grid/services/remote.service.ts
Labels: autocomplete, status: verified, version: 7.2.x

#987 Routing exception fix
  src/app/index/index.component.ts
Labels: status: verified

#906 Update highlight samples after search refactoring
  src/app/data-display/text-highlight/text-highlight-sample-1/text-highlight-sample-1.component.html
  src/app/data-display/text-highlight/text-highlight-sample-1/text-highlight-sample-1.component.ts
  src/app/data-display/text-highlight/text-highlight-sample-2/text-highlight-sample-2.component.html
  src/app/data-display/text-highlight/text-highlight-sample-2/text-highlight-sample-2.component.ts
Labels: search, status: verified

#985 Set close on outside click to false
  src/app/interactions/toggle/toggle.component.ts
Labels: status: verified, toggle, version: 7.2.x

#971 Add TreeGrid Aggregations Sample
  live-editing/configs/TreeGridFinjsConfigGenerator.ts
  src/app/grid-finjs/grid-finjs.module.ts
  src/app/treegrid-finjs/hierFinancialData.ts
  src/app/treegrid-finjs/tree-grid-finjs-sample.component.html
  src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
  src/app/treegrid-finjs/tree-grid-grouping.pipe.ts
  src/app/treegrid-finjs/treeLocalData.service.ts
  src/app/treegrid-finjs/treegrid-finjs.module.ts
Labels: status: verified, tree-grid, version: 7.2.x

#813 Add timepicker dropdown sample.
  live-editing/configs/TimePickerConfigGenerator.ts
  src/app/app.module.ts
  src/app/scheduling/scheduling-routes-data.ts
  src/app/scheduling/scheduling-routing.module.ts
  src/app/scheduling/scheduling.module.ts
  src/app/scheduling/timepicker/timepicker-dropdown/timepicker-dropdown.component.html
  src/app/scheduling/timepicker/timepicker-dropdown/timepicker-dropdown.component.scss
  src/app/scheduling/timepicker/timepicker-dropdown/timepicker-dropdown.component.ts
Labels: status: verified, time picker, version: 7.2.x

#992 Fix TreeGrid Aggregations Stackblitz config
  live-editing/configs/TreeGridFinjsConfigGenerator.ts
  src/app/treegrid-finjs/tree-grid-finjs-sample.component.html
Labels: status: verified, tree-grid, version: 7.2.x

#989 docs(date-picker): Added a sample for editable date-picker #3034
  src/app/scheduling/datepicker/datepicker-dropdown/datepicker-dropdown.component.html
  src/app/scheduling/datepicker/datepicker-dropdown/datepicker-dropdown.component.scss
  src/app/scheduling/datepicker/datepicker-dropdown/datepicker-dropdown.component.ts
  src/app/scheduling/datepicker/datepicker-sample-1/datepicker-sample-1.component.html
  src/app/scheduling/datepicker/datepicker-sample-3/datepicker-sample-3.component.html
  src/app/scheduling/datepicker/datepicker-sample-4/datepicker-sample-4.component.html
  src/app/scheduling/scheduling-routes-data.ts
  src/app/scheduling/scheduling-routing.module.ts
  src/app/scheduling/scheduling.module.ts
  src/app/theming/theme-chooser/theme-chooser-sample.component.ts
Labels: date picker, status: verified, version: 7.2.x

#997 Update version
  package-lock.json
  package.json
Labels: status: verified

#1001 fix(igxSelect): Better items positioning illustration( with less items)
  src/app/data-entries/select/select-sample-1/select-sample-1.component.ts
Labels: select, status: verified, version: 7.2.x

#1000 Add config dor datepicker-dropdown
  live-editing/configs/DatePickerConfigGenerator.ts
Labels: date picker, status: verified

#1004 Adding IgxCsvExporterService provider #1002
  src/app/grid-crm/grid-crm.module.ts
Labels: status: verified, toolbar

#998 Updating the samples after initial review
  src/app/hierarchical-grid/data.ts
  src/app/hierarchical-grid/hierarchical-grid-column-hiding/hierarchical-grid-custom-hiding.component.html
  src/app/hierarchical-grid/hierarchical-grid-column-hiding/hierarchical-grid-hiding.component.html
  src/app/hierarchical-grid/hierarchical-grid-column-moving/hierarchical-grid-moving.component.html
  src/app/hierarchical-grid/hierarchical-grid-column-pinning/hierarchical-grid-pinning.component.html
  src/app/hierarchical-grid/hierarchical-grid-column-resizing/hierarchical-grid-resizing.component.html
  src/app/hierarchical-grid/hierarchical-grid-display-density/hierarchical-grid-density.component.html
  src/app/hierarchical-grid/hierarchical-grid-editing/data.ts
  src/app/hierarchical-grid/hierarchical-grid-editing/hierarchical-grid-editing.component.html
  src/app/hierarchical-grid/hierarchical-grid-filtering/hierarchical-grid-custom-filtering.component.html
  src/app/hierarchical-grid/hierarchical-grid-filtering/hierarchical-grid-filtering.component.html
  src/app/hierarchical-grid/hierarchical-grid-multi-column-headers/hierarchical-grid-multi-column.component.html
  src/app/hierarchical-grid/hierarchical-grid-paging/hierarchical-grid-paging.component.html
  src/app/hierarchical-grid/hierarchical-grid-paging/hierarchical-grid-remote-paging.component.html
  src/app/hierarchical-grid/hierarchical-grid-paging/hierarchical-grid-remote-paging.component.ts
  src/app/hierarchical-grid/hierarchical-grid-selection/hierarchical-grid-selection.component.html
  src/app/hierarchical-grid/hierarchical-grid-sorting/hierarchical-grid-sorting.component.html
  src/app/hierarchical-grid/hierarchical-grid-summary/hierarchical-grid-summary.component.html
  src/app/hierarchical-grid/hierarchical-grid-summary/hierarchical-grid-summary.component.ts
  src/app/hierarchical-grid/hierarchical-grid-toolbar/hierarchical-grid-toolbar-custom.component.html
  src/app/hierarchical-grid/hierarchical-grid-toolbar/hierarchical-grid-toolbar-title.component.html
Labels: hierarchical-grid, status: verified, version: 7.2.x

#1010 Replace paragraphs with divs in the TextHighlight samples
  src/app/data-display/text-highlight/text-highlight-sample-1/text-highlight-sample-1.component.html
  src/app/data-display/text-highlight/text-highlight-sample-2/text-highlight-sample-2.component.html
  src/app/data-display/text-highlight/text-highlight-sample-2/text-highlight-sample-2.component.ts
Labels: search, status: verified
