Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2019-11, with the labels that each got.

#1562 Enhance chart integration (vnext)
  src/app/grid/grid-dynamic-chart-data/chart.service.ts
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.html
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.scss
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.ts
  src/assets/images/svg/charts/100StackedArea.svg
  src/assets/images/svg/charts/100StackedBar.svg
  src/assets/images/svg/charts/100StackedColumn.svg
  src/assets/images/svg/charts/100StackedLine.svg
  src/assets/images/svg/charts/BubbleScatter.svg
  src/assets/images/svg/charts/GroupedArea.svg
  src/assets/images/svg/charts/GroupedBar.svg
  src/assets/images/svg/charts/GroupedColumn.svg
  src/assets/images/svg/charts/GroupedLine.svg
  src/assets/images/svg/charts/LineScatter.svg
  src/assets/images/svg/charts/Pie.svg
  src/assets/images/svg/charts/PointScatter.svg
  src/assets/images/svg/charts/StackedArea.svg
  src/assets/images/svg/charts/StackedBar.svg
  src/assets/images/svg/charts/StackedColumn.svg
  src/assets/images/svg/charts/StackedLine.svg
Labels: status: verified

#1563 Enhance chart integration (master)
  src/app/grid/grid-dynamic-chart-data/chart.service.ts
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.html
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.scss
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.ts
  src/assets/images/svg/charts/100StackedArea.svg
  src/assets/images/svg/charts/100StackedBar.svg
  src/assets/images/svg/charts/100StackedColumn.svg
  src/assets/images/svg/charts/100StackedLine.svg
  src/assets/images/svg/charts/BubbleScatter.svg
  src/assets/images/svg/charts/GroupedArea.svg
  src/assets/images/svg/charts/GroupedBar.svg
  src/assets/images/svg/charts/GroupedColumn.svg
  src/assets/images/svg/charts/GroupedLine.svg
  src/assets/images/svg/charts/LineScatter.svg
  src/assets/images/svg/charts/Pie.svg
  src/assets/images/svg/charts/PointScatter.svg
  src/assets/images/svg/charts/StackedArea.svg
  src/assets/images/svg/charts/StackedBar.svg
  src/assets/images/svg/charts/StackedColumn.svg
  src/assets/images/svg/charts/StackedLine.svg
Labels: status: verified

#1566 Fix issue 1564 vnext
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.html
Labels: status: verified

#1569 Update vNext to igniteui-angular 9.0.0-beta.2
  live-editing/configs/GridConfigGenerator.ts
  package-lock.json
  package.json
  src/app/grid-crm/grid-crm/grid-crm.component.scss
  src/app/grid-finjs/grid-finjs-demo.component.html
  src/app/grid/grid-dynamic-chart-data/context-menu/context-menu.component.html
  src/app/grid/grid-row-drag/grid-row-drag.component.ts
  src/app/grid/grid-toolbar-style/grid-toolbar-style.component.scss
  src/app/hierarchical-grid/hierarchical-grid-editing-events/hierarchical-grid-editing-events.component.ts
  src/app/hierarchical-grid/hierarchical-grid-paging-style/hierarchical-grid-paging-style.component.scss
  src/app/hierarchical-grid/hierarchical-grid-toolbar-style/hierarchical-grid-toolbar-style.component.scss
  src/app/tree-grid/tree-grid-paging-style/tree-grid-paging-style-sample.component.scss
  src/app/tree-grid/tree-grid-toolbar-style/tree-grid-toolbar-style.component.scss
Labels: status: verified, version: 9.0.x

#1568 Fix issues for chart integration sample (vnext)
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.html
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.scss
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.ts
Labels: status: verified

#1567 Fix issues for chart integration (master)
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.html
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.scss
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.ts
Labels: status: verified

#1558 Update grid remote sorting/filtering samples - vNext
  src/app/grid/grid-remote-filtering-sample/remote-filtering-sample.component.html
  src/app/grid/grid-remote-filtering-sample/remote-filtering-sample.component.ts
  src/app/tree-grid/tree-grid-remote-filtering-sample/tree-grid-remote-filtering-sample.component.html
  src/app/tree-grid/tree-grid-remote-filtering-sample/tree-grid-remote-filtering-sample.component.ts
Labels: ig-grid, ig-hierarchical-grid, ig-tree-grid, status: verified

#1561 Cell styles demo
  live-editing/configs/GridConfigGenerator.ts
  live-editing/configs/TreeGridConfigGenerator.ts
  package-lock.json
  src/app/grid/grid-conditional-cell-style-2/grid-conditional-cell-style-2.component.html
  src/app/grid/grid-conditional-cell-style-2/grid-conditional-cell-style-2.component.scss
  src/app/grid/grid-conditional-cell-style-2/grid-conditional-cell-style-2.component.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
  src/app/tree-grid/tree-grid-conditional-cell-style-2/tree-grid-conditional-cell-style-2.component.html
  src/app/tree-grid/tree-grid-conditional-cell-style-2/tree-grid-conditional-cell-style-2.component.scss
  src/app/tree-grid/tree-grid-conditional-cell-style-2/tree-grid-conditional-cell-style-2.component.ts
  src/app/tree-grid/tree-grid-routes-data.ts
  src/app/tree-grid/tree-grid-routing.module.ts
  src/app/tree-grid/tree-grid.module.ts
Labels: status: verified

#1579 Cell styles demo master
  live-editing/configs/GridConfigGenerator.ts
  live-editing/configs/TreeGridConfigGenerator.ts
  src/app/grid/grid-conditional-cell-style-2/grid-conditional-cell-style-2.component.html
  src/app/grid/grid-conditional-cell-style-2/grid-conditional-cell-style-2.component.scss
  src/app/grid/grid-conditional-cell-style-2/grid-conditional-cell-style-2.component.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
  src/app/tree-grid/tree-grid-conditional-cell-style-2/tree-grid-conditional-cell-style-2.component.html
  src/app/tree-grid/tree-grid-conditional-cell-style-2/tree-grid-conditional-cell-style-2.component.scss
  src/app/tree-grid/tree-grid-conditional-cell-style-2/tree-grid-conditional-cell-style-2.component.ts
  src/app/tree-grid/tree-grid-routes-data.ts
  src/app/tree-grid/tree-grid-routing.module.ts
  src/app/tree-grid/tree-grid.module.ts
Labels: status: verified

#1560 Demonstrating setOffset method in a drag/drop sample
  src/app/interactions/drag-drop/dialog-sample/drag-dialog-sample.component.html
  src/app/interactions/drag-drop/dialog-sample/drag-dialog-sample.component.ts
Labels: drag-drop, status: verified

#1581 Adding a fix for a not working clear button.
  src/app/data-entries/input-group/input-group-sample-5/input-group-sample-5.component.ts
Labels: input-group, status: verified

#1583 Adding a fix for a not working clear button.
  src/app/data-entries/input-group/input-group-sample-5/input-group-sample-5.component.ts
Labels: input-group, status: verified

#1584 Update toolbar style samples - vNext
  src/app/grid-crm/grid-crm/grid-crm.component.scss
  src/app/grid/grid-toolbar-style/grid-toolbar-style.component.scss
  src/app/hierarchical-grid/hierarchical-grid-toolbar-style/hierarchical-grid-toolbar-style.component.scss
  src/app/tree-grid/tree-grid-toolbar-style/tree-grid-toolbar-style.component.scss
Labels: status: verified, styling, toolbar

#1590 Update igniteui-angular to 9 beta 3
  live-editing/configs/CarouselConfigGenerator.ts
  package-lock.json
  package.json
Labels: status: verified

#1557 samples(grid): Adding extenral filtering samples #1546
  live-editing/configs/GridConfigGenerator.ts
  live-editing/configs/HierarchicalGridConfigGenerator.ts
  live-editing/configs/TreeGridConfigGenerator.ts
  src/app/grid/grid-external-advanced-filtering/grid-external-advanced-filtering.component.html
  src/app/grid/grid-external-advanced-filtering/grid-external-advanced-filtering.component.scss
  src/app/grid/grid-external-advanced-filtering/grid-external-advanced-filtering.component.ts
  src/app/grid/grid-external-excel-style-filtering/grid-external-excel-style-filtering.component.html
  src/app/grid/grid-external-excel-style-filtering/grid-external-excel-style-filtering.component.scss
  src/app/grid/grid-external-excel-style-filtering/grid-external-excel-style-filtering.component.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
  src/app/hierarchical-grid/hierarchical-grid-external-advanced-filtering/hierarchical-grid-external-advanced-filtering.component.html
  src/app/hierarchical-grid/hierarchical-grid-external-advanced-filtering/hierarchical-grid-external-advanced-filtering.component.scss
  src/app/hierarchical-grid/hierarchical-grid-external-advanced-filtering/hierarchical-grid-external-advanced-filtering.component.ts
  src/app/hierarchical-grid/hierarchical-grid-external-excel-style-filtering/hierarchical-grid-external-excel-style-filtering.component.html
  src/app/hierarchical-grid/hierarchical-grid-external-excel-style-filtering/hierarchical-grid-external-excel-style-filtering.component.scss
  src/app/hierarchical-grid/hierarchical-grid-external-excel-style-filtering/hierarchical-grid-external-excel-style-filtering.component.ts
  src/app/hierarchical-grid/hierarchical-grid-routes-data.ts
  src/app/hierarchical-grid/hierarchical-grid-routing.module.ts
  src/app/hierarchical-grid/hierarchical-grid.module.ts
  src/app/tree-grid/tree-grid-external-advanced-filtering/tree-grid-external-advanced-filtering.component.html
  src/app/tree-grid/tree-grid-external-advanced-filtering/tree-grid-external-advanced-filtering.component.scss
  src/app/tree-grid/tree-grid-external-advanced-filtering/tree-grid-external-advanced-filtering.component.ts
  src/app/tree-grid/tree-grid-external-excel-style-filtering/tree-grid-external-excel-style-filtering.component.html
  src/app/tree-grid/tree-grid-external-excel-style-filtering/tree-grid-external-excel-style-filtering.component.scss
  src/app/tree-grid/tree-grid-external-excel-style-filtering/tree-grid-external-excel-style-filtering.component.ts
  src/app/tree-grid/tree-grid-routes-data.ts
  src/app/tree-grid/tree-grid-routing.module.ts
  src/app/tree-grid/tree-grid.module.ts
Labels: grid, status: verified

#1594 fix(sample): Adding debounce when handling onDataPreLoad subscription…
  src/app/grid/grid-sample-4/grid-sample-4.component.html
  src/app/grid/grid-sample-4/grid-sample-4.component.ts
  src/app/grid/services/remoteService.ts
Labels: status: verified

#1593 fix(sample): Adding debounce when handling onDataPreLoad subscription…
  src/app/grid/grid-sample-4/grid-sample-4.component.html
  src/app/grid/grid-sample-4/grid-sample-4.component.ts
  src/app/grid/services/remoteService.ts
Labels: status: verified

#1597 Fixing #1580 - [Combo] Combo in grid editing sample is not properly bound
  src/app/grid/grid-editing-sample/grid-editing-sample.component.html
Labels: combo, status: verified

#1600 Fix(sample)#1580-Changing [valueKey] to [displayKey] for the combo editor.
  src/app/grid/grid-editing-sample/grid-editing-sample.component.html
Labels: combo, status: verified

#1585 Mkirkova/custom row drag demo v next
  live-editing/configs/GridConfigGenerator.ts
  live-editing/configs/HierarchicalGridConfigGenerator.ts
  live-editing/configs/TreeGridConfigGenerator.ts
  src/app/grid/grid-multiple-row-drag/grid-multiple-row-drag.component.html
  src/app/grid/grid-multiple-row-drag/grid-multiple-row-drag.component.scss
  src/app/grid/grid-multiple-row-drag/grid-multiple-row-drag.component.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
  src/app/hierarchical-grid/hierarchical-grid-multi-row-drag/hierarchical-grid-multi-row-drag.component.html
  src/app/hierarchical-grid/hierarchical-grid-multi-row-drag/hierarchical-grid-multi-row-drag.component.scss
  src/app/hierarchical-grid/hierarchical-grid-multi-row-drag/hierarchical-grid-multi-row-drag.component.ts
  src/app/hierarchical-grid/hierarchical-grid-routes-data.ts
  src/app/hierarchical-grid/hierarchical-grid-routing.module.ts
  src/app/hierarchical-grid/hierarchical-grid.module.ts
  src/app/tree-grid/tree-grid-multi-row-drag/tree-grid-multi-row-drag.component.html
  src/app/tree-grid/tree-grid-multi-row-drag/tree-grid-multi-row-drag.component.scss
  src/app/tree-grid/tree-grid-multi-row-drag/tree-grid-multi-row-drag.component.ts
  src/app/tree-grid/tree-grid-routes-data.ts
  src/app/tree-grid/tree-grid-routing.module.ts
  src/app/tree-grid/tree-grid.module.ts
Labels: grid, row-drag, status: verified, version: 9.0.x

#1591 Mkirkova/custom row drag demo
  live-editing/configs/GridConfigGenerator.ts
  live-editing/configs/HierarchicalGridConfigGenerator.ts
  live-editing/configs/TreeGridConfigGenerator.ts
  src/app/grid/grid-multiple-row-drag/grid-multiple-row-drag.component.html
  src/app/grid/grid-multiple-row-drag/grid-multiple-row-drag.component.scss
  src/app/grid/grid-multiple-row-drag/grid-multiple-row-drag.component.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
  src/app/hierarchical-grid/hierarchical-grid-multi-row-drag/hierarchical-grid-multi-row-drag.component.html
  src/app/hierarchical-grid/hierarchical-grid-multi-row-drag/hierarchical-grid-multi-row-drag.component.scss
  src/app/hierarchical-grid/hierarchical-grid-multi-row-drag/hierarchical-grid-multi-row-drag.component.ts
  src/app/hierarchical-grid/hierarchical-grid-routes-data.ts
  src/app/hierarchical-grid/hierarchical-grid-routing.module.ts
  src/app/hierarchical-grid/hierarchical-grid.module.ts
  src/app/tree-grid/tree-grid-multi-row-drag/tree-grid-multi-row-drag.component.html
  src/app/tree-grid/tree-grid-multi-row-drag/tree-grid-multi-row-drag.component.scss
  src/app/tree-grid/tree-grid-multi-row-drag/tree-grid-multi-row-drag.component.ts
  src/app/tree-grid/tree-grid-routes-data.ts
  src/app/tree-grid/tree-grid-routing.module.ts
  src/app/tree-grid/tree-grid.module.ts
Labels: grid, row-drag, status: in-test, version: 8.2.x

#1603 chore(*): update to igniteui-angular@9.0.0-beta.3
  package-lock.json
  package.json
Labels: status: verified

#1586 Enhancement of the carousel samples
  live-editing/configs/CarouselConfigGenerator.ts
  src/app/layouts/carousel/carousel-animations-sample/carousel-animations-sample.component.html
  src/app/layouts/carousel/carousel-animations-sample/carousel-animations-sample.component.scss
  src/app/layouts/carousel/carousel-animations-sample/carousel-animations-sample.component.ts
  src/app/layouts/carousel/carousel-base-sample/carousel-base-sample.component.html
  src/app/layouts/carousel/carousel-base-sample/carousel-base-sample.component.scss
  src/app/layouts/carousel/carousel-base-sample/carousel-base-sample.component.ts
  src/app/layouts/carousel/carousel-details/carousel-details.component.html
  src/app/layouts/carousel/carousel-details/carousel-details.component.scss
  src/app/layouts/carousel/carousel-details/carousel-details.component.ts
  src/app/layouts/carousel/carousel-no-navigation-sample/carousel-no-navigation-sample.component.html
  src/app/layouts/carousel/carousel-no-navigation-sample/carousel-no-navigation-sample.component.scss
  src/app/layouts/carousel/carousel-no-navigation-sample/carousel-no-navigation-sample.component.ts
  src/app/layouts/carousel/carousel-sample-1/carousel-sample-1.component.html
  src/app/layouts/carousel/carousel-sample-1/carousel-sample-1.component.scss
  src/app/layouts/carousel/carousel-sample-1/carousel-sample-1.component.ts
  src/app/layouts/carousel/carousel-sample-2/carousel-sample-2.component.html
  src/app/layouts/carousel/carousel-sample-2/carousel-sample-2.component.scss
  src/app/layouts/carousel/carousel-sample-3/carousel-sample-3.component.html
  src/app/layouts/carousel/carousel-sample-3/carousel-sample-3.component.scss
  src/app/layouts/carousel/carousel-sample-3/carousel-sample-3.component.ts
  src/app/layouts/carousel/carousel-sample-4/carousel-sample-4.component.html
  src/app/layouts/carousel/carousel-sample-4/carousel-sample-4.component.scss
  src/app/layouts/carousel/carousel-sample-4/carousel-sample-4.component.ts
  src/app/layouts/layouts-routes-data.ts
  src/app/layouts/layouts-routing.module.ts
  src/app/layouts/layouts.module.ts
  src/assets/images/carousel/AmazingBridge.png
  src/assets/images/carousel/AmazingBridgeThumb.png
  src/assets/images/carousel/CulturalDip.png
  src/assets/images/carousel/CulturalDipThumb.png
  src/assets/images/carousel/GoldenBeaches.png
  src/assets/images/carousel/GoldenBeachesThumb.png
  src/assets/images/carousel/IslandOfHistory.png
  src/assets/images/carousel/IslandOfHistoryThumb.png
  src/assets/images/carousel/WonderfulCoast.png
  src/assets/images/carousel/WonderfulCoastThumb.png
  src/assets/images/svg/carousel/Onboarding1.svg
  src/assets/images/svg/carousel/Onboarding2.svg
  src/assets/images/svg/carousel/Onboarding3.svg
  src/assets/images/svg/carousel/Route.svg
  src/assets/images/svg/carousel/SignUp.svg
Labels: status: verified

#1604 Fix Cell Selection sample stakcblitz config (vNext)
  live-editing/configs/GridConfigGenerator.ts
Labels: StackBlitz, status: verified

#1605 Fix Cell Selection sample stakcblitz config (master)
  live-editing/configs/GridConfigGenerator.ts
Labels: StackBlitz, status: verified

#1610 fix(tree-grid, hierarchical-grid): deselected row
  src/app/hierarchical-grid/hierarchical-grid-multi-row-drag/hierarchical-grid-multi-row-drag.component.ts
  src/app/tree-grid/tree-grid-multi-row-drag/tree-grid-multi-row-drag.component.ts
Labels: hierarchical-grid, status: verified, tree-grid, version: 9.0.x

#1614 Data analysis sample with perf impr
  package-lock.json
  src/app/grid-finjs/grid-finjs-demo.component.ts
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.html
  src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
Labels: status: verified

#1611 fix(tree-grid, hierarchical-grid): deselected row
  src/app/hierarchical-grid/hierarchical-grid-multi-row-drag/hierarchical-grid-multi-row-drag.component.ts
  src/app/tree-grid/tree-grid-multi-row-drag/tree-grid-multi-row-drag.component.ts
Labels: hierarchical-grid, status: verified, tree-grid, version: 8.2.x

#1615 Data analysis sample with perf impr
  package-lock.json
  src/app/grid-finjs/grid-finjs-demo.component.ts
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.html
  src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
Labels: status: verified

#1617 fix(hgrid): row drag stackblitz samples
  live-editing/configs/HierarchicalGridConfigGenerator.ts
Labels: StackBlitz, hierarchical-grid, row-drag, status: verified

#1618 fix(hgrid): row drag stackblitz samples
  live-editing/configs/HierarchicalGridConfigGenerator.ts
Labels: StackBlitz, hierarchical-grid, row-drag, status: verified
