Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2019-04, with the labels that each got.

#1075 Add samples for igxFilterCellTemplate
  live-editing/configs/GridConfigGenerator.ts
  live-editing/configs/HierarchicalGridConfigGenerator.ts
  live-editing/configs/TreeGridConfigGenerator.ts
  src/app/grid/grid-filtering-template-sample/grid-filtering-template-sample.component.html
  src/app/grid/grid-filtering-template-sample/grid-filtering-template-sample.component.scss
  src/app/grid/grid-filtering-template-sample/grid-filtering-template-sample.component.ts
  src/app/grid/grid-filtering-template-sample/nwindData.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
  src/app/hierarchical-grid/hierarchical-grid-filtering-template/data.ts
  src/app/hierarchical-grid/hierarchical-grid-filtering-template/hierarchical-grid-filtering-template.component.html
  src/app/hierarchical-grid/hierarchical-grid-filtering-template/hierarchical-grid-filtering-template.component.scss
  src/app/hierarchical-grid/hierarchical-grid-filtering-template/hierarchical-grid-filtering-template.component.ts
  src/app/hierarchical-grid/hierarchical-grid-routes-data.ts
  src/app/hierarchical-grid/hierarchical-grid-routing.module.ts
  src/app/hierarchical-grid/hierarchical-grid.module.ts
  src/app/tree-grid/tree-grid-filtering-template-sample/tree-grid-filtering-template-sample.component.html
  src/app/tree-grid/tree-grid-filtering-template-sample/tree-grid-filtering-template-sample.component.scss
  src/app/tree-grid/tree-grid-filtering-template-sample/tree-grid-filtering-template-sample.component.ts
  src/app/tree-grid/tree-grid-routes-data.ts
  src/app/tree-grid/tree-grid-routing.module.ts
  src/app/tree-grid/tree-grid.module.ts
Labels: grid, status: verified

#1082 Fix Column Moving sample pinning in Chorme
  src/app/grid/grid-moving-sample/grid-moving-sample.component.html
Labels: status: verified

#598 Change the theme applied to samples
  src/app/grid-finjs/grid-finjs-demo.component.html
  src/app/grid-finjs/grid-finjs-demo.component.scss
  src/app/grid-finjs/grid-finjs-demo.component.ts
  src/app/grid/grid-boston-marathon/grid.component.scss
  src/app/grid/grid-editing-sample/grid-editing-sample.component.scss
  src/app/index/docs-layout.component.scss
  src/app/index/docs-layout.component.ts
  src/app/theming/dark-theme-sample/dark-theme-sample.component.scss
  src/app/theming/styles/theme-classes.scss
  src/app/theming/theme-chooser/theme-chooser-sample.component.scss
  src/app/treegrid-finjs/tree-grid-finjs-sample.component.html
  src/app/treegrid-finjs/tree-grid-finjs-sample.component.scss
  src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
  src/styles.scss
  src/themes.scss
Labels: status: in-test

#1083 Changing column's dataType to 'number' in the two igxHierarchicalGrid Hiding samples
  src/app/hierarchical-grid/hierarchical-grid-column-hiding/hierarchical-grid-custom-hiding.component.html
  src/app/hierarchical-grid/hierarchical-grid-column-hiding/hierarchical-grid-hiding.component.html
Labels: hierarchical-grid, status: verified

#1085 Updating to verion 7.2.4
  package-lock.json
  package.json
Labels: status: verified

#1089 Add multi cell selection sample
  live-editing/configs/GridConfigGenerator.ts
  src/app/grid/grid-multi-cell-selection/grid-multi-cell-selection.component.html
  src/app/grid/grid-multi-cell-selection/grid-multi-cell-selection.component.scss
  src/app/grid/grid-multi-cell-selection/grid-multi-cell-selection.component.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
Labels: status: verified

#1084 Mtp igniteui angular samples spreadsheet
  live-editing/configs/SpreadsheetConfigGenerator.ts
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/index/index.component.ts
  src/app/spreadsheet/spreadsheet-activation/spreadsheet-activation.component.html
  src/app/spreadsheet/spreadsheet-activation/spreadsheet-activation.component.scss
  src/app/spreadsheet/spreadsheet-activation/spreadsheet-activation.component.spec.ts
  src/app/spreadsheet/spreadsheet-activation/spreadsheet-activation.component.ts
  src/app/spreadsheet/spreadsheet-clipboard/spreadsheet-clipboard.component.html
  src/app/spreadsheet/spreadsheet-clipboard/spreadsheet-clipboard.component.scss
  src/app/spreadsheet/spreadsheet-clipboard/spreadsheet-clipboard.component.spec.ts
  src/app/spreadsheet/spreadsheet-clipboard/spreadsheet-clipboard.component.ts
  src/app/spreadsheet/spreadsheet-commands/spreadsheet-commands.component.html
  src/app/spreadsheet/spreadsheet-commands/spreadsheet-commands.component.scss
  src/app/spreadsheet/spreadsheet-commands/spreadsheet-commands.component.spec.ts
  src/app/spreadsheet/spreadsheet-commands/spreadsheet-commands.component.ts
  src/app/spreadsheet/spreadsheet-cond-formatting/spreadsheet-cond-formatting.component.html
  src/app/spreadsheet/spreadsheet-cond-formatting/spreadsheet-cond-formatting.component.scss
  src/app/spreadsheet/spreadsheet-cond-formatting/spreadsheet-cond-formatting.component.spec.ts
  src/app/spreadsheet/spreadsheet-cond-formatting/spreadsheet-cond-formatting.component.ts
  src/app/spreadsheet/spreadsheet-data-validation/spreadsheet-data-validation.component.html
  src/app/spreadsheet/spreadsheet-data-validation/spreadsheet-data-validation.component.scss
  src/app/spreadsheet/spreadsheet-data-validation/spreadsheet-data-validation.component.spec.ts
  src/app/spreadsheet/spreadsheet-data-validation/spreadsheet-data-validation.component.ts
  src/app/spreadsheet/spreadsheet-filter-dialog/spreadsheet-filter-dialog.component.html
  src/app/spreadsheet/spreadsheet-filter-dialog/spreadsheet-filter-dialog.component.scss
  src/app/spreadsheet/spreadsheet-filter-dialog/spreadsheet-filter-dialog.component.spec.ts
  src/app/spreadsheet/spreadsheet-filter-dialog/spreadsheet-filter-dialog.component.ts
  src/app/spreadsheet/spreadsheet-format-dialog/spreadsheet-format-dialog.component.html
  src/app/spreadsheet/spreadsheet-format-dialog/spreadsheet-format-dialog.component.scss
  src/app/spreadsheet/spreadsheet-format-dialog/spreadsheet-format-dialog.component.spec.ts
  src/app/spreadsheet/spreadsheet-format-dialog/spreadsheet-format-dialog.component.ts
  src/app/spreadsheet/spreadsheet-hyperlinks/spreadsheet-hyperlinks.component.html
  src/app/spreadsheet/spreadsheet-hyperlinks/spreadsheet-hyperlinks.component.scss
  src/app/spreadsheet/spreadsheet-hyperlinks/spreadsheet-hyperlinks.component.spec.ts
  src/app/spreadsheet/spreadsheet-hyperlinks/spreadsheet-hyperlinks.component.ts
  src/app/spreadsheet/spreadsheet-overview/spreadsheet-overview.component.html
  src/app/spreadsheet/spreadsheet-overview/spreadsheet-overview.component.scss
  src/app/spreadsheet/spreadsheet-overview/spreadsheet-overview.component.spec.ts
  src/app/spreadsheet/spreadsheet-overview/spreadsheet-overview.component.ts
  src/app/spreadsheet/spreadsheet-routes-data.ts
  src/app/spreadsheet/spreadsheet-routing.module.ts
  src/app/spreadsheet/spreadsheet-sort-dialog/spreadsheet-sort-dialog.component.html
  src/app/spreadsheet/spreadsheet-sort-dialog/spreadsheet-sort-dialog.component.scss
  src/app/spreadsheet/spreadsheet-sort-dialog/spreadsheet-sort-dialog.component.spec.ts
  src/app/spreadsheet/spreadsheet-sort-dialog/spreadsheet-sort-dialog.component.ts
  src/app/spreadsheet/spreadsheet-worksheets/spreadsheet-worksheets.component.html
  src/app/spreadsheet/spreadsheet-worksheets/spreadsheet-worksheets.component.scss
  src/app/spreadsheet/spreadsheet-worksheets/spreadsheet-worksheets.component.spec.ts
  src/app/spreadsheet/spreadsheet-worksheets/spreadsheet-worksheets.component.ts
  src/app/spreadsheet/spreadsheet.module.ts
Labels: status: verified

#1090 Adding [minWidth] to the Photo column in the Hierarchical Grid Resizing sample
  src/app/hierarchical-grid/hierarchical-grid-column-resizing/hierarchical-grid-resizing.component.html
Labels: status: verified

#1096 Add a fix to make the pin icons clickable in the latest Chrome
  src/app/hierarchical-grid/hierarchical-grid-column-moving/hierarchical-grid-moving.component.html
Labels: status: verified

#1100 Fixing the HGrid Editing and Pinning samples
  src/app/hierarchical-grid/hierarchical-grid-column-pinning/hierarchical-grid-pinning.component.html
  src/app/hierarchical-grid/hierarchical-grid-editing/hierarchical-grid-editing.component.html
Labels: hierarchical-grid, pinning, status: verified

#1101 Changing theme apllication and removal approach, because of IE 11 and Edge
  src/app/index/docs-layout.component.ts
Labels: status: verified

#1094 Check-in for conditional formatting, configuring, and activation sample.
  live-editing/configs/SpreadsheetConfigGenerator.ts
  src/app/spreadsheet/spreadsheet-activation/spreadsheet-activation.component.html
  src/app/spreadsheet/spreadsheet-activation/spreadsheet-activation.component.scss
  src/app/spreadsheet/spreadsheet-activation/spreadsheet-activation.component.spec.ts
  src/app/spreadsheet/spreadsheet-activation/spreadsheet-activation.component.ts
  src/app/spreadsheet/spreadsheet-cond-formatting/spreadsheet-cond-formatting.component.html
  src/app/spreadsheet/spreadsheet-cond-formatting/spreadsheet-cond-formatting.component.scss
  src/app/spreadsheet/spreadsheet-cond-formatting/spreadsheet-cond-formatting.component.spec.ts
  src/app/spreadsheet/spreadsheet-cond-formatting/spreadsheet-cond-formatting.component.ts
  src/app/spreadsheet/spreadsheet-configuring/spreadsheet-configuring.component.html
  src/app/spreadsheet/spreadsheet-configuring/spreadsheet-configuring.component.scss
  src/app/spreadsheet/spreadsheet-configuring/spreadsheet-configuring.component.ts
  src/app/spreadsheet/spreadsheet-hyperlinks/spreadsheet-hyperlinks.component.html
  src/app/spreadsheet/spreadsheet-hyperlinks/spreadsheet-hyperlinks.component.scss
  src/app/spreadsheet/spreadsheet-hyperlinks/spreadsheet-hyperlinks.component.spec.ts
  src/app/spreadsheet/spreadsheet-hyperlinks/spreadsheet-hyperlinks.component.ts
  src/app/spreadsheet/spreadsheet-routes-data.ts
  src/app/spreadsheet/spreadsheet-routing.module.ts
  src/app/spreadsheet/spreadsheet.module.ts
  src/app/utilities/excel-utility.ts
  src/assets/ConditionalFormatData.xlsx
  src/assets/HyperlinkWorkbook.xlsx
  src/assets/WeeklySalesReport.xlsx
Labels: status: verified

#975 xsharp - fixed missing modules in DC stackblitz
  live-editing/configs/DataChartConfigGenerator.ts
  live-editing/configs/FinancialChartConfigGenerator.ts
  live-editing/generators/SampleAssetsGenerator.ts
  package.json
  src/app/charts/charts-routes-data.ts
  src/app/charts/charts-routing.module.ts
  src/app/charts/data-chart/data-chart-overview/data-chart-overview.component.html
  src/app/charts/data-chart/data-chart-samples-module.ts
  src/app/charts/financial-chart/annotations/financial-chart-annotations.component.html
  src/app/charts/financial-chart/annotations/financial-chart-annotations.component.scss
  src/app/charts/financial-chart/annotations/financial-chart-annotations.component.ts
  src/app/charts/financial-chart/overview/financial-chart-overview-sample.component.html
  src/app/charts/financial-chart/overview/financial-chart-overview-sample.component.ts
  src/app/charts/financial-chart/services/financial-data.service.ts
  src/app/charts/financial-chart/time-based-data/financial-chart-time-based-data.component.html
  src/app/charts/financial-chart/time-based-data/financial-chart-time-based-data.component.scss
  src/app/charts/financial-chart/time-based-data/financial-chart-time-based-data.component.ts
Labels: status: awaiting-test

#1095 docs(date-picker): Added a sample for drop-down mode re-templating
  live-editing/configs/DatePickerConfigGenerator.ts
  src/app/scheduling/datepicker/datepicker-sample-7/datepicker-sample-7.component.html
  src/app/scheduling/datepicker/datepicker-sample-7/datepicker-sample-7.component.scss
  src/app/scheduling/datepicker/datepicker-sample-7/datepicker-sample-7.component.ts
  src/app/scheduling/scheduling-routes-data.ts
  src/app/scheduling/scheduling-routing.module.ts
  src/app/scheduling/scheduling.module.ts
Labels: date picker, status: verified, version: 7.2.x

#1104 Replacing all the images for HGrid samples with new ones
  src/app/hierarchical-grid/data.ts
  src/app/hierarchical-grid/hierarchical-grid-row-editing/data.ts
  src/assets/images/hgrid/ahmad.jpg
  src/assets/images/hgrid/ahmad.png
  src/assets/images/hgrid/alicia.jpg
  src/assets/images/hgrid/alicia.png
  src/assets/images/hgrid/athar.jpg
  src/assets/images/hgrid/athar.png
  src/assets/images/hgrid/babila.jpg
  src/assets/images/hgrid/babila.png
  src/assets/images/hgrid/eva.jpg
  src/assets/images/hgrid/eva.png
  src/assets/images/hgrid/izabella.jpg
  src/assets/images/hgrid/izabella.png
  src/assets/images/hgrid/kimmy.jpg
  src/assets/images/hgrid/kimmy.png
  src/assets/images/hgrid/mar.jpg
  src/assets/images/hgrid/mar.png
  src/assets/images/hgrid/marti.jpg
  src/assets/images/hgrid/marti.png
  src/assets/images/hgrid/naomi.jpg
  src/assets/images/hgrid/naomi.png
  src/assets/images/hgrid/nguyen.jpg
  src/assets/images/hgrid/nguyen.png
  src/assets/images/hgrid/pablo.jpg
  src/assets/images/hgrid/pablo.png
  src/assets/images/hgrid/peter.jpg
  src/assets/images/hgrid/peter.png
  src/assets/images/hgrid/siri.jpg
  src/assets/images/hgrid/siri.png
Labels: enhancement, hierarchical-grid, status: verified, version: 7.2.x

#1108 Attaching datePicker to HGrid in the Filtering Template sample
  src/app/hierarchical-grid/hierarchical-grid-filtering-template/hierarchical-grid-filtering-template.component.html
  src/app/hierarchical-grid/hierarchical-grid-filtering-template/hierarchical-grid-filtering-template.component.ts
Labels: date picker, hierarchical-grid, status: verified

#1120 updated to 7.2.1 and fixed API breaking change
  package-lock.json
  package.json
  src/app/spreadsheet/spreadsheet-clipboard/spreadsheet-clipboard.component.ts
  src/app/spreadsheet/spreadsheet-commands/spreadsheet-commands.component.ts
Labels: status: in-review

#1121 Update project to 7.2.5
  package-lock.json
  package.json
Labels: status: verified

#1113 Adding samples for divider component
  live-editing/configs/DividerConfigGenerator.ts
  live-editing/generators/ConfigGenerators.ts
  src/app/layouts/divider/dashed/divider-dashed.component.html
  src/app/layouts/divider/dashed/divider-dashed.component.scss
  src/app/layouts/divider/dashed/divider-dashed.component.ts
  src/app/layouts/divider/default/divider-default.component.html
  src/app/layouts/divider/default/divider-default.component.scss
  src/app/layouts/divider/default/divider-default.component.ts
  src/app/layouts/divider/inset/divider-inset.component.html
  src/app/layouts/divider/inset/divider-inset.component.scss
  src/app/layouts/divider/inset/divider-inset.component.ts
  src/app/layouts/divider/vertical/divider-vertical.component.html
  src/app/layouts/divider/vertical/divider-vertical.component.scss
  src/app/layouts/divider/vertical/divider-vertical.component.ts
  src/app/layouts/layouts-routes-data.ts
  src/app/layouts/layouts-routing.module.ts
  src/app/layouts/layouts.module.ts
Labels: divider, status: verified

#1107 refactor(cards): update card samples to showcase refactored cards
  live-editing/configs/CardConfigGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/interactions/interactions.module.ts
  src/app/layouts/card/card-sample-1/card-sample-1.component.html
  src/app/layouts/card/card-sample-1/card-sample-1.component.scss
  src/app/layouts/card/card-sample-1/card-sample-1.component.ts
  src/app/layouts/card/card-sample-1/card-sample-1.module.ts
  src/app/layouts/card/card-sample-2/card-sample-2.component.html
  src/app/layouts/card/card-sample-2/card-sample-2.component.scss
  src/app/layouts/card/card-sample-2/card-sample-2.component.ts
  src/app/layouts/card/card-sample-3/card-sample-3.component.html
  src/app/layouts/card/card-sample-3/card-sample-3.component.scss
  src/app/layouts/card/card-sample-3/card-sample-3.component.ts
  src/app/layouts/card/card-sample-4/card-sample-4.component.html
  src/app/layouts/card/card-sample-4/card-sample-4.component.scss
  src/app/layouts/card/card-sample-4/card-sample-4.component.ts
  src/app/layouts/card/card.blueprint.ts
  src/app/layouts/card/card.component.html
  src/app/layouts/card/card.component.scss
  src/app/layouts/card/card.component.ts
  src/app/layouts/layouts-routes-data.ts
  src/app/layouts/layouts-routing.module.ts
  src/app/layouts/layouts.module.ts
  src/assets/images/card/icons/breeze.svg
  src/assets/images/card/icons/rain.svg
  src/assets/images/card/media/ROZES-Under-the-Grave.jpg
  src/assets/images/card/media/cafe.jpg
  src/assets/images/card/media/weather.png
Labels: card, status: verified

#1114 Fix pinning in tree grid column moving sample
  src/app/tree-grid/tree-grid-column-moving-sample/tree-grid-column-moving-sample.component.html
Labels: column moving, status: verified, tree-grid

#1109 Setting each column width separately in the Custom Hiding HGrid sample
  src/app/hierarchical-grid/hierarchical-grid-column-hiding/hierarchical-grid-custom-hiding.component.html
  src/app/hierarchical-grid/hierarchical-grid-column-hiding/hierarchical-grid-custom-hiding.component.ts
Labels: column-hiding, hierarchical-grid, status: verified

#1071 Update custom overlay settings
  src/app/data-entries/select/select-sample-4/select-sample-4.component.ts
Labels: enhancement, select

#1126 Change cell's EditValue invocation in Grid Editing samples
  src/app/grid/grid-batch-editing/grid-batch-editing-sample.component.html
  src/app/grid/grid-editing-sample/grid-editing-sample.component.html
Labels: status: verified

#1132 Update angular cli, code, rxjs and product
  package-lock.json
  package.json
Labels: status: verified
