Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2019-01, with the labels that each got.

#831 Fixing the igxRippleTarget
  src/app/snackbar/snackbar-sample-4/snackbar-sample-4.component.html
Labels: list, status: verified

#857 Notifications bundle
  live-editing/configs/BannerConfigGenerator.ts
  live-editing/configs/SnackbarConfigGenerator.ts
  live-editing/configs/ToastConfigGenerator.ts
  live-editing/generators/SampleAssetsGenerator.ts
  package-lock.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/index/index.component.ts
  src/app/notifications/banner/banner-sample-1/banner-sample-1.component.html
  src/app/notifications/banner/banner-sample-1/banner-sample-1.component.scss
  src/app/notifications/banner/banner-sample-1/banner-sample-1.component.ts
  src/app/notifications/banner/banner-sample-2/banner-sample-2.component.html
  src/app/notifications/banner/banner-sample-2/banner-sample-2.component.scss
  src/app/notifications/banner/banner-sample-2/banner-sample-2.component.ts
  src/app/notifications/banner/banner-sample-3/banner-sample-3.component.html
  src/app/notifications/banner/banner-sample-3/banner-sample-3.component.scss
  src/app/notifications/banner/banner-sample-3/banner-sample-3.component.ts
  src/app/notifications/banner/banner-sample-4/banner-sample-4.component.html
  src/app/notifications/banner/banner-sample-4/banner-sample-4.component.scss
  src/app/notifications/banner/banner-sample-4/banner-sample-4.component.ts
  src/app/notifications/notifications-routing.module.ts
  src/app/notifications/notifications.module.ts
  src/app/notifications/snackbar/snackbar-sample-1/snackbar-sample-1.component.html
  src/app/notifications/snackbar/snackbar-sample-1/snackbar-sample-1.component.scss
  src/app/notifications/snackbar/snackbar-sample-1/snackbar-sample-1.component.ts
  src/app/notifications/snackbar/snackbar-sample-2/snackbar-sample-2.component.html
  src/app/notifications/snackbar/snackbar-sample-2/snackbar-sample-2.component.scss
  src/app/notifications/snackbar/snackbar-sample-2/snackbar-sample-2.component.ts
  src/app/notifications/snackbar/snackbar-sample-3/snackbar-sample-3.component.html
  src/app/notifications/snackbar/snackbar-sample-3/snackbar-sample-3.component.scss
  src/app/notifications/snackbar/snackbar-sample-3/snackbar-sample-3.component.ts
  src/app/notifications/snackbar/snackbar-sample-4/snackbar-sample-4.component.html
  src/app/notifications/snackbar/snackbar-sample-4/snackbar-sample-4.component.scss
  src/app/notifications/snackbar/snackbar-sample-4/snackbar-sample-4.component.ts
  src/app/notifications/toast/toast-sample-1/toast-sample-1.component.html
  src/app/notifications/toast/toast-sample-1/toast-sample-1.component.scss
  src/app/notifications/toast/toast-sample-1/toast-sample-1.component.ts
  src/app/notifications/toast/toast-sample-2/toast-sample-2.component.html
  src/app/notifications/toast/toast-sample-2/toast-sample-2.component.scss
  src/app/notifications/toast/toast-sample-2/toast-sample-2.component.ts
  src/app/notifications/toast/toast-sample-3/toast-sample-3.component.html
  src/app/notifications/toast/toast-sample-3/toast-sample-3.component.scss
  src/app/notifications/toast/toast-sample-3/toast-sample-3.component.ts
  src/app/notifications/toast/toast-sample-4/toast-sample-4.component.html
  src/app/notifications/toast/toast-sample-4/toast-sample-4.component.scss
  src/app/notifications/toast/toast-sample-4/toast-sample-4.component.ts
  src/app/notifications/toast/toast-sample-5/toast-sample-5.component.html
  src/app/notifications/toast/toast-sample-5/toast-sample-5.component.scss
  src/app/notifications/toast/toast-sample-5/toast-sample-5.component.ts
Labels: status: verified

#778 Fixing StackBlitz config for the Drag and Drop sample
  live-editing/configs/DragAndDropConfigGenerator.ts
Labels: status: verified

#861 Introduced gauges bundle
  live-editing/configs/GaugesConfigGenerator.ts
  live-editing/generators/SampleAssetsGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/gauges/gauges-routing.module.ts
  src/app/gauges/gauges.module.ts
  src/app/index/index.component.ts
Labels: status: verified

#867 added lists bundle
  live-editing/configs/ComboConfigGenerator.ts
  live-editing/configs/ListConfigGenerator.ts
  live-editing/generators/SampleAssetsGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/index/index.component.ts
  src/app/lists/combo/cascading-combos/cascading-combos.component.html
  src/app/lists/combo/cascading-combos/cascading-combos.component.scss
  src/app/lists/combo/cascading-combos/cascading-combos.component.ts
  src/app/lists/combo/cascading-combos/local-data.ts
  src/app/lists/combo/combo-features/combo-features.component.html
  src/app/lists/combo/combo-features/combo-features.component.scss
  src/app/lists/combo/combo-features/combo-features.component.ts
  src/app/lists/combo/combo-features/local-data.ts
  src/app/lists/combo/combo-main/combo-main.component.html
  src/app/lists/combo/combo-main/combo-main.component.scss
  src/app/lists/combo/combo-main/combo-main.component.ts
  src/app/lists/combo/combo-main/local-data.ts
  src/app/lists/combo/combo-remote/combo-remote.component.html
  src/app/lists/combo/combo-remote/combo-remote.component.scss
  src/app/lists/combo/combo-remote/combo-remote.component.ts
  src/app/lists/combo/combo-template/combo-template.component.html
  src/app/lists/combo/combo-template/combo-template.component.scss
  src/app/lists/combo/combo-template/combo-template.component.ts
  src/app/lists/combo/combo-template/local-data.ts
  src/app/lists/list/list-chat-sample/list-chat-sample.component.html
  src/app/lists/list/list-chat-sample/list-chat-sample.component.scss
  src/app/lists/list/list-chat-sample/list-chat-sample.component.ts
  src/app/lists/list/list-chat-sample/services/contacts.service.ts
  src/app/lists/list/list-chat-sample/services/messages.service.ts
  src/app/lists/list/list-sample-1/list-sample-1.component.html
  src/app/lists/list/list-sample-1/list-sample-1.component.scss
  src/app/lists/list/list-sample-1/list-sample-1.component.ts
  src/app/lists/list/list-sample-2/list-sample-2.component.html
  src/app/lists/list/list-sample-2/list-sample-2.component.scss
  src/app/lists/list/list-sample-2/list-sample-2.component.ts
  src/app/lists/list/list-sample-3/list-sample-3.component.html
  src/app/lists/list/list-sample-3/list-sample-3.component.scss
  src/app/lists/list/list-sample-3/list-sample-3.component.ts
  src/app/lists/list/list-sample-4/list-sample-4.component.html
  src/app/lists/list/list-sample-4/list-sample-4.component.scss
  src/app/lists/list/list-sample-4/list-sample-4.component.ts
  src/app/lists/list/list-sample-5/list-sample-5.component.html
  src/app/lists/list/list-sample-5/list-sample-5.component.scss
  src/app/lists/list/list-sample-5/list-sample-5.component.ts
  src/app/lists/list/list-sample-6/list-sample-6.component.html
  src/app/lists/list/list-sample-6/list-sample-6.component.scss
  src/app/lists/list/list-sample-6/list-sample-6.component.ts
  src/app/lists/list/list-sample-7/list-sample-7.component.html
  src/app/lists/list/list-sample-7/list-sample-7.component.scss
  src/app/lists/list/list-sample-7/list-sample-7.component.ts
  src/app/lists/list/list.component.html
  src/app/lists/list/list.component.scss
  src/app/lists/list/list.component.spec.ts
  src/app/lists/list/list.component.ts
  src/app/lists/lists-routing.module.ts
  src/app/lists/lists.module.ts
Labels: status: verified

#865 added menu bundle
  live-editing/configs/NavDrawerConfigGenerator.ts
  live-editing/configs/NavbarConfigGenerator.ts
  live-editing/generators/SampleAssetsGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/index/index.component.ts
  src/app/menus/menus-routing.module.ts
  src/app/menus/menus.module.ts
  src/app/menus/navbar/navbar-sample-1/navbar-sample-1.component.html
  src/app/menus/navbar/navbar-sample-1/navbar-sample-1.component.scss
  src/app/menus/navbar/navbar-sample-1/navbar-sample-1.component.ts
  src/app/menus/navbar/navbar-sample-2/navbar-sample-2.component.html
  src/app/menus/navbar/navbar-sample-2/navbar-sample-2.component.scss
  src/app/menus/navbar/navbar-sample-2/navbar-sample-2.component.ts
  src/app/menus/navbar/navbar.component.html
  src/app/menus/navbar/navbar.component.scss
  src/app/menus/navbar/navbar.component.spec.ts
  src/app/menus/navbar/navbar.component.ts
  src/app/menus/navdrawer/nav-drawer-mini/nav-drawer-mini.component.html
  src/app/menus/navdrawer/nav-drawer-mini/nav-drawer-mini.component.scss
  src/app/menus/navdrawer/nav-drawer-mini/nav-drawer-mini.component.ts
  src/app/menus/navdrawer/nav-drawer-pin/nav-drawer-pin.component.html
  src/app/menus/navdrawer/nav-drawer-pin/nav-drawer-pin.component.scss
  src/app/menus/navdrawer/nav-drawer-pin/nav-drawer-pin.component.ts
  src/app/menus/navdrawer/nav-drawer-simple/nav-drawer-simple.component.html
  src/app/menus/navdrawer/nav-drawer-simple/nav-drawer-simple.component.scss
  src/app/menus/navdrawer/nav-drawer-simple/nav-drawer-simple.component.ts
  src/app/menus/navdrawer/navdrawer.component.html
  src/app/menus/navdrawer/navdrawer.component.scss
  src/app/menus/navdrawer/navdrawer.component.spec.ts
  src/app/menus/navdrawer/navdrawer.component.ts
Labels: status: verified

#866 Themes bundle
  live-editing/configs/DensityConfigGenerator.ts
  live-editing/configs/GridConfigGenerator.ts
  live-editing/configs/ShadowsConfigGenerator.ts
  live-editing/configs/ThemingConfigGenerator.ts
  live-editing/configs/TimePickerConfigGenerator.ts
  live-editing/generators/SampleAssetsGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/index/index.component.ts
  src/app/theming/display-density/display-density.component.html
  src/app/theming/display-density/display-density.component.scss
  src/app/theming/display-density/display-density.component.ts
  src/app/theming/shadows/shadows-sample-1/shadows-sample.component.html
  src/app/theming/shadows/shadows-sample-1/shadows-sample.component.scss
  src/app/theming/shadows/shadows-sample-1/shadows-sample.component.ts
  src/app/theming/shadows/shadows-sample-2/shadows-sample-2.component.html
  src/app/theming/shadows/shadows-sample-2/shadows-sample-2.component.scss
  src/app/theming/shadows/shadows-sample-2/shadows-sample-2.component.ts
  src/app/theming/theming-routing.module.ts
  src/app/theming/theming.module.ts
Labels: status: verified

#871 Adding simple colors to add product button in grid_eding and default-theme samples
  src/app/grid/grid-editing-sample/grid-editing-sample.component.scss
  src/app/theming/default-theme-sample/default-theme-sample.component.scss
Labels: status: verified

#862 Add custom content sample for IgxSnackbar
  live-editing/configs/SnackbarConfigGenerator.ts
  src/app/notifications/notifications-routing.module.ts
  src/app/notifications/notifications.module.ts
  src/app/notifications/snackbar/snackbar-sample-1/snackbar-sample-1.component.html
  src/app/notifications/snackbar/snackbar-sample-2/snackbar-sample-2.component.html
  src/app/notifications/snackbar/snackbar-sample-3/snackbar-sample-3.component.html
  src/app/notifications/snackbar/snackbar-sample-4/snackbar-sample-4.component.html
  src/app/notifications/snackbar/snackbar-sample-5/snackbar-sample-5.component.html
  src/app/notifications/snackbar/snackbar-sample-5/snackbar-sample-5.component.scss
  src/app/notifications/snackbar/snackbar-sample-5/snackbar-sample-5.component.ts
Labels: status: verified

#872 Updating angular to 7.2.0 and angular cli to 7.2.1
  package-lock.json
  package.json
  src/app/grid/grid-finjs-demo/grid-finjs-demo.component.ts
  src/app/tree-grid/tree-grid-finjs/tree-grid-finjs-sample.component.ts
  src/app/utilities/excel-exporter.ts
Labels: build, status: verified

#875 Services bundle
  live-editing/configs/ExportCsvConfigGenerator.ts
  live-editing/configs/ExportExcelConfigGenerator.ts
  live-editing/configs/LocalizationConfigGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/index/index.component.ts
  src/app/services/export-csv/csv-export-sample-1/csv-export-sample-1.component.html
  src/app/services/export-csv/csv-export-sample-1/csv-export-sample-1.component.scss
  src/app/services/export-csv/csv-export-sample-1/csv-export-sample-1.component.spec.ts
  src/app/services/export-csv/csv-export-sample-1/csv-export-sample-1.component.ts
  src/app/services/export-csv/csv-export.component.html
  src/app/services/export-csv/csv-export.component.scss
  src/app/services/export-csv/csv-export.component.spec.ts
  src/app/services/export-csv/csv-export.component.ts
  src/app/services/export-excel/excel-export-sample-1/excel-export-sample-1.component.html
  src/app/services/export-excel/excel-export-sample-1/excel-export-sample-1.component.scss
  src/app/services/export-excel/excel-export-sample-1/excel-export-sample-1.component.spec.ts
  src/app/services/export-excel/excel-export-sample-1/excel-export-sample-1.component.ts
  src/app/services/export-excel/excel-export.component.html
  src/app/services/export-excel/excel-export.component.scss
  src/app/services/export-excel/excel-export.component.spec.ts
  src/app/services/export-excel/excel-export.component.ts
  src/app/services/localization-samples/localization-sample-1/localization-sample-1.component.html
  src/app/services/localization-samples/localization-sample-1/localization-sample-1.component.scss
  src/app/services/localization-samples/localization-sample-1/localization-sample-1.component.ts
  src/app/services/localization-samples/localization-sample-1/nwindData.ts
  src/app/services/localization-samples/localization-sample-2/localization-sample-2.component.html
  src/app/services/localization-samples/localization-sample-2/localization-sample-2.component.scss
  src/app/services/localization-samples/localization-sample-2/localization-sample-2.component.ts
  src/app/services/localization-samples/localization-sample-2/nwindData.ts
  src/app/services/localization-samples/localization-sample-3/localization-sample-3.component.html
  src/app/services/localization-samples/localization-sample-3/localization-sample-3.component.scss
  src/app/services/localization-samples/localization-sample-3/localization-sample-3.component.ts
  src/app/services/localization-samples/localization-sample-3/nwindData.ts
  src/app/services/services-routing.module.ts
  src/app/services/services.module.ts
Labels: status: verified

#877 added treeGrid bundle
  live-editing/configs/TreeGridConfigGenerator.ts
  live-editing/generators/SampleAssetsGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/index/index.component.ts
  src/app/tree-grid/tree-grid-routing.module.ts
  src/app/tree-grid/tree-grid.module.ts
Labels: status: verified

#881 Add Igxgrid bundle
  live-editing/configs/GridCRMConfigGenerator.ts
  live-editing/configs/GridConfigGenerator.ts
  live-editing/generators/SampleAssetsGenerator.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/grid-crm/grid-crm-routing.module.ts
  src/app/grid-crm/grid-crm.module.ts
  src/app/grid-crm/grid-crm/data.ts
  src/app/grid-crm/grid-crm/grid-crm.component.html
  src/app/grid-crm/grid-crm/grid-crm.component.scss
  src/app/grid-crm/grid-crm/grid-crm.component.ts
  src/app/grid/grid-boston-marathon/grid.component.html
  src/app/grid/grid-boston-marathon/grid.component.scss
  src/app/grid/grid-boston-marathon/grid.component.spec.ts
  src/app/grid/grid-boston-marathon/grid.component.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
  src/app/index/index.component.ts
Labels: status: verified

#886 clearing out the app.module
  src/app/app.module.ts
Labels: status: verified

#894 Updating igniteui angular to 7.1.2
  package-lock.json
  package.json
Labels: build, status: verified

#885 Set width to searchBox
  src/app/index/index.component.scss
Labels: status: verified

#896 Fixing Drag and Drop directive sample
  src/app/interactions/drag-drop/drag-drop.component.ts
Labels: drag & drop, status: verified

#898 Fix inconsistent class name in input group sample
  src/app/data-entries/input-group/input-group-sample-6/input-group-sample-6.component.html
  src/app/data-entries/input-group/input-group-sample-6/input-group-sample-6.component.scss
Labels: input group, status: verified

#902 Adding the services routing to the sample routes
  live-editing/generators/SampleAssetsGenerator.ts
Labels: status: verified

#900 Sass.js version update
  package-lock.json
  package.json
Labels: status: verified

#907 Finalizing lazy loading
  src/app/app-routing.module.ts
  src/app/charts/charts-routes-data.ts
  src/app/charts/charts-routing.module.ts
  src/app/data-display/data-display-routes-data.ts
  src/app/data-display/data-display-routing.module.ts
  src/app/data-entries/data-entries-routes-data.ts
  src/app/data-entries/data-entries-routing.module.ts
  src/app/excel-library/excel-library-routes-data.ts
  src/app/excel-library/excel-library-routing.module.ts
  src/app/gauges/gauges-routes-data.ts
  src/app/gauges/gauges-routing.module.ts
  src/app/grid-crm/grid-crm-routes-data.ts
  src/app/grid-crm/grid-crm-routing.module.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/index/index.component.ts
  src/app/interactions/interactions-routes-data.ts
  src/app/interactions/interactions-routing.module.ts
  src/app/layouts/layouts-routes-data.ts
  src/app/layouts/layouts-routing.module.ts
  src/app/lists/lists-routes-data.ts
  src/app/lists/lists-routing.module.ts
  src/app/menus/menus-routes-data.ts
  src/app/menus/menus-routing.module.ts
  src/app/notifications/notifications-routes-data.ts
  src/app/notifications/notifications-routing.module.ts
  src/app/scheduling/scheduling-routes-data.ts
  src/app/scheduling/scheduling-routing.module.ts
  src/app/services/services-routes-data.ts
  src/app/services/services-routing.module.ts
  src/app/theming/theming-routes-data.ts
  src/app/theming/theming-routing.module.ts
  src/app/tree-grid/tree-grid-routes-data.ts
  src/app/tree-grid/tree-grid-routing.module.ts
Labels: status: verified

#913 Updating igniteui-angular to 7.1.3
  package-lock.json
  package.json
Labels: build

#911 Providing Indeterminate Circular Progress sample
  live-editing/configs/CircularProgressbarConfigGenerator.ts
  src/app/data-display/circular-progressbar/circular-indeterminate-progressbar/circular-indeterminate-progressbar.component.html
  src/app/data-display/circular-progressbar/circular-indeterminate-progressbar/circular-indeterminate-progressbar.component.scss
  src/app/data-display/circular-progressbar/circular-indeterminate-progressbar/circular-indeterminate-progressbar.component.ts
  src/app/data-display/data-display-routes-data.ts
  src/app/data-display/data-display-routing.module.ts
  src/app/data-display/data-display.module.ts
Labels: status: verified

#919 add bundles to lazyload for the finjs demos
  live-editing/configs/GridConfigGenerator.ts
  live-editing/configs/GridFinjsConfigGenerator.ts
  live-editing/configs/TreeGridConfigGenerator.ts
  live-editing/configs/TreeGridFinjsConfigGenerator.ts
  live-editing/generators/SampleAssetsGenerator.ts
  src/app/app-routing.module.ts
  src/app/grid-finjs/grid-finjs-demo.component.html
  src/app/grid-finjs/grid-finjs-demo.component.scss
  src/app/grid-finjs/grid-finjs-demo.component.ts
  src/app/grid-finjs/grid-finjs-routes-data.ts
  src/app/grid-finjs/grid-finjs-routing.module.ts
  src/app/grid-finjs/grid-finjs.module.ts
  src/app/grid-finjs/localData.service.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
  src/app/index/index.component.ts
  src/app/tree-grid/tree-grid-routes-data.ts
  src/app/tree-grid/tree-grid-routing.module.ts
  src/app/tree-grid/tree-grid.module.ts
  src/app/treegrid-finjs/hierFinancialData.ts
  src/app/treegrid-finjs/tree-grid-finjs-sample.component.html
  src/app/treegrid-finjs/tree-grid-finjs-sample.component.scss
  src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
  src/app/treegrid-finjs/treeLocalData.service.ts
  src/app/treegrid-finjs/treegrid-finjs-routes-data.ts
  src/app/treegrid-finjs/treegrid-finjs-routing.module.ts
  src/app/treegrid-finjs/treegrid-finjs.module.ts
Labels: status: verified
