Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2019-10, with the labels that each got.

#1458 Fixes issues with custom selection and removes redundant code
  src/app/grid/grid-custom-summaries-selection/grid-custom-summaries-selection.component.html
  src/app/grid/grid-custom-summaries-selection/grid-custom-summaries-selection.component.ts
  src/app/grid/grid-custom-summaries-selection/summaries-data/summaries-data.component.ts
Labels: category-bug, status: verified, version: 8.2.x

#1501 Simplify select groups demo
  src/app/data-entries/select/select-sample-2/select-sample-2.component.html
  src/app/data-entries/select/select-sample-2/select-sample-2.component.ts
Labels: ig-select, status: verified

#1499 Merge vNext into master
  live-editing/configs/TreeGridConfigGenerator.ts
  src/app/data-entries/select/select-sample-2/select-sample-2.component.html
  src/app/data-entries/select/select-sample-2/select-sample-2.component.ts
  src/app/grid/grid-custom-summaries-selection/grid-custom-summaries-selection.component.html
  src/app/grid/grid-custom-summaries-selection/grid-custom-summaries-selection.component.ts
  src/app/grid/grid-custom-summaries-selection/summaries-data/summaries-data.component.ts
  src/app/tree-grid/tree-grid-batch-editing/tree-grid-batch-editing-sample.component.html
  src/app/tree-grid/tree-grid-batch-editing/tree-grid-batch-editing-sample.component.ts
  src/app/tree-grid/tree-grid-batch-editing/tree-grid-with-transactions.component.ts
  src/app/tree-grid/tree-grid.module.ts
Labels: version: 8.2.x

#1507 Web config changes master
  web.config
Labels: version: 8.2.x

#1504 Fix grid persistence sample - vNext
  src/app/grid/grid-save-state/grid-state.component.html
  src/app/grid/grid-save-state/state.directive.ts
Labels: status: verified

#1505 Fix grid persistence sample - master
  src/app/grid/grid-save-state/grid-state.component.html
  src/app/grid/grid-save-state/state.directive.ts
Labels: status: verified

#1510 Unifies data sources to master
  live-editing/configs/GridConfigGenerator.ts
  src/app/data/customers.ts
  src/app/data/grid-groupby-summary-data.ts
  src/app/grid/grid-column-hiding-sample/data.ts
  src/app/grid/grid-column-hiding-sample/grid-column-hiding-sample.component.ts
  src/app/grid/grid-column-hiding-toolbar-sample/data.ts
  src/app/grid/grid-column-hiding-toolbar-sample/grid-column-hiding-toolbar-sample.component.ts
  src/app/grid/grid-column-hiding-toolbar-style/data.ts
  src/app/grid/grid-column-hiding-toolbar-style/grid-column-hiding-toolbar-style.component.ts
  src/app/grid/grid-composite-data-binding/grid-composite-data.component.ts
  src/app/grid/grid-composite-data-binding/localData.ts
  src/app/grid/grid-displaydensity-sample/data.ts
  src/app/grid/grid-displaydensity-sample/grid-displaydensity-sample.component.ts
  src/app/grid/grid-excel-style-filtering-sample-2/nwindData.ts
  src/app/grid/grid-excel-style-filtering-sample-3/nwindData.ts
  src/app/grid/grid-groupby-sample/data.ts
  src/app/grid/grid-groupby-sample/grid-groupby-sample.component.ts
  src/app/grid/grid-groupby-styling/grid-groupby-styling.component.ts
  src/app/grid/grid-groupby-summary-sample/grid-groupby-summary-sample.component.ts
  src/app/grid/grid-groupby-summary-styling-sample/grid-groupby-summary-styling-sample.component.ts
  src/app/grid/grid-resizing-sample/data.ts
  src/app/grid/grid-resizing-sample/grid-resizing-sample.component.ts
  src/app/grid/grid-sample-3/data.ts
  src/app/grid/grid-sample-3/grid-sample-3.component.ts
  src/app/grid/grid-sample-pinning/data.ts
  src/app/grid/grid-sample-pinning/grid-pinning.component.ts
  src/app/grid/grid-sample-pinning/grid-toolbar-pinning.component.ts
Labels: category-enhancement, category-refactoring, status: verified, version: 8.3.x

#1512 Items in Kanban sample moved correctly
  src/app/interactions/drag-drop/kanban-sample/kanban-sample.component.html
  src/app/interactions/drag-drop/kanban-sample/kanban-sample.component.ts
Labels: category-bug, ig-drag & drop, status: verified, version: 8.3.x

#1513 TreeGrid Row reordering demo has a missing file in StackBlitz - vNext
  live-editing/configs/TreeGridConfigGenerator.ts
Labels: category-StackBlitz, ig-row-drag, ig-tree-grid, status: verified, version: 9.0.x

#1514 TreeGrid Row reordering demo has a missing file in StackBlitz - master
  live-editing/configs/TreeGridConfigGenerator.ts
Labels: category-StackBlitz, ig-row-drag, ig-tree-grid, status: verified

#1508 Add bottomNav style sample - vNext
  live-editing/configs/TabBarConfigGenerator.ts
  src/app/layouts/layouts-routes-data.ts
  src/app/layouts/layouts-routing.module.ts
  src/app/layouts/layouts.module.ts
  src/app/layouts/tabbar/tabbar-style/tabbar-style.component.html
  src/app/layouts/tabbar/tabbar-style/tabbar-style.component.scss
  src/app/layouts/tabbar/tabbar-style/tabbar-style.component.ts
Labels: ig-bottom-nav, status: verified

#1509 Add bottomNav style sample - master
  live-editing/configs/TabBarConfigGenerator.ts
  src/app/layouts/layouts-routes-data.ts
  src/app/layouts/layouts-routing.module.ts
  src/app/layouts/layouts.module.ts
  src/app/layouts/tabbar/tabbar-style/tabbar-style.component.html
  src/app/layouts/tabbar/tabbar-style/tabbar-style.component.scss
  src/app/layouts/tabbar/tabbar-style/tabbar-style.component.ts
Labels: ig-bottom-nav, status: verified

#1515 Add tree grid style sample - vNext
  live-editing/configs/TreeGridConfigGenerator.ts
  src/app/tree-grid/tree-grid-routes-data.ts
  src/app/tree-grid/tree-grid-routing.module.ts
  src/app/tree-grid/tree-grid-style/tree-grid-style.component.html
  src/app/tree-grid/tree-grid-style/tree-grid-style.component.scss
  src/app/tree-grid/tree-grid-style/tree-grid-style.component.ts
  src/app/tree-grid/tree-grid.module.ts
Labels: ig-tree-grid, status: verified

#1516 Add tree grid style sample - master
  live-editing/configs/TreeGridConfigGenerator.ts
  src/app/tree-grid/tree-grid-routes-data.ts
  src/app/tree-grid/tree-grid-routing.module.ts
  src/app/tree-grid/tree-grid-style/tree-grid-style.component.html
  src/app/tree-grid/tree-grid-style/tree-grid-style.component.scss
  src/app/tree-grid/tree-grid-style/tree-grid-style.component.ts
  src/app/tree-grid/tree-grid.module.ts
Labels: ig-tree-grid, status: verified

#1519 Update carousel routing sample - vNext
  src/app/layouts/carousel/carousel-details/carousel-details.component.ts
  src/app/layouts/carousel/carousel-sample-4/carousel-sample-4.component.ts
Labels: status: verified, version: 8.2.x

#1521 Items in Kanban sample moved correctly
  src/app/interactions/drag-drop/kanban-sample/kanban-sample.component.html
  src/app/interactions/drag-drop/kanban-sample/kanban-sample.component.ts
Labels: category-bug, ig-drag & drop, status: verified

#1524 Update staging to latest 8.2.3 version
  package-lock.json
  package.json
  src/app/scheduling/datepicker/datepicker-sample-8/datepicker-sample-8.component.ts
Labels: status: verified

#1530 Adding grid with chart integration sample (vNext)
  src/app/grid/grid-dynamic-chart-data/chart.service.ts
  src/app/grid/grid-dynamic-chart-data/context-menu/context-menu.component.html
  src/app/grid/grid-dynamic-chart-data/context-menu/context-menu.component.scss
  src/app/grid/grid-dynamic-chart-data/context-menu/context-menu.component.ts
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.html
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.scss
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.ts
  src/app/grid/grid-dynamic-chart-data/initializers.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
  src/app/grid/services/financialData.ts
  src/styles.scss
Labels: status: verified

#1531 Adding grid with chart integration sample (master)
  src/app/grid/grid-dynamic-chart-data/chart.service.ts
  src/app/grid/grid-dynamic-chart-data/context-menu/context-menu.component.html
  src/app/grid/grid-dynamic-chart-data/context-menu/context-menu.component.scss
  src/app/grid/grid-dynamic-chart-data/context-menu/context-menu.component.ts
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.html
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.scss
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.ts
  src/app/grid/grid-dynamic-chart-data/initializers.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
  src/app/grid/services/financialData.ts
  src/styles.scss
Labels: status: verified

#1533 Adding date format for Grid Summary sample (vnext)
  src/app/grid/grid-sample-3/grid-sample-3.component.html
Labels: status: verified

#1532 Formatting date column for Grid Summary sample (master)
  src/app/grid/grid-sample-3/grid-sample-3.component.html
Labels: status: verified

#1539 Refactor selection based summary sample
  live-editing/configs/GridConfigGenerator.ts
  src/app/grid/grid-custom-summaries-selection/grid-custom-summaries-selection.component.html
  src/app/grid/grid-custom-summaries-selection/grid-custom-summaries-selection.component.scss
  src/app/grid/grid-custom-summaries-selection/grid-custom-summaries-selection.component.ts
  src/app/grid/grid-custom-summaries-selection/summaries-data/summaries-data.component.html
  src/app/grid/grid-custom-summaries-selection/summaries-data/summaries-data.component.scss
  src/app/grid/grid-custom-summaries-selection/summaries-data/summaries-data.component.ts
  src/app/grid/grids.module.ts
Labels: status: verified

#1545 Refactor selection based summary sample --master
  live-editing/configs/GridConfigGenerator.ts
  src/app/grid/grid-custom-summaries-selection/grid-custom-summaries-selection.component.html
  src/app/grid/grid-custom-summaries-selection/grid-custom-summaries-selection.component.scss
  src/app/grid/grid-custom-summaries-selection/grid-custom-summaries-selection.component.ts
  src/app/grid/grid-custom-summaries-selection/summaries-data/summaries-data.component.html
  src/app/grid/grid-custom-summaries-selection/summaries-data/summaries-data.component.scss
  src/app/grid/grid-custom-summaries-selection/summaries-data/summaries-data.component.ts
  src/app/grid/grids.module.ts
Labels: status: verified

#1542 Update master to 8.2.5
  package-lock.json
  package.json
  src/app/scheduling/datepicker/datepicker-sample-8/datepicker-sample-8.component.ts
Labels: status: verified

#1551 chore: update to ignite-ui angular 8.2.6
  package-lock.json
  package.json
  src/app/grid/custom-grid-paging-style/custom-grid-paging-style.component.scss
  src/app/grid/grid-boston-marathon/grid.component.scss
  src/app/grid/grid-remote-paging-sample/remote-paging-sample.component.html
  src/app/hierarchical-grid/hierarchical-grid-paging-style/hierarchical-grid-paging-style.component.scss
  src/app/hierarchical-grid/hierarchical-grid-paging/hierarchical-grid-remote-paging.component.html
  src/app/theming/styles/dark-theme-class.scss
  src/app/theming/styles/dark-theme.scss
  src/app/theming/styles/schemas.scss
  src/app/theming/styles/theme-classes.scss
  src/app/theming/styles/themes.scss
  src/app/tree-grid/tree-grid-paging-style/tree-grid-paging-style-sample.component.scss
  src/app/tree-grid/tree-grid-remote-paging-sample/tree-grid-remote-paging-sample.component.html
Labels: status: verified, version: 9.0.x

#1548 Update select group sample to use text @Input
  src/app/data-entries/select/select-sample-2/select-sample-2.component.html
  src/app/data-entries/select/select-sample-2/select-sample-2.component.scss
  src/app/data-entries/select/select-sample-2/select-sample-2.component.ts
Labels: category-enhancement, ig-select, status: verified, version: 8.2.x

#1536 Look for the correct file in "additionalFiles"
  live-editing/configs/OverlayConfigGenerator.ts
Labels: category-StackBlitz, ig-overlay, status: verified

#1535 Look for the correct file in "additionalFiles"
  live-editing/configs/OverlayConfigGenerator.ts
Labels: category-StackBlitz, ig-overlay, status: verified
