Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2019-12, with the labels that each got.

#1622 Update to beta 6
  angular.json
  gulpfile.js
  package-lock.json
  package.json
  src/app/date-parser.ts
  src/app/grid-crm/grid-crm/grid-crm.component.ts
  src/app/grid-finjs/grid-finjs-demo.component.html
  src/app/grid/grid-editing-events/grid-editing-events.component.ts
  src/app/grid/grid-sorting-sample/grid-sorting-sample.component.ts
  src/app/grid/grid-sorting-styling/grid-sorting-styling.component.ts
  src/app/hierarchical-grid/hierarchical-grid-paging/hierarchical-grid-remote-paging.component.ts
  src/app/interactions/drag-drop/kanban-sample/kanban-sample.component.ts
  src/app/interactions/drag-drop/list-reorder-sample/list-reorder-sample.component.ts
  src/app/interactions/slider/slider-sample-2/slider-sample-2.component.html
  src/app/layouts/card/card-sample-4/card-sample-4.component.html
  src/app/layouts/expansion-panel/expansion-sample-4/expansion-sample-4.component.ts
  src/app/lists/combo/combo-binding/combo-binding.component.ts
  src/app/lists/list/list-sample-1/list-sample-1.component.ts
  src/app/lists/list/list-sample-7/list-sample-7.component.html
  src/app/treegrid-finjs/tree-grid-finjs-sample.component.html
  src/tsconfig.app.json
  tsconfig.json
Labels: status: verified

#1596 Add paginator pagingsample v next
  live-editing/configs/GridConfigGenerator.ts
  src/app/grid/grid-custom-remote-paging-sample/custom-remote-paging-sample.component.html
  src/app/grid/grid-custom-remote-paging-sample/custom-remote-paging-sample.component.scss
  src/app/grid/grid-custom-remote-paging-sample/custom-remote-paging-sample.component.ts
  src/app/grid/grid-remote-paging-sample/remote-paging-sample.component.html
  src/app/grid/grid-remote-paging-sample/remote-paging-sample.component.scss
  src/app/grid/grid-remote-paging-sample/remote-paging-sample.component.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
  src/app/grid/services/remotePagingService.ts
  src/app/hierarchical-grid/hierarchical-grid-paging/hierarchical-grid-remote-paging.component.html
  src/app/hierarchical-grid/hierarchical-grid-paging/hierarchical-grid-remote-paging.component.ts
  src/app/tree-grid/tree-grid-remote-paging-sample/tree-grid-remote-paging-sample.component.html
  src/app/tree-grid/tree-grid-remote-paging-sample/tree-grid-remote-paging-sample.component.ts
Labels: status: verified

#1570 Adding master-detail sample for grid
  live-editing/configs/GridConfigGenerator.ts
  package-lock.json
  src/app/grid/grid-master-detail/grid-master-detail.component.html
  src/app/grid/grid-master-detail/grid-master-detail.component.scss
  src/app/grid/grid-master-detail/grid-master-detail.component.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
  src/app/hierarchical-grid/hierarchical-grid.module.ts
Labels: status: in-test

#1624 fix(Card): Replaced broken links with relative urls. #1613
  src/app/layouts/card/card-sample-4/card-sample-4.component.html
  src/assets/images/card/avatars/photographer.jpg
  src/assets/images/card/media/photographer_portfolio.jpg
Labels: card, status: verified

#1621 fix(Card): Replaced broken links with relative urls. #1613
  src/app/layouts/card/card-sample-4/card-sample-4.component.html
  src/assets/images/card/avatars/photographer.jpg
  src/assets/images/card/media/photographer_portfolio.jpg
Labels: card, status: verified

#1627 Fix finjs livediting config v next
  live-editing/configs/GridFinjsConfigGenerator.ts
Labels: status: verified

#1601 Enhance state persistence sample vnext
  live-editing/configs/GridConfigGenerator.ts
  src/app/grid/grid-save-state/grid-state.component.html
  src/app/grid/grid-save-state/grid-state.component.scss
  src/app/grid/grid-save-state/grid-state.component.ts
  src/app/grid/grid-save-state/state.directive.ts
  src/app/grid/grids.module.ts
Labels: status: verified

#1623 All Data summary sample
  live-editing/configs/GridConfigGenerator.ts
  live-editing/configs/HierarchicalGridConfigGenerator.ts
  live-editing/configs/TreeGridConfigGenerator.ts
  src/app/data/nwindData.ts
  src/app/grid/grid-allData-summary/grid-allData-summary.component.html
  src/app/grid/grid-allData-summary/grid-allData-summary.component.scss
  src/app/grid/grid-allData-summary/grid-allData-summary.component.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
  src/app/hierarchical-grid/hierarchical-grid-allData-summary/hierarchical-grid-allData-summary.component.html
  src/app/hierarchical-grid/hierarchical-grid-allData-summary/hierarchical-grid-allData-summary.component.scss
  src/app/hierarchical-grid/hierarchical-grid-allData-summary/hierarchical-grid-allData-summary.component.ts
  src/app/hierarchical-grid/hierarchical-grid-routes-data.ts
  src/app/hierarchical-grid/hierarchical-grid-routing.module.ts
  src/app/hierarchical-grid/hierarchical-grid.module.ts
  src/app/tree-grid/tree-grid-routes-data.ts
  src/app/tree-grid/tree-grid-routing.module.ts
  src/app/tree-grid/tree-grid.module.ts
  src/app/tree-grid/treegrid-allData-summary/treegrid-allData-summary.component.html
  src/app/tree-grid/treegrid-allData-summary/treegrid-allData-summary.component.scss
  src/app/tree-grid/treegrid-allData-summary/treegrid-allData-summary.component.ts
Labels: grid, status: verified, summaries

#1626 fix FinJS demo live-editing config - master
  live-editing/configs/GridFinjsConfigGenerator.ts
  package-lock.json
Labels: status: verified, version: 9.0.x

#1608 Slider ticks samples
  live-editing/configs/SliderConfigGenerator.ts
  src/app/interactions/interactions-routes-data.ts
  src/app/interactions/interactions-routing.module.ts
  src/app/interactions/interactions.module.ts
  src/app/interactions/slider/discrete-slider-ticks-bottom/discrete-slider-ticks-bottom.component.html
  src/app/interactions/slider/discrete-slider-ticks-bottom/discrete-slider-ticks-bottom.component.scss
  src/app/interactions/slider/discrete-slider-ticks-bottom/discrete-slider-ticks-bottom.component.ts
  src/app/interactions/slider/slider-primary-ticks-top/slider-primary-ticks-top.component.html
  src/app/interactions/slider/slider-primary-ticks-top/slider-primary-ticks-top.component.scss
  src/app/interactions/slider/slider-primary-ticks-top/slider-primary-ticks-top.component.ts
  src/app/interactions/slider/slider-secondary-ticks-mirror/slider-secondary-ticks-mirror.component.html
  src/app/interactions/slider/slider-secondary-ticks-mirror/slider-secondary-ticks-mirror.component.scss
  src/app/interactions/slider/slider-secondary-ticks-mirror/slider-secondary-ticks-mirror.component.ts
  src/app/interactions/slider/slider-tick-labels-template/tick-labels-template.component.html
  src/app/interactions/slider/slider-tick-labels-template/tick-labels-template.component.scss
  src/app/interactions/slider/slider-tick-labels-template/tick-labels-template.component.ts
  src/app/interactions/slider/slider-ticks-bottomtotop-labels/slider-ticks-bottomtotop-labels.component.html
  src/app/interactions/slider/slider-ticks-bottomtotop-labels/slider-ticks-bottomtotop-labels.component.scss
  src/app/interactions/slider/slider-ticks-bottomtotop-labels/slider-ticks-bottomtotop-labels.component.ts
  src/app/interactions/slider/slider-timeframe/slider-timeframe.component.html
  src/app/interactions/slider/slider-timeframe/slider-timeframe.component.scss
  src/app/interactions/slider/slider-timeframe/slider-timeframe.component.ts
  src/app/treegrid-finjs/tree-grid-finjs-sample.component.html
Labels: slider, status: verified, version: 9.0.x

#1609 Collapsible Column Groups Sample
  live-editing/configs/GridConfigGenerator.ts
  live-editing/configs/HierarchicalGridConfigGenerator.ts
  live-editing/configs/TreeGridConfigGenerator.ts
  src/app/grid/grid-collapsible-columnGroups/grid-collapsible-column-groups.component.html
  src/app/grid/grid-collapsible-columnGroups/grid-collapsible-column-groups.component.scss
  src/app/grid/grid-collapsible-columnGroups/grid-collapsible-column-groups.component.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
  src/app/hierarchical-grid/hierarchical-grid-collapsible-column-groups/hierarchical-grid-collapsible-column-groups.component.html
  src/app/hierarchical-grid/hierarchical-grid-collapsible-column-groups/hierarchical-grid-collapsible-column-groups.component.scss
  src/app/hierarchical-grid/hierarchical-grid-collapsible-column-groups/hierarchical-grid-collapsible-column-groups.component.ts
  src/app/hierarchical-grid/hierarchical-grid-routes-data.ts
  src/app/hierarchical-grid/hierarchical-grid-routing.module.ts
  src/app/hierarchical-grid/hierarchical-grid.module.ts
  src/app/tree-grid/tree-grid-collapsible-groups/tree-grid-collapsible-column-groups.component.html
  src/app/tree-grid/tree-grid-collapsible-groups/tree-grid-collapsible-column-groups.component.scss
  src/app/tree-grid/tree-grid-collapsible-groups/tree-grid-collapsible-column-groups.component.ts
  src/app/tree-grid/tree-grid-routes-data.ts
  src/app/tree-grid/tree-grid-routing.module.ts
  src/app/tree-grid/tree-grid.module.ts
Labels: grid, status: verified

#1628 All Data summary sample --master
  live-editing/configs/GridConfigGenerator.ts
  live-editing/configs/HierarchicalGridConfigGenerator.ts
  live-editing/configs/TreeGridConfigGenerator.ts
  src/app/data/nwindData.ts
  src/app/grid/grid-allData-summary/grid-allData-summary.component.html
  src/app/grid/grid-allData-summary/grid-allData-summary.component.scss
  src/app/grid/grid-allData-summary/grid-allData-summary.component.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
  src/app/hierarchical-grid/hierarchical-grid-allData-summary/hierarchical-grid-allData-summary.component.html
  src/app/hierarchical-grid/hierarchical-grid-allData-summary/hierarchical-grid-allData-summary.component.scss
  src/app/hierarchical-grid/hierarchical-grid-allData-summary/hierarchical-grid-allData-summary.component.ts
  src/app/hierarchical-grid/hierarchical-grid-routes-data.ts
  src/app/hierarchical-grid/hierarchical-grid-routing.module.ts
  src/app/hierarchical-grid/hierarchical-grid.module.ts
  src/app/tree-grid/tree-grid-routes-data.ts
  src/app/tree-grid/tree-grid-routing.module.ts
  src/app/tree-grid/tree-grid.module.ts
  src/app/tree-grid/treegrid-allData-summary/treegrid-allData-summary.component.html
  src/app/tree-grid/treegrid-allData-summary/treegrid-allData-summary.component.scss
  src/app/tree-grid/treegrid-allData-summary/treegrid-allData-summary.component.ts
Labels: grid, status: verified, summaries

#1599 Add paginator to remote paging samples
  live-editing/configs/GridConfigGenerator.ts
  src/app/grid/grid-custom-remote-paging-sample/custom-remote-paging-sample.component.html
  src/app/grid/grid-custom-remote-paging-sample/custom-remote-paging-sample.component.scss
  src/app/grid/grid-custom-remote-paging-sample/custom-remote-paging-sample.component.ts
  src/app/grid/grid-remote-paging-sample/remote-paging-sample.component.html
  src/app/grid/grid-remote-paging-sample/remote-paging-sample.component.scss
  src/app/grid/grid-remote-paging-sample/remote-paging-sample.component.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
  src/app/grid/services/remotePagingService.ts
  src/app/hierarchical-grid/hierarchical-grid-paging/hierarchical-grid-remote-paging.component.html
  src/app/hierarchical-grid/hierarchical-grid-paging/hierarchical-grid-remote-paging.component.ts
  src/app/tree-grid/tree-grid-remote-paging-sample/tree-grid-remote-paging-sample.component.html
  src/app/tree-grid/tree-grid-remote-paging-sample/tree-grid-remote-paging-sample.component.ts
Labels: status: verified

#1630 chore(*): Fixing mdv sample stackblitz config.
  live-editing/configs/GridConfigGenerator.ts
  src/app/grid/grid-master-detail/grid-master-detail.component.html
  src/app/grid/grid-master-detail/grid-master-detail.component.scss
Labels: status: verified

#1620 Fix samples leaking css
  src/app/data-entries/dropdown/dropdown-menu/dropdown-menu.component.scss
  src/app/data-entries/dropdown/dropdown-menu/dropdown-menu.component.ts
Labels: status: verified, styling, version: 9.0.x

#1634 Updates samples with the themes generated from the theming widget
  src/app/index/docs-layout.component.ts
Labels: status: verified

#1643 Add conditional styling directive to chart integration sample (VNEXT)
  src/app/grid/grid-dynamic-chart-data/conditional-formatting.directive.ts
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.html
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.scss
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.ts
  src/app/grid/grids.module.ts
  src/app/grid/services/financialData.ts
  src/assets/images/svg/conditions/ColorScale.svg
  src/assets/images/svg/conditions/DataBars.svg
  src/assets/images/svg/conditions/DuplicateValues.svg
  src/assets/images/svg/conditions/Empty.svg
  src/assets/images/svg/conditions/Equal.svg
  src/assets/images/svg/conditions/GreaterThan.svg
  src/assets/images/svg/conditions/TextContains.svg
  src/assets/images/svg/conditions/Top10.svg
  src/assets/images/svg/conditions/UniqueValues.svg
Labels: status: verified

#1644 Add conditional styling directive for chart integration sample (MASTER)
  src/app/grid/grid-dynamic-chart-data/conditional-formatting.directive.ts
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.html
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.scss
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.ts
  src/app/grid/grids.module.ts
  src/app/grid/services/financialData.ts
  src/assets/images/svg/conditions/ColorScale.svg
  src/assets/images/svg/conditions/DataBars.svg
  src/assets/images/svg/conditions/DuplicateValues.svg
  src/assets/images/svg/conditions/Empty.svg
  src/assets/images/svg/conditions/Equal.svg
  src/assets/images/svg/conditions/GreaterThan.svg
  src/assets/images/svg/conditions/TextContains.svg
  src/assets/images/svg/conditions/Top10.svg
  src/assets/images/svg/conditions/UniqueValues.svg
Labels: status: verified

#1642 Fixing MDV sample issues in Stackblitz
  live-editing/configs/GridConfigGenerator.ts
  src/app/grid/grid-master-detail/grid-master-detail.component.html
Labels: master-detail, status: verified

#1646 Bring back light and dark theme selection only on IE11.
  src/app/index/docs-layout.component.ts
Labels: status: verified, theming

#1640 Fix daily icons
  src/app/layouts/expansion-panel/expansion-sample-7/expansion-sample-7.component.html
Labels: ig-expansion-panel, status: verified

#1647 Update grid row reorder sample to include window scroll position.
  src/app/grid/grid-row-reorder-sample/grid-row-reorder.ts
  src/app/hierarchical-grid/hierarchical-grid-row-reorder/hierarchical-grid-row-reorder.component.ts
  src/app/tree-grid/tree-grid-row-reorder/tree-grid-row-reorder.component.ts
Labels: grid, row-drag, status: verified

#1645 leave the button exactly as how the default theme styles it
  src/app/theming/default-theme-sample/default-theme-sample.component.html
  src/app/theming/default-theme-sample/default-theme-sample.component.scss
Labels: status: verified, theming, version: 9.0.x

#1649 Enhancing Conditional styling in chart integration sample
  src/app/grid/grid-dynamic-chart-data/conditional-formatting.directive.ts
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.html
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.scss
  src/app/grid/grid-dynamic-chart-data/grid-dynamic-chart-data.component.ts
  src/assets/images/svg/conditions/Clear.svg
Labels: status: verified
