Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2020-06, with the labels that each got.

#2058 Nalipiev/9.1.0 update
  package-lock.json
  package.json
  src/app/grid/grid-editing-events/grid-editing-events.component.html
  src/app/notifications/toast/toast-sample-1/toast-sample-1.component.html
  src/app/notifications/toast/toast-sample-2/toast-sample-2.component.html
  src/app/notifications/toast/toast-sample-3/toast-sample-3.component.html
  src/app/notifications/toast/toast-sample-4/toast-sample-4.component.html
  src/app/notifications/toast/toast-sample-5/toast-sample-5.component.html
  src/app/notifications/toast/toast-style/toast-style.component.html
  src/app/scheduling/timepicker/timepicker-sample-4/timepicker-sample-4.component.html
Labels: status: verified, version: 9.1.x

#2037 Increase Requested Chunk Size in the Remote Virtualization Sample
  src/app/grid/grid-sample-4/grid-sample-4.component.ts
  src/app/grid/services/remoteService.ts
Labels: status: verified, version: 9.1.x

#2059 chore(*): update to dockmanager 1.0.0
  package-lock.json
  package.json
Labels: status: verified

#2062 Update carousel images src
  src/app/layouts/carousel/carousel.component.ts
Labels: version: 10.0.x

#2063 Update carousel images src - master
  src/app/layouts/carousel/carousel.component.ts
Labels: version: 9.1.x

#2057 Remove duplicate columns in MCH sample - master
  src/app/grid/multi-column-headers/multi-column-headers.html
Labels: status: verified, version: 9.0.x

#2056 Remove duplicate columns in MCH sample
  src/app/grid/multi-column-headers/multi-column-headers.html
Labels: status: resolved, version: 9.1.x

#2065 fix(sample): Prevent keydown events from inside the details template …
  projects/app-lob/src/app/grid/grid-master-detail/grid-master-detail.component.html
Labels: status: verified

#2047 Single Row Loading Indicator on Remote Virtualization Sample
  src/app/grid/grid-sample-4/grid-sample-4.component.html
  src/app/grid/grid-sample-4/grid-sample-4.component.ts
  src/app/grid/services/remoteService.ts
Labels: grid, status: verified, version: 9.1.x

#2075 Update npm install to ci
  azure-pipelines.yml
Labels: build

#2069 fix(drop-down): remote sample use proper unique value binding - master
  src/app/data-entries/dropdown/drop-down-remote-virtual/drop-down-remote.component.html
Labels: dropdown, status: verified, version: 9.1.x

#2084 refactor(drop-down): improve drop-down samples
  src/app/data-entries/dropdown/drop-down-remote-virtual/drop-down-remote.component.html
  src/app/data-entries/dropdown/drop-down-remote-virtual/drop-down-remote.component.scss
  src/app/data-entries/dropdown/drop-down-virtual/drop-down-virtual.component.html
  src/app/data-entries/dropdown/drop-down-virtual/drop-down-virtual.component.scss
  src/app/data-entries/dropdown/drop-down-virtual/drop-down-virtual.component.ts
  src/app/data-entries/dropdown/dropdown-menu/dropdown-menu.component.html
  src/app/data-entries/dropdown/dropdown-menu/dropdown-menu.component.scss
  src/app/data-entries/dropdown/dropdown-menu/dropdown-menu.component.ts
  src/app/data-entries/dropdown/dropdown-sample-1/dropdown-sample-1.component.html
  src/app/data-entries/dropdown/dropdown-sample-1/dropdown-sample-1.component.scss
  src/app/data-entries/dropdown/dropdown-sample-2/dropdown-sample-2.component.html
  src/app/data-entries/dropdown/dropdown-sample-2/dropdown-sample-2.component.scss
  src/app/data-entries/dropdown/dropdown-sample-3/dropdown-sample-3.component.html
  src/app/data-entries/dropdown/dropdown-sample-3/dropdown-sample-3.component.scss
  src/app/data-entries/dropdown/dropdown-sample-4/dropdown-sample-4.component.html
  src/app/data-entries/dropdown/dropdown-sample-4/dropdown-sample-4.component.scss
  src/app/data-entries/dropdown/dropdown-sample-5/dropdown-sample-5.component.html
  src/app/data-entries/dropdown/dropdown-sample-5/dropdown-sample-5.component.scss
  src/app/data-entries/dropdown/dropdown-styling/dropdown-styling.component.html
  src/app/data-entries/dropdown/dropdown-styling/dropdown-styling.component.scss
Labels: dropdown, refactoring, status: verified, version: 10.0.x

#2072 Add igxHint in select samples
  src/app/data-entries/select/select-input-directives/select-input-directives.html
Labels: enhancement, select, status: verified, version: 9.2.x

#2078 Rename ESF template lables to more meaningful ones
  src/app/grid/grid-excel-style-filtering-sample-3/grid-excel-style-filtering-sample-3.component.html
  src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-sample-3/hierarchical-grid-excel-style-filtering-sample-3.component.html
  src/app/tree-grid/tree-grid-excel-style-filtering-sample-3/tree-grid-excel-style-filtering-sample-3.component.html
Labels: status: verified

#2082 Rename ESF template lables to more meaningful ones
  src/app/grid/grid-excel-style-filtering-sample-3/grid-excel-style-filtering-sample-3.component.html
  src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-sample-3/hierarchical-grid-excel-style-filtering-sample-3.component.html
  src/app/tree-grid/tree-grid-excel-style-filtering-sample-3/tree-grid-excel-style-filtering-sample-3.component.html
Labels: status: verified

#2086 fix(select): adjust select item content display to account for lib change
  src/app/data-entries/select/select-header-footer/select-header-footer.component.html
  src/app/data-entries/select/select-header-footer/select-header-footer.component.scss
  src/app/data-entries/select/select-header-footer/select-header-footer.component.ts
  src/app/data-entries/select/select-sample-2/select-sample-2.component.html
  src/app/data-entries/select/select-sample-2/select-sample-2.component.scss
  src/app/data-entries/select/select-sample-2/select-sample-2.component.ts
Labels: select, status: verified

#2029 Grid Remote paging using default paging template
  live-editing/configs/GridConfigGenerator.ts
  live-editing/configs/HierarchicalGridConfigGenerator.ts
  live-editing/configs/TreeGridConfigGenerator.ts
  package-lock.json
  package.json
  src/app/grid/grid-remote-paging-defaultTemplate-sample/remote-paging-default-template.component.html
  src/app/grid/grid-remote-paging-defaultTemplate-sample/remote-paging-default-template.component.scss
  src/app/grid/grid-remote-paging-defaultTemplate-sample/remote-paging-default-template.component.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
  src/app/hierarchical-grid/hierarchical-grid-remote-paging-default-template/hierarchical-grid-remote-paging-default-template.component.html
  src/app/hierarchical-grid/hierarchical-grid-remote-paging-default-template/hierarchical-grid-remote-paging-default-template.component.scss
  src/app/hierarchical-grid/hierarchical-grid-remote-paging-default-template/hierarchical-grid-remote-paging-default-template.component.ts
  src/app/hierarchical-grid/hierarchical-grid-remote-paging-default-template/remotePagingService.ts
  src/app/hierarchical-grid/hierarchical-grid-routes-data.ts
  src/app/hierarchical-grid/hierarchical-grid-routing.module.ts
  src/app/hierarchical-grid/hierarchical-grid.module.ts
  src/app/tree-grid/tree-grid-remote-paging-default-template/remotePagingService.ts
  src/app/tree-grid/tree-grid-remote-paging-default-template/tree-grid-remote-paging-default-template.component.html
  src/app/tree-grid/tree-grid-remote-paging-default-template/tree-grid-remote-paging-default-template.component.scss
  src/app/tree-grid/tree-grid-remote-paging-default-template/tree-grid-remote-paging-default-template.component.ts
  src/app/tree-grid/tree-grid-routes-data.ts
  src/app/tree-grid/tree-grid-routing.module.ts
  src/app/tree-grid/tree-grid.module.ts
Labels: grid, paging, status: verified, version: 9.1.x

#2090 refactor text highlight samples
  src/app/data-display/text-highlight/text-highlight-sample-1/text-highlight-sample-1.component.html
  src/app/data-display/text-highlight/text-highlight-sample-1/text-highlight-sample-1.component.scss
  src/app/data-display/text-highlight/text-highlight-sample-1/text-highlight-sample-1.component.ts
  src/app/data-display/text-highlight/text-highlight-sample-2/text-highlight-sample-2.component.html
  src/app/data-display/text-highlight/text-highlight-sample-2/text-highlight-sample-2.component.scss
  src/app/data-display/text-highlight/text-highlight-sample-2/text-highlight-sample-2.component.ts
  src/app/data-display/text-highlight/text-highlight-style/text-highlight-style.component.html
  src/app/data-display/text-highlight/text-highlight-style/text-highlight-style.component.scss
  src/app/data-display/text-highlight/text-highlight-style/text-highlight-style.component.ts
Labels: refactoring, status: awaiting-test, text-highlight, version: 10.0.x

#2083 refactor(autocomplete): improve autocomplete samples
  live-editing/configs/AutocompleteConfigGenerator.ts
  src/app/data-entries/autocomplete/autocomplete-remote/autocomplete-remote.component.html
  src/app/data-entries/autocomplete/autocomplete-remote/autocomplete-remote.component.scss
  src/app/data-entries/autocomplete/autocomplete-remote/autocomplete-remote.component.ts
  src/app/data-entries/autocomplete/autocomplete/autocomplete.component.html
  src/app/data-entries/autocomplete/movie/movie.component.html
  src/app/data-entries/autocomplete/movie/movie.component.scss
  src/app/data-entries/autocomplete/movie/movie.component.ts
  src/app/data-entries/data-entries-routes-data.ts
  src/app/data-entries/data-entries-routing.module.ts
  src/app/data-entries/data-entries.module.ts
Labels: autocomplete, refactoring, status: awaiting-test, version: 10.0.x

#2092 Kb nav ehancements
  src/app/grid/grid-keyboardnav-guide-sample/grid-keyboardnav-sample.component.html
  src/app/grid/grid-keyboardnav-guide-sample/grid-keyboardnav-sample.component.scss
  src/app/grid/grid-keyboardnav-guide-sample/grid-keyboardnav-sample.component.ts
  src/app/hierarchical-grid/hgrid-keybarod-nav-guide-sample/hgrid-keyboard-guide.component.html
  src/app/hierarchical-grid/hgrid-keybarod-nav-guide-sample/hgrid-keyboard-guide.component.scss
  src/app/hierarchical-grid/hgrid-keybarod-nav-guide-sample/hgrid-keyboard-guide.component.ts
  src/app/tree-grid/tgrid-keyboard-guide/tgrid-keyboardnav-guide.component.html
  src/app/tree-grid/tgrid-keyboard-guide/tgrid-keyboardnav-guide.component.scss
  src/app/tree-grid/tgrid-keyboard-guide/tgrid-keyboardnav-guide.component.ts
Labels: status: verified

#2094 refactor(select): improve select samples
  live-editing/configs/SelectConfigGenerator.ts
  src/app/data-entries/data-entries-routes-data.ts
  src/app/data-entries/data-entries-routing.module.ts
  src/app/data-entries/data-entries.module.ts
  src/app/data-entries/select/select-form/select-form.component.html
  src/app/data-entries/select/select-form/select-form.component.scss
  src/app/data-entries/select/select-form/select-form.component.ts
  src/app/data-entries/select/select-header-footer/select-header-footer.component.scss
  src/app/data-entries/select/select-input-directives/select-input-directives.html
  src/app/data-entries/select/select-input-directives/select-input-directives.scss
  src/app/data-entries/select/select-sample-1/select-sample-1.component.html
  src/app/data-entries/select/select-sample-1/select-sample-1.component.scss
  src/app/data-entries/select/select-sample-2/select-sample-2.component.html
  src/app/data-entries/select/select-sample-2/select-sample-2.component.scss
  src/app/data-entries/select/select-sample-3/select-sample-3.component.html
  src/app/data-entries/select/select-sample-3/select-sample-3.component.scss
  src/app/data-entries/select/select-sample-3/select-sample-3.component.ts
  src/app/data-entries/select/select-styling/select-styling.component.html
  src/app/data-entries/select/select-styling/select-styling.component.scss
  src/app/data-entries/select/select-styling/select-styling.component.ts
Labels: refactoring, select, status: awaiting-test, version: 10.0.x

#2095 Keyboard navigation enahncements
  src/app/grid/grid-keyboardnav-guide-sample/grid-keyboardnav-sample.component.html
  src/app/grid/grid-keyboardnav-guide-sample/grid-keyboardnav-sample.component.scss
  src/app/grid/grid-keyboardnav-guide-sample/grid-keyboardnav-sample.component.ts
  src/app/hierarchical-grid/hgrid-keybarod-nav-guide-sample/hgrid-keyboard-guide.component.html
  src/app/hierarchical-grid/hgrid-keybarod-nav-guide-sample/hgrid-keyboard-guide.component.scss
  src/app/hierarchical-grid/hgrid-keybarod-nav-guide-sample/hgrid-keyboard-guide.component.ts
  src/app/tree-grid/tgrid-keyboard-guide/tgrid-keyboardnav-guide.component.html
  src/app/tree-grid/tgrid-keyboard-guide/tgrid-keyboardnav-guide.component.scss
  src/app/tree-grid/tgrid-keyboard-guide/tgrid-keyboardnav-guide.component.ts
Labels: status: verified

#2079 Update custom styles in some samples #1418
  src/app/grid/custom-grid-paging-style/custom-grid-paging-style.component.scss
  src/app/grid/grid-column-hiding-toolbar-style/grid-column-hiding-toolbar-style.component.scss
  src/app/grid/grid-filtering-style/grid-filtering-style.component.scss
Labels: grid, status: verified, styling

#2098 Fix(): error should not be thrown when load Column Moving Samples - master
  src/app/grid/grid-moving-sample/grid-moving-sample.component.html
  src/app/grid/grid-moving-sample/grid-moving-sample.component.ts
  src/app/grid/grid-moving-styled-sample/grid-moving-styled-sample.component.html
  src/app/grid/grid-moving-styled-sample/grid-moving-styled-sample.component.ts
Labels: column moving, grid, status: verified

#2097 Fix(): error should not be thrown when load Column Moving Samples - vnext
  src/app/grid/grid-moving-sample/grid-moving-sample.component.html
  src/app/grid/grid-moving-sample/grid-moving-sample.component.ts
  src/app/grid/grid-moving-styled-sample/grid-moving-styled-sample.component.html
  src/app/grid/grid-moving-styled-sample/grid-moving-styled-sample.component.ts
Labels: column moving, grid, status: verified

#2099 Updating to Angular 10
  angular.json
  e2e/tsconfig.e2e.json
  live-editing/generators/SampleAssetsGenerator.ts
  package-lock.json
  package.json
  projects/app-lob/.browserslistrc
  projects/app-lob/e2e/tsconfig.json
  projects/app-lob/tsconfig.app.json
  projects/app-lob/tsconfig.spec.json
  src/app/data-entries/dropdown/dropdown-menu/dropdown-menu.component.ts
  src/app/data-entries/dropdown/dropdown-sample-1/dropdown-sample-1.component.ts
  src/app/data-entries/dropdown/dropdown-sample-2/dropdown-sample-2.component.ts
  src/app/data-entries/dropdown/dropdown-sample-4/dropdown-sample-4.component.ts
  src/app/data-entries/dropdown/dropdown-sample-5/dropdown-sample-5.component.ts
  src/app/data-entries/select/select-header-footer/select-header-footer.component.ts
  src/app/data-entries/select/select-sample-2/select-sample-2.component.ts
  src/app/grid/grid-editing-sample/grid-editing-sample.component.ts
  src/app/hierarchical-grid/services/remote-lod.service.ts
  src/app/interactions/tooltip/tooltip-rich/tooltip-rich.component.scss
  src/app/notifications/banner/banner-sample-4/banner-sample-4.component.scss
  src/tsconfig.app.json
  src/tsconfig.spec.json
  tsconfig.base.json
  tsconfig.json
  tslint.json
Labels: status: verified

#2101 Update grid edit events sample
  src/app/grid/grid-editing-events/grid-editing-events.component.ts
  src/app/hierarchical-grid/hierarchical-grid-editing-events/hierarchical-grid-editing-events.component.html
  src/app/hierarchical-grid/hierarchical-grid-editing-events/hierarchical-grid-editing-events.component.ts
  src/app/tree-grid/tree-grid-editing-events/tree-grid-editing-events.component.ts
Labels: grid, severity: medium, status: pending-localization, status: verified, version: 10.0.x, version: 9.1.x, version: 9.2.x

#2103 Adding igniteui-angular-live-editing submodule and gulp task configuration
  .gitmodules
  .vscode/launch.json
  gulpfile.js
  live-editing/generators/SampleAssetsGenerator.ts
  live-editing/generators/SharedAssetsGenerator.ts
  live-editing/generators/misc/SharedAssetsFile.ts
  live-editing/services/DependencyResolver.ts
  package-lock.json
  package.json
Labels: status: in-test
