Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2020-05, with the labels that each got.

#1960 refactor(label&input): refactor label&input samples
  live-editing/configs/InputGroupConfigGenerator.ts
  src/app/data-entries/input-group/input-group-sample-1/input-group-sample-1.component.html
  src/app/data-entries/input-group/input-group-sample-1/input-group-sample-1.component.scss
  src/app/data-entries/input-group/input-group-sample-1/input-group-sample-1.component.ts
  src/app/data-entries/input-group/input-group-sample-2/input-group-sample-2.component.html
  src/app/data-entries/input-group/input-group-sample-2/input-group-sample-2.component.scss
  src/app/data-entries/input-group/input-group-sample-2/input-group-sample-2.component.ts
Labels: input, refactoring, status: verified, version: 9.1.x

#1946 Sample Grid and Action Strip width transaction actions.
  live-editing/configs/GridConfigGenerator.ts
  src/app/grid/grid-action-strip/grid-action-strip-sample.html
  src/app/grid/grid-action-strip/grid-action-strip-sample.scss
  src/app/grid/grid-action-strip/grid-action-strip-sample.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
Labels: status: awaiting-test

#1948 Implement keyboard navigation sample
  live-editing/configs/GridConfigGenerator.ts
  src/app/grid/grid-keyboardnav-guide-sample/grid-keyboardnav-sample.component.html
  src/app/grid/grid-keyboardnav-guide-sample/grid-keyboardnav-sample.component.scss
  src/app/grid/grid-keyboardnav-guide-sample/grid-keyboardnav-sample.component.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
  src/app/tree-grid/column-group-selection/column-group-selection.component.html
Labels: grid, keyboard-navigation, status: verified

#1963 Update remote paging sample
  package-lock.json
  package.json
  src/app/grid/grid-remote-paging-sample/remote-paging-sample.component.html
  src/app/grid/grid-remote-paging-sample/remote-paging-sample.component.ts
Labels: status: verified

#1969 Add nmp link to README.md
  README.md
Labels: status: awaiting-test

#1796 Add AOT to LOB application
  angular.json
Labels: status: resolved

#1972 Enhance Boston Marathon sample
  package-lock.json
  projects/app-lob/src/app/grid/grid-boston-marathon/grid.component.html
  projects/app-lob/src/app/grid/grid-boston-marathon/grid.component.scss
  projects/app-lob/src/app/grid/grid-boston-marathon/grid.component.ts
  projects/app-lob/src/app/grid/services/data.ts
Labels: enhancement, status: verified, version: 9.1.x

#1971 Enhance Boston Marathon App
  projects/app-lob/src/app/grid/grid-boston-marathon/grid.component.html
  projects/app-lob/src/app/grid/grid-boston-marathon/grid.component.scss
  projects/app-lob/src/app/grid/grid-boston-marathon/grid.component.ts
  projects/app-lob/src/app/grid/services/data.ts
Labels: enhancement, status: verified, version: 9.0.x

#1961 refactor(circulalr progress bar): improve circular bar samples
  live-editing/configs/CircularProgressbarConfigGenerator.ts
  src/app/data-display/circular-progressbar/circular-dynamic-sample/circular-dynamic-sample.component.html
  src/app/data-display/circular-progressbar/circular-dynamic-sample/circular-dynamic-sample.component.scss
  src/app/data-display/circular-progressbar/circular-dynamic-sample/circular-dynamic-sample.component.ts
  src/app/data-display/circular-progressbar/circular-indeterminate-progressbar/circular-indeterminate-progressbar.component.html
  src/app/data-display/circular-progressbar/circular-indeterminate-progressbar/circular-indeterminate-progressbar.component.scss
  src/app/data-display/circular-progressbar/circular-indeterminate-progressbar/circular-indeterminate-progressbar.component.ts
  src/app/data-display/circular-progressbar/circular-progressbar.component.html
  src/app/data-display/circular-progressbar/circular-progressbar.component.scss
  src/app/data-display/circular-progressbar/circular-progressbar.component.ts
  src/app/data-display/circular-progressbar/circular-styling-sample/circular-styling-sample.component.html
  src/app/data-display/circular-progressbar/circular-styling-sample/circular-styling-sample.component.scss
  src/app/data-display/circular-progressbar/circular-styling-sample/circular-styling-sample.component.ts
  src/app/data-display/data-display-routes-data.ts
  src/app/data-display/data-display-routing.module.ts
  src/app/data-display/data-display.module.ts
Labels: circular-progress, status: verified, version: 9.1.x

#1978 Make filtering ignore case
  projects/app-lob/src/app/grid/grid-boston-marathon/grid.component.ts
Labels: enhancement, status: verified, version: 9.1.x

#1979 Make filtering ignore case
  projects/app-lob/src/app/grid/grid-boston-marathon/grid.component.ts
Labels: enhancement, status: verified, version: 9.0.x

#1980 Update to alpha 13
  package-lock.json
  package.json
Labels: status: verified

#1974 refactor(input-group): improve input group samples
  live-editing/configs/InputGroupConfigGenerator.ts
  src/app/data-entries/data-entries-routes-data.ts
  src/app/data-entries/input-group/input-group-sample-3/input-group-sample-3.component.html
  src/app/data-entries/input-group/input-group-sample-3/input-group-sample-3.component.scss
  src/app/data-entries/input-group/input-group-sample-3/input-group-sample-3.component.ts
  src/app/data-entries/input-group/input-group-sample-4/input-group-sample-4.component.html
  src/app/data-entries/input-group/input-group-sample-4/input-group-sample-4.component.scss
  src/app/data-entries/input-group/input-group-sample-4/input-group-sample-4.component.ts
  src/app/data-entries/input-group/input-group-sample-5/input-group-sample-5.component.html
  src/app/data-entries/input-group/input-group-sample-5/input-group-sample-5.component.scss
  src/app/data-entries/input-group/input-group-sample-5/input-group-sample-5.component.ts
  src/app/data-entries/input-group/input-group-sample-6/input-group-sample-6.component.html
  src/app/data-entries/input-group/input-group-sample-6/input-group-sample-6.component.scss
  src/app/data-entries/input-group/input-group-sample-6/input-group-sample-6.component.ts
  src/app/data-entries/input-group/input-group-styling/input-group-styling.component.html
  src/app/data-entries/input-group/input-group-styling/input-group-styling.component.scss
  src/app/data-entries/input-group/input-group-styling/input-group-styling.component.ts
  src/app/data-entries/input-group/reactive-forms/reactive-forms.component.html
  src/app/data-entries/input-group/reactive-forms/reactive-forms.component.scss
  src/app/data-entries/input-group/reactive-forms/reactive-forms.component.ts
Labels: input-group, refactoring, status: verified, version: 9.1.x

#1986 Use reduce instead of flat operator
  projects/app-lob/src/app/grid/grid-boston-marathon/grid.component.ts
Labels: status: verified

#1985 Use reduce instead of flat operator
  projects/app-lob/src/app/grid/grid-boston-marathon/grid.component.ts
Labels: status: verified

#1984 refactor(icon): improve icon samples
  src/app/data-display/data-display-routing.module.ts
  src/app/data-display/data-display.module.ts
  src/app/data-display/icon/icon-sample-1/icon-sample-1.component.html
  src/app/data-display/icon/icon-sample-1/icon-sample-1.component.scss
  src/app/data-display/icon/icon-sample-1/icon-sample-1.component.ts
  src/app/data-display/icon/icon-sample-2/icon-sample-2.component.html
  src/app/data-display/icon/icon-sample-2/icon-sample-2.component.scss
  src/app/data-display/icon/icon-sample-2/icon-sample-2.component.ts
  src/app/data-display/icon/icon-sample-3/icon-sample-3.component.html
  src/app/data-display/icon/icon-sample-3/icon-sample-3.component.scss
  src/app/data-display/icon/icon-sample-3/icon-sample-3.component.ts
  src/app/data-display/icon/icon-sample-4/icon-sample-4.component.html
  src/app/data-display/icon/icon-sample-4/icon-sample-4.component.scss
  src/app/data-display/icon/icon-sample-4/icon-sample-4.component.ts
  src/app/data-display/icon/icon-sample-5/icon-sample-5.component.html
  src/app/data-display/icon/icon-sample-5/icon-sample-5.component.scss
  src/app/data-display/icon/icon-sample-5/icon-sample-5.component.ts
  src/app/data-display/icon/icon-sample2/icon-sample2.component.html
  src/app/data-display/icon/icon-sample2/icon-sample2.component.ts
  src/app/data-display/icon/icon-styling-sample/icon-styling-sample.component.html
  src/app/data-display/icon/icon-styling-sample/icon-styling-sample.component.scss
  src/app/data-display/icon/icon-styling-sample/icon-styling-sample.component.ts
  src/app/data-display/icon/svg-icon-sample/svg-icon-sample.component.html
  src/app/data-display/icon/svg-icon-sample/svg-icon-sample.component.scss
Labels: icon, refactoring, status: verified, version: 9.1.x

#1988 Fixing IE 11 rendering issue
  projects/app-lob/src/styles.scss
  src/styles.scss
Labels: status: verified

#1990 Fix rendering issue in IE11 (master)
  projects/app-lob/src/styles.scss
  src/styles.scss
Labels: status: verified

#1976 docs(dock-manager): Create dock manager sample
  azure-pipelines.yml
  package-lock.json
  package.json
  src/app/layouts/dock-manager/dock-manager.component.html
  src/app/layouts/dock-manager/dock-manager.component.scss
  src/app/layouts/dock-manager/dock-manager.component.ts
  src/app/layouts/layouts-routes-data.ts
  src/app/layouts/layouts-routing.module.ts
  src/app/layouts/layouts.module.ts
  src/main.ts
Labels: dock manager, status: verified

#1999 chore: updat to 9.1.0-alpha.14
  package-lock.json
  package.json
Labels: status: verified, version: 9.1.x

#1949 Action Strip Samples
  live-editing/configs/ActionStripConfigGenerator.ts
  live-editing/configs/GridConfigGenerator.ts
  live-editing/generators/ConfigGenerators.ts
  src/app/grid/grid-action-strip/grid-action-strip-sample.html
  src/app/grid/grid-action-strip/grid-action-strip-sample.scss
  src/app/grid/grid-action-strip/grid-action-strip-sample.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
  src/app/menus/action-strip/action-strip-paragraph-menu/action-strip-paragraph-menu.component.html
  src/app/menus/action-strip/action-strip-paragraph-menu/action-strip-paragraph-menu.component.scss
  src/app/menus/action-strip/action-strip-paragraph-menu/action-strip-paragraph-menu.component.ts
  src/app/menus/action-strip/action-strip-paragraph-styling/action-strip-paragraph-styling.component.html
  src/app/menus/action-strip/action-strip-paragraph-styling/action-strip-paragraph-styling.component.scss
  src/app/menus/action-strip/action-strip-paragraph-styling/action-strip-paragraph-styling.component.ts
  src/app/menus/action-strip/action-strip-paragraph/action-strip-paragraph.component.html
  src/app/menus/action-strip/action-strip-paragraph/action-strip-paragraph.component.scss
  src/app/menus/action-strip/action-strip-paragraph/action-strip-paragraph.component.ts
  src/app/menus/menus-routes-data.ts
  src/app/menus/menus-routing.module.ts
  src/app/menus/menus.module.ts
Labels: action-strip, status: verified, version: 9.1.x

#1977 Adding text selection directive samples
  live-editing/configs/DateTimeEditorConfigGenerator.ts
  live-editing/configs/InputGroupConfigGenerator.ts
  live-editing/configs/MaskConfigGenerator.ts
  src/app/data-display/data-display.module.ts
  src/app/data-display/mask/mask-sample-1/mask-sample-1.component.html
  src/app/data-display/mask/mask-sample-1/mask-sample-1.component.ts
  src/app/data-entries/data-entries-routes-data.ts
  src/app/data-entries/data-entries-routing.module.ts
  src/app/data-entries/data-entries.module.ts
  src/app/data-entries/input-group/input-text-selection/input-text-selection.component.html
  src/app/data-entries/input-group/input-text-selection/input-text-selection.component.scss
  src/app/data-entries/input-group/input-text-selection/input-text-selection.component.ts
  src/app/scheduling/datetimeeditor/datetime-basic/datetime-basic.component.html
  src/app/scheduling/datetimeeditor/datetime-basic/datetime-basic.component.scss
  src/app/scheduling/scheduling.module.ts
Labels: status: verified

#2014 Update filter combinations in Grid Keyboard Navigation Sample
  src/app/grid/grid-keyboardnav-guide-sample/grid-keyboardnav-sample.component.html
  src/app/grid/grid-keyboardnav-guide-sample/grid-keyboardnav-sample.component.scss
  src/app/grid/grid-keyboardnav-guide-sample/grid-keyboardnav-sample.component.ts
  src/app/hierarchical-grid/hgrid-keybarod-nav-guide-sample/hgrid-keyboard-guide.component.html
  src/app/hierarchical-grid/hgrid-keybarod-nav-guide-sample/hgrid-keyboard-guide.component.scss
  src/app/hierarchical-grid/hgrid-keybarod-nav-guide-sample/hgrid-keyboard-guide.component.ts
  src/app/tree-grid/tgrid-keyboard-guide/tgrid-keyboardnav-guide.component.html
  src/app/tree-grid/tgrid-keyboard-guide/tgrid-keyboardnav-guide.component.scss
  src/app/tree-grid/tgrid-keyboard-guide/tgrid-keyboardnav-guide.component.ts
  src/app/tree-grid/tree-grid-routes-data.ts
Labels: status: verified

#2013 Enhance FinJS sample with KB nav latest changes
  projects/app-lob/src/app/grid-finjs/grid-finjs-demo.component.html
  projects/app-lob/src/app/grid-finjs/grid-finjs-demo.component.ts
Labels: finjs-grid, status: verified, version: 9.1.x

#2011 fix(slider): two-way databound slider inputs
  src/app/interactions/slider/slider-sample-1/slider-sample-1.component.html
  src/app/interactions/slider/slider-sample-1/slider-sample-1.component.ts
  src/app/interactions/slider/slider-sample-3/slider-sample-3.component.html
  src/app/interactions/slider/slider-sample-3/slider-sample-3.component.ts
Labels: slider, status: verified

#1992 Adds fixed height to the MDV sample row detail template
  projects/app-lob/src/app/grid/grid-master-detail/grid-master-detail.component.html
Labels: status: verified, version: 9.0.x

#1993 Adds fixed height to the MDV sample row detail template - 9.1
  projects/app-lob/src/app/grid/grid-master-detail/grid-master-detail.component.html
Labels: status: verified, version: 9.1.x

#2026 fix(igx-date-range-picker): min-max range; value
  src/app/scheduling/daterangepicker/daterangepicker-flight-booking/daterangepicker-flight-booking.ts
  src/app/scheduling/daterangepicker/daterangepicker-mode/daterangepicker-mode.html
Labels: range-date-picker, status: verified, version: 9.1.x

#2019 Closes action strip on scroll
  src/app/grid/grid-action-strip/grid-action-strip-sample.html
  src/app/grid/grid-row-pinning-drag/grid-row-pinning-drag.component.html
  src/app/grid/grid-row-pinning-styling/grid-row-pinning-styling.component.html
  src/app/grid/grid-row-pinning/grid-row-pinning.component.html
  src/app/hierarchical-grid/hierarchical-grid-row-pinning-styling/hierarchical-grid-row-pinning-styling.component.html
  src/app/hierarchical-grid/hierarchical-grid-row-pinning/hierarchical-grid-row-pinning.component.html
  src/app/tree-grid/tree-grid-row-pinning-styling/tree-grid-row-pinning-styling.component.html
  src/app/tree-grid/tree-grid-row-pinning/tree-grid-row-pinning.component.html
Labels: action-strip, status: verified, version: 9.1.x

#2008 Data Analysis sample with dock manager
  package-lock.json
  package.json
  projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/data-analysis-dock-manager.component.html
  projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/data-analysis-dock-manager.component.scss
  projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/data-analysis-dock-manager.component.ts
  projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/dock-slot/dock-slot.component.html
  projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/dock-slot/dock-slot.component.scss
  projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/dock-slot/dock-slot.component.ts
  projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/floating-panes.service.ts
  projects/app-lob/src/app/grid-dynamic-chart-data/directives/chart-integration/chart-integration.directive.ts
  projects/app-lob/src/app/grid-dynamic-chart-data/directives/chart-integration/initializers.ts
  projects/app-lob/src/app/grid-dynamic-chart-data/directives/conditional-formatting/conditional-formatting.directive.ts
  projects/app-lob/src/app/grid-dynamic-chart-data/grid-dynamic-chart-data-routes-data.ts
  projects/app-lob/src/app/grid-dynamic-chart-data/grid-dynamic-chart-data-routing.module.ts
  projects/app-lob/src/app/grid-dynamic-chart-data/grid-dynamic-chart-data.component.html
  projects/app-lob/src/app/grid-dynamic-chart-data/grid-dynamic-chart-data.component.scss
  projects/app-lob/src/app/grid-dynamic-chart-data/grid-dynamic-chart-data.component.ts
  projects/app-lob/src/app/grid-dynamic-chart-data/grid-dynamic-chart-data.module.ts
  projects/app-lob/src/main.ts
Labels: status: verified

#2018 add igxFocus for the custom cell editors
  projects/app-lob/src/app/grid-finjs/grid-finjs-demo.component.html
  projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.html
  src/app/grid/grid-editing-sample/grid-editing-sample.component.html
Labels: status: verified

#1998 Enter key in Custom keyboard navigation samples
  src/app/grid/grid-custom-kb-navigation/grid-custom-kb-navigation-sample.component.ts
  src/app/hierarchical-grid/hierarchical-grid-custom-kb-navigation/hierarchical-grid-custom-kb-navigation-sample.component.ts
  src/app/tree-grid/tree-grid-keyboard-navigation/tree-grid-keyboard-navigation-sample.component.ts
Labels: status: verified

#2032 Simplify and update service to get pages/chunks of data on demand and…
  src/app/grid/grid-sample-5/grid-sample-5.component.html
  src/app/grid/grid-sample-5/grid-sample-5.component.ts
  src/app/grid/grid-sample-5/remote.service.ts
Labels: status: verified

#2017 fix(nav-drawer): samples layout
  src/app/menus/navdrawer/nav-drawer-mini/nav-drawer-mini.component.scss
  src/app/menus/navdrawer/nav-drawer-pin/nav-drawer-pin.component.scss
  src/app/menus/navdrawer/nav-drawer-routing/nav-drawer-routing.component.scss
  src/app/menus/navdrawer/nav-drawer-simple/nav-drawer-simple.component.scss
  src/app/menus/navdrawer/nav-drawer-styling/nav-drawer-styling.component.scss
Labels: navigation drawer, status: verified, version: 9.1.x

#2030 Update MRL keyboard sample
  src/app/grid/grid-mrl-custom-navigation/grid-mrl-custom-navigation.component.ts
Labels: grid, keyboard-navigation, status: verified, version: 9.1.x

#2012 Add dock manager config generator
  live-editing/configs/DockManagerConfigGenerator.ts
  live-editing/configs/core/AppModuleConfig.ts
  live-editing/generators/ConfigGenerators.ts
  live-editing/generators/SampleAssetsGenerator.ts
  live-editing/templates/app.module.ts.template
  package-lock.json
  package.json
  projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/data-analysis-dock-manager.component.scss
  projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/data-analysis-dock-manager.component.ts
  projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/floating-panes.service.ts
  projects/app-lob/src/app/grid-dynamic-chart-data/grid-dynamic-chart-data.component.ts
  projects/app-lob/src/main.ts
  src/app/layouts/dock-manager/dock-manager-sample/dock-manager.component.html
  src/app/layouts/dock-manager/dock-manager-sample/dock-manager.component.scss
  src/app/layouts/dock-manager/dock-manager-sample/dock-manager.component.ts
  src/app/layouts/layouts-routing.module.ts
  src/app/layouts/layouts.module.ts
  src/main.ts
Labels: status: verified

#2034 refactor(*): do not use igx-css-vars
  src/app/data-display/badge/badge-styling-sample/badge-styling-sample.component.scss
  src/app/data-display/circular-progressbar/circular-styling-sample/circular-styling-sample.component.scss
  src/app/data-display/icon/icon-styling-sample/icon-styling-sample.component.scss
  src/app/data-display/linear-progressbar/linear-progressbar-styling-sample/linear-progressbar-styling-sample.component.scss
  src/app/data-entries/buttonGroup/button-group-style/button-group-style.component.scss
  src/app/data-entries/buttons/buttons-style/buttons-style.component.scss
  src/app/data-entries/checkbox/checkbox-styling/checkbox-styling.component.scss
  src/app/data-entries/input-group/input-group-styling/input-group-styling.component.scss
  src/app/data-entries/radio/radio-styling-sample/radio-styling-sample.component.scss
  src/app/data-entries/switch/switch-styling/switch-styling.component.scss
  src/app/grid/column-selection-styles/column-selection-styles.component.scss
  src/app/hierarchical-grid/column-selection-styles/hierarchical-grid-column-selection-styles.component.scss
  src/app/interactions/dialog/dialog-styling-sample/dialog-styling-sample.component.scss
  src/app/interactions/overlay/overlay-styling/overlay-styling.component.scss
  src/app/interactions/ripple/ripple-stying/ripple-styling-sample.component.scss
  src/app/interactions/slider/slider-styling-sample/app-slider-styling.component.scss
  src/app/interactions/tooltip/tooltip-style/tooltip-style.component.scss
  src/app/layouts/avatar/avatar-styling/avatar-styling.component.scss
  src/app/layouts/card/card-styling-sample/card-styling-sample.component.scss
  src/app/layouts/expansion-panel/expansion-styling/expansion-styling.component.scss
  src/app/layouts/splitter/splitter-styling-sample/splitter-styling-sample.component.scss
  src/app/layouts/tabbar/tabbar-style/tabbar-style.component.scss
  src/app/menus/navbar/navbar-style/navbar-style.component.scss
  src/app/menus/navdrawer/nav-drawer-styling/nav-drawer-styling.component.scss
  src/app/notifications/banner/banner-styling/banner-styling.component.scss
  src/app/notifications/snackbar/snackbar-style/snackbar-style.component.scss
  src/app/notifications/toast/toast-style/toast-style.component.scss
  src/app/scheduling/calendar/calendar-styling-sample/calendar-styling-sample.component.scss
  src/app/scheduling/datepicker/datepicker-styling-sample/datepicker-styling-sample.component.scss
  src/app/scheduling/monthpicker/monthpicker-styling/monthpicker-styling.component.scss
  src/app/scheduling/timepicker/timepicker-styling/timepicker-styling.component.scss
  src/app/tree-grid/column-selection-styles/tree-grid-column-selection-style.component.scss
Labels: refactoring, version: 9.1.x

#2007 refactor(chip): improve chip samples
  live-editing/configs/ChipConfigGenerator.ts
  src/app/data-display/chip-styling/chip-styling.component.html
  src/app/data-display/chip-styling/chip-styling.component.scss
  src/app/data-display/chip-styling/chip-styling.component.ts
  src/app/data-display/chip/chip-area-sample/chip-area-sample.component.html
  src/app/data-display/chip/chip-area-sample/chip-area-sample.component.scss
  src/app/data-display/chip/chip-area-sample/chip-area-sample.component.ts
  src/app/data-display/chip/chip-simple/chip-simple.component.html
  src/app/data-display/chip/chip-simple/chip-simple.component.scss
  src/app/data-display/chip/chip-simple/chip-simple.component.ts
  src/app/data-display/chip/chip-styling/chip-styling.component.html
  src/app/data-display/chip/chip-styling/chip-styling.component.scss
  src/app/data-display/chip/chip-styling/chip-styling.component.ts
  src/app/data-display/chip/chip.component.html
  src/app/data-display/chip/chip.component.scss
  src/app/data-display/chip/chip.component.ts
  src/app/data-display/chip/email-filter-pipe.ts
  src/app/data-display/data-display-routes-data.ts
  src/app/data-display/data-display-routing.module.ts
  src/app/data-display/data-display.module.ts
Labels: chip, refactoring, status: awaiting-test, version: 9.1.x

#2050 Fixing media queries in summary sample (master)
  src/app/grid/grid-sample-3/grid-sample-3.component.html
  src/app/grid/grid-sample-3/grid-sample-3.component.scss
  src/app/grid/grid-sample-3/grid-sample-3.component.ts
Labels: status: verified

#2046 update to igniteui-angular@9.1.0-rc.1
  angular.json
  ignite-ui-cli.json
  package-lock.json
  package.json
  src/app/data-display/chip/chip-styling/chip-styling.component.scss
Labels: status: verified, version: 9.1.x

#2044 Update clipboard sample
  src/app/grid/grid-clipboard-operations-sample/grid-clipboard-operations-sample.component.html
Labels: grid, status: verified, version: 9.1.x

#2049 Fixing media queries in summary sample (vNext)
  src/app/grid/grid-sample-3/grid-sample-3.component.html
  src/app/grid/grid-sample-3/grid-sample-3.component.scss
  src/app/grid/grid-sample-3/grid-sample-3.component.ts
Labels: status: verified

#2028 Update filtering template sample
  src/app/grid/grid-filtering-template-sample/grid-filtering-template-sample.component.html
  src/app/grid/grid-filtering-template-sample/grid-filtering-template-sample.component.ts
  src/app/hierarchical-grid/hierarchical-grid-filtering-template/hierarchical-grid-filtering-template.component.html
  src/app/hierarchical-grid/hierarchical-grid-filtering-template/hierarchical-grid-filtering-template.component.ts
  src/app/tree-grid/tree-grid-filtering-template-sample/tree-grid-filtering-template-sample.component.html
  src/app/tree-grid/tree-grid-filtering-template-sample/tree-grid-filtering-template-sample.component.ts
Labels: grid, status: verified, version: 9.1.x

#2045 Update clipboard sample- master
  src/app/grid/grid-clipboard-operations-sample/grid-clipboard-operations-sample.component.html
Labels: grid, status: verified, version: 9.0.x

#2022 Remote paging with batch editing
  live-editing/configs/GridConfigGenerator.ts
  src/app/grid/grid-batchEditing-remotePaging/batch-editing-remote-paging.component.html
  src/app/grid/grid-batchEditing-remotePaging/batch-editing-remote-paging.component.scss
  src/app/grid/grid-batchEditing-remotePaging/batch-editing-remote-paging.component.ts
  src/app/grid/grid-batchEditing-remotePaging/transaction.component.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
Labels: grid, paging, status: verified

#2051 Fix sizing in Master-detail sample.
  projects/app-lob/src/app/grid/grid-master-detail/grid-master-detail.component.html
  projects/app-lob/src/app/grid/grid-master-detail/grid-master-detail.component.ts
Labels: status: verified

#1975 Infinite Scroll Sample
  live-editing/configs/GridConfigGenerator.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grid-sample-5/grid-sample-5.component.html
  src/app/grid/grid-sample-5/grid-sample-5.component.scss
  src/app/grid/grid-sample-5/grid-sample-5.component.ts
  src/app/grid/grid-sample-5/remote.service.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
Labels: grid, status: in-test, version: 9.1.x

#2052 Fix border position for layout config sample.
  src/app/grid/grid-multi-row-layout-configuration/grid-multi-row-layout-configuration.component.scss
Labels: status: verified

#2054 Adding ESF do data analysis dock manager sample
  projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/data-analysis-dock-manager.component.html
  projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/data-analysis-dock-manager.component.scss
  projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/data-analysis-dock-manager.component.ts
  projects/app-lob/src/app/grid-dynamic-chart-data/directives/conditional-formatting/conditional-formatting.directive.ts
Labels: status: verified
