Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2020-12, with the labels that each got.

#2389 Update dockmanager to 1.2.0 beta.7
  package-lock.json
  package.json
Labels: status: verified

#2393 Update dockmanager to 1.2.0 - vnext
  package-lock.json
  package.json
Labels: status: verified

#2394 Update dockmanager to 1.2.0 - master
  package-lock.json
  package.json
Labels: status: verified

#2397 Update lob for ci m
  package-lock.json
  package.json
Labels: status: verified

#2398 Update to 11.0.5
  package-lock.json
  package.json
Labels: status: verified

#2388 Removing CSS support from live editing generation
  gulpfile.js
  live-editing/LiveEditingManager.ts
  live-editing/README.md
  live-editing/generators/Generator.ts
  live-editing/generators/MetaDataGenerator.ts
  live-editing/generators/SampleAssetsGenerator.ts
  live-editing/generators/SharedAssetsGenerator.ts
  live-editing/generators/misc/SharedAssetsFile.ts
  live-editing/generators/misc/StyleSyntax.ts
  live-editing/services/SassCompiler.ts
  live-editing/services/SassJsCompileChecker.ts
  live-editing/templates/angular-css-support.json.template
  live-editing/templates/polyfills.ts.template
  package.json
Labels: status: verified

#2404 refactor(drop-down): include prefix, suffix and divider sample
  live-editing/configs/DropDownConfigGenerator.ts
  src/app/data-entries/dropdown/dropdown-sample-3/dropdown-sample-3.component.html
  src/app/data-entries/dropdown/dropdown-sample-3/dropdown-sample-3.component.scss
  src/app/data-entries/dropdown/dropdown-sample-3/dropdown-sample-3.component.ts
Labels: dropdown, status: verified, version: 11.1.x

#2382 Fix chip samples so that removing a chip does not throw an error
  src/app/data-display/chip/chip-area-sample/chip-area-sample.component.ts
  src/app/data-display/chip/chip-simple/chip-simple.component.ts
  src/app/data-display/chip/chip-styling/chip-styling.component.ts
Labels: chip, status: verified, version: 11.0.x

#2381 Fix chip samples so that removing a chip does not throw an error
  src/app/data-display/chip/chip-area-sample/chip-area-sample.component.ts
  src/app/data-display/chip/chip-simple/chip-simple.component.ts
  src/app/data-display/chip/chip-styling/chip-styling.component.ts
Labels: chip, status: verified, version: 11.0.x

#2399 Remove Css support from LE generation (master)
  gulpfile.js
  live-editing/LiveEditingManager.ts
  live-editing/README.md
  live-editing/generators/Generator.ts
  live-editing/generators/MetaDataGenerator.ts
  live-editing/generators/SampleAssetsGenerator.ts
  live-editing/generators/SharedAssetsGenerator.ts
  live-editing/generators/misc/SharedAssetsFile.ts
  live-editing/generators/misc/StyleSyntax.ts
  live-editing/services/SassCompiler.ts
  live-editing/services/SassJsCompileChecker.ts
  live-editing/templates/angular-css-support.json.template
  live-editing/templates/polyfills.ts.template
  package.json
Labels: status: verified

#2395 Add page title and meta description -vnext
  live-editing/generators/SharedAssetsGenerator.ts
  live-editing/templates/app.component.ts.template
  projects/app-crm/src/app/app.component.ts
  projects/app-lob/src/app/app.component.ts
  projects/app-lob/src/app/grid-dynamic-chart-data/grid-dynamic-chart-data-routes-data.ts
  projects/app-lob/src/app/grid-finjs/grid-finjs-routes-data.ts
  projects/app-lob/src/app/grid/grid-routes-data.ts
  projects/app-lob/src/app/seo.service.ts
  projects/app-lob/src/app/treegrid-finjs/treegrid-finjs-routes-data.ts
Labels: status: verified

#2396 Add page title and meta description -master
  live-editing/generators/SharedAssetsGenerator.ts
  live-editing/templates/app.component.ts.template
  projects/app-crm/src/app/app.component.ts
  projects/app-lob/src/app/app.component.ts
  projects/app-lob/src/app/grid-dynamic-chart-data/grid-dynamic-chart-data-routes-data.ts
  projects/app-lob/src/app/grid-finjs/grid-finjs-routes-data.ts
  projects/app-lob/src/app/grid/grid-routes-data.ts
  projects/app-lob/src/app/seo.service.ts
  projects/app-lob/src/app/treegrid-finjs/treegrid-finjs-routes-data.ts
Labels: status: verified
