Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2020-10, with the labels that each got.

#2266 fix(grid): fix grid width
  src/app/grid/grid-row-drag-base/grid-row-drag-base.component.html
Labels: grid, status: verified, version: 10.1.x

#2265 fix(grid): fix grid width
  src/app/grid/grid-row-drag-base/grid-row-drag-base.component.html
Labels: grid, status: awaiting-test, version: 10.2.x

#2134 Fix navdrawer item indentation and adding ellipsis class and styles from dev demos
  src/app/index/index.component.html
  src/app/index/index.component.scss
Labels: navigation drawer

#2275 Add flat grid add row samples
  live-editing/configs/GridConfigGenerator.ts
  src/app/grid/grid-add-row-sample/grid-add-row-sample.component.html
  src/app/grid/grid-add-row-sample/grid-add-row-sample.component.scss
  src/app/grid/grid-add-row-sample/grid-add-row-sample.component.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
Labels: grid, row-adding, status: verified

#2277 refactor(finjs)Remove template in date column#2255
  projects/app-lob/src/app/grid-finjs/grid-finjs-demo.component.html
Labels: status: verified

#2278 refactor(finjs)Remove template in date column#2255
  projects/app-lob/src/app/grid-finjs/grid-finjs-demo.component.html
Labels: status: verified

#2283 Update to 10.2.0-alpha.7
  angular.json
  e2e/tsconfig.e2e.json
  package-lock.json
  package.json
  projects/app-lob/e2e/tsconfig.json
  projects/app-lob/tsconfig.app.json
  projects/app-lob/tsconfig.spec.json
  src/app/hierarchical-grid/hierarchical-grid-editing-events/hierarchical-grid-editing-events.component.ts
  src/tsconfig.app.json
  src/tsconfig.spec.json
  tsconfig.base.json
  tsconfig.json
Labels: status: verified

#2281 refactor(CRM grid):Fix responsiveness #2271
  projects/app-lob/src/app/grid-crm/grid-crm/grid-crm/grid-crm.component.scss
Labels: status: verified

#2282 refactor(CRM grid):Fix responsiveness #2271
  projects/app-lob/src/app/grid-crm/grid-crm/grid-crm/grid-crm.component.scss
Labels: status: verified

#2285 Adding new finjs sample
  projects/app-lob/src/app/grid-dynamic-chart-data/directives/conditional-formatting/conditional-formatting.directive.ts
  projects/app-lob/src/app/grid-finjs/grid-finjs-routes-data.ts
  projects/app-lob/src/app/grid-finjs/grid-finjs-routing.module.ts
  projects/app-lob/src/app/grid-finjs/grid-finjs.module.ts
  projects/app-lob/src/app/grid-finjs/partial/grid-finjs-partial.component.html
  projects/app-lob/src/app/grid-finjs/partial/grid-finjs-partial.component.scss
  projects/app-lob/src/app/grid-finjs/partial/grid-finjs-partial.component.ts
  src/app/grid/grid-editing-events/grid-editing-events.component.html
  src/app/hierarchical-grid/hierarchical-grid-editing-events/hierarchical-grid-editing-events.component.html
  src/app/tree-grid/tree-grid-editing-events/tree-grid-editing-events.component.html
Labels: status: verified

#2287 Update to 10.2.0-beta.0
  package-lock.json
  package.json
  tsconfig.json
Labels: status: verified

#2273 Add tree grid add row samples
  live-editing/configs/TreeGridConfigGenerator.ts
  src/app/tree-grid/tree-grid-add-row-sample/employee.ts
  src/app/tree-grid/tree-grid-add-row-sample/tree-grid-add-row-sample.component.html
  src/app/tree-grid/tree-grid-add-row-sample/tree-grid-add-row-sample.component.scss
  src/app/tree-grid/tree-grid-add-row-sample/tree-grid-add-row-sample.component.ts
  src/app/tree-grid/tree-grid-routes-data.ts
  src/app/tree-grid/tree-grid-routing.module.ts
  src/app/tree-grid/tree-grid.module.ts
Labels: row-adding, tree-grid

#2276 Add add row samples for HGrid
  live-editing/configs/HierarchicalGridConfigGenerator.ts
  src/app/grid/grid-action-strip/grid-action-strip-sample.html
  src/app/hierarchical-grid/hierarchical-grid-add-row/hierarchical-grid-add-row.component.html
  src/app/hierarchical-grid/hierarchical-grid-add-row/hierarchical-grid-add-row.component.scss
  src/app/hierarchical-grid/hierarchical-grid-add-row/hierarchical-grid-add-row.component.ts
  src/app/hierarchical-grid/hierarchical-grid-routes-data.ts
  src/app/hierarchical-grid/hierarchical-grid-routing.module.ts
  src/app/hierarchical-grid/hierarchical-grid.module.ts
  src/app/tree-grid/tree-grid-add-row-sample/tree-grid-add-row-sample.component.html
Labels: hierarchical-grid, row-adding

#2260 Editing lifecycle samples for tGrid, hGrid and Grid
  live-editing/configs/GridConfigGenerator.ts
  live-editing/configs/HierarchicalGridConfigGenerator.ts
  live-editing/configs/TreeGridConfigGenerator.ts
  src/app/grid/grid-editing-lifecycle-sample/grid-editing-lifecycle.component.html
  src/app/grid/grid-editing-lifecycle-sample/grid-editing-lifecycle.component.scss
  src/app/grid/grid-editing-lifecycle-sample/grid-editing-lifecycle.component.ts
  src/app/grid/grid-routes-data.ts
  src/app/grid/grids-routing.module.ts
  src/app/grid/grids.module.ts
  src/app/hierarchical-grid/hgrid-editing-lifecycle-sample/hgrid-editing-lifecycle.component.html
  src/app/hierarchical-grid/hgrid-editing-lifecycle-sample/hgrid-editing-lifecycle.component.scss
  src/app/hierarchical-grid/hgrid-editing-lifecycle-sample/hgrid-editing-lifecycle.component.ts
  src/app/hierarchical-grid/hierarchical-grid-routes-data.ts
  src/app/hierarchical-grid/hierarchical-grid-routing.module.ts
  src/app/hierarchical-grid/hierarchical-grid.module.ts
  src/app/tree-grid/tgrid-editing-lifecycle-sample/tgrid-editing-lifecycle.component.html
  src/app/tree-grid/tgrid-editing-lifecycle-sample/tgrid-editing-lifecycle.component.scss
  src/app/tree-grid/tgrid-editing-lifecycle-sample/tgrid-editing-lifecycle.component.ts
  src/app/tree-grid/tree-grid-routes-data.ts
  src/app/tree-grid/tree-grid-routing.module.ts
  src/app/tree-grid/tree-grid.module.ts
Labels: status: verified

#2294 chore: update to igniteui-angular@10.2.0-beta.1
  package-lock.json
  package.json
Labels: status: verified, version: 10.2.x

#2298 chore(expansion-panel): run 10.2.0 migrations
  src/app/layouts/expansion-panel/expansion-sample-4/expansion-sample-4.component.ts
Labels: expansion panel, version: 10.2.x

#2288 Change all samples that use mouse events to show/hide action strip
  src/app/grid/grid-action-strip/grid-action-strip-sample.html
  src/app/grid/grid-action-strip/grid-action-strip-sample.ts
  src/app/grid/grid-add-row-sample/grid-add-row-sample.component.html
  src/app/grid/grid-add-row-sample/grid-add-row-sample.component.ts
  src/app/grid/grid-row-pinning-drag/grid-row-pinning-drag.component.html
  src/app/grid/grid-row-pinning-drag/grid-row-pinning-drag.component.ts
  src/app/grid/grid-row-pinning-styling/grid-row-pinning-styling.component.html
  src/app/grid/grid-row-pinning-styling/grid-row-pinning-styling.component.ts
  src/app/grid/grid-row-pinning/grid-row-pinning.component.html
  src/app/grid/grid-row-pinning/grid-row-pinning.component.ts
  src/app/hierarchical-grid/hierarchical-grid-row-pinning-styling/hierarchical-grid-row-pinning-styling.component.html
  src/app/hierarchical-grid/hierarchical-grid-row-pinning-styling/hierarchical-grid-row-pinning-styling.component.ts
  src/app/hierarchical-grid/hierarchical-grid-row-pinning/hierarchical-grid-row-pinning.component.html
  src/app/hierarchical-grid/hierarchical-grid-row-pinning/hierarchical-grid-row-pinning.component.ts
  src/app/tree-grid/tree-grid-row-pinning-styling/tree-grid-row-pinning-styling.component.html
  src/app/tree-grid/tree-grid-row-pinning-styling/tree-grid-row-pinning-styling.component.ts
  src/app/tree-grid/tree-grid-row-pinning/tree-grid-row-pinning.component.html
  src/app/tree-grid/tree-grid-row-pinning/tree-grid-row-pinning.component.ts
Labels: action-strip, grid, hierarchical-grid, status: verified, tree-grid, version: 10.2.x

#2299 chore: update to igniteui-angular@10.2.0-rc.0
  package-lock.json
  package.json
Labels: status: verified, version: 10.2.x

#2296 Create preset overlay settings sample_vNext
  live-editing/configs/OverlayConfigGenerator.ts
  src/app/interactions/interactions-routes-data.ts
  src/app/interactions/interactions-routing.module.ts
  src/app/interactions/interactions.module.ts
  src/app/interactions/overlay/overlay-preset-settings/overlay-preset-settings-sample.component.html
  src/app/interactions/overlay/overlay-preset-settings/overlay-preset-settings-sample.component.scss
  src/app/interactions/overlay/overlay-preset-settings/overlay-preset-settings-sample.component.ts
Labels: overlay, status: verified, version: 10.2.x

#2303 chore: update to rc.1
  package-lock.json
  package.json
Labels: status: verified, version: 10.2.x

#2300 Fix icon name in custom filtering sample
  src/app/grid/grid-custom-filtering/grid-custom-filtering.component.ts
  src/app/hierarchical-grid/hierarchical-grid-filtering/hierarchical-grid-custom-filtering.component.ts
  src/app/tree-grid/tree-grid-filtering-custom-sample/tree-grid-filtering-custom-sample.component.ts
Labels: status: verified, version: 10.2.x

#2301 fix(toast): changing position bug
  src/app/notifications/toast/toast-sample-1/toast-sample-1.component.ts
  src/app/notifications/toast/toast-sample-5/toast-sample-5.component.ts
  src/app/notifications/toast/toast-style/toast-style.component.ts
Labels: status: verified, toast, version: 10.2.x

#2309 Add polyfill for Array.includes()
  projects/app-lob/src/polyfills.ts
  src/polyfills.ts
Labels: status: verified

#2318 Fix git modules target branch for vNext
  .gitmodules
Labels: status: awaiting-test

#2316 Fixing treegrid clipboard interactions errors
  src/app/tree-grid/tree-grid-clipboard-operations-sample/tree-grid-clipboard-operations-sample.component.ts
Labels: status: verified

#2321 Update dock manager to 1.1.0
  package-lock.json
  package.json
Labels: status: verified, version: 10.2.x

#2325 Update dock manager to 1.1.0 - master
  package-lock.json
  package.json
Labels: status: verified

#2322 fix(styles): fixed ESF input text color on filtering styling demos
  src/app/grid/grid-excel-style-filtering-style/grid-excel-style-filtering-style.component.scss
  src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-style/hierarchical-grid-excel-style-filtering-style.component.scss
  src/app/tree-grid/tree-grid-excel-style-filtering-style/tree-grid-excel-style-filtering-style.component.scss
Labels: status: verified

#2320 fix(styles): fixed quick filter input text color on filtering styling demos
  src/app/grid/grid-filtering-style/grid-filtering-style.component.scss
  src/app/hierarchical-grid/hierarchical-grid-filtering-style/hierarchical-grid-filtering-style.component.scss
  src/app/tree-grid/tree-grid-filtering-style/tree-grid-filtering-style.component.scss
Labels: status: verified

#2323 fix(styles): fixed quick filter input text color on filtering styling demos - master
  src/app/grid/grid-filtering-style/grid-filtering-style.component.scss
  src/app/hierarchical-grid/hierarchical-grid-filtering-style/hierarchical-grid-filtering-style.component.scss
  src/app/tree-grid/tree-grid-filtering-style/tree-grid-filtering-style.component.scss
Labels: status: verified

#2324 fix(styles): fixed ESF input text color on filtering styling demos - master
  src/app/grid/grid-excel-style-filtering-style/grid-excel-style-filtering-style.component.scss
  src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-style/hierarchical-grid-excel-style-filtering-style.component.scss
  src/app/tree-grid/tree-grid-excel-style-filtering-style/tree-grid-excel-style-filtering-style.component.scss
Labels: status: verified

#2327 fix(list-sample): set keepItem to true for rightItem pan
  src/app/lists/list/list-sample-7/list-sample-7.component.ts
Labels: list, status: verified

#2313 Add ID field of SINGERS data so that there is no duplication in PK values
  src/app/hierarchical-grid/data.ts
  src/app/hierarchical-grid/hierarchical-grid-add-row/hierarchical-grid-add-row.component.html
  src/app/hierarchical-grid/hierarchical-grid-add-row/hierarchical-grid-add-row.component.ts
  src/app/hierarchical-grid/hierarchical-grid-batch-editing/hierarchical-grid-batch-editing.component.ts
  src/app/hierarchical-grid/hierarchical-grid-editing/hierarchical-grid-editing.component.ts
  src/app/hierarchical-grid/models.ts
Labels: hierarchical-grid, row-adding, status: verified, version: 10.2.x

#2330 Add ID field of SINGERS data so that there is no duplication in PK values
  src/app/hierarchical-grid/data.ts
  src/app/hierarchical-grid/hierarchical-grid-add-row/hierarchical-grid-add-row.component.html
  src/app/hierarchical-grid/hierarchical-grid-add-row/hierarchical-grid-add-row.component.ts
  src/app/hierarchical-grid/hierarchical-grid-batch-editing/hierarchical-grid-batch-editing.component.ts
  src/app/hierarchical-grid/hierarchical-grid-editing/hierarchical-grid-editing.component.ts
  src/app/hierarchical-grid/models.ts
Labels: grid, row-adding, status: verified

#2329 fix(list-sample): set keepItem to true for rightItem pan
  src/app/lists/list/list-sample-7/list-sample-7.component.ts
Labels: list, status: verified

#2333 update(version): Bump up version to 10.2.1 vNext
  package-lock.json
  package.json
Labels: status: verified

#2332 fix(directive): prevent scroll directive now applied to grid tbody - vNext
  src/app/directives/prevent-scroll.directive.ts
Labels: grid, status: verified

#2331 fix(directive): prevent scroll directive now applied to grid tbody - master
  src/app/directives/prevent-scroll.directive.ts
Labels: grid, status: verified
