Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2021-09, with the labels that each got.

#2805 chore(*): DockManager update to 1.6.0-beta.0
  package-lock.json
  package.json
Labels: dock manager

#2768 Add Range Buttons sample
  live-editing/configs/DateRangePickerConfigGenerator.ts
  src/app/scheduling/daterangepicker/daterangepicker-range-buttons/daterangepicker-range-buttons.html
  src/app/scheduling/daterangepicker/daterangepicker-range-buttons/daterangepicker-range-buttons.scss
  src/app/scheduling/daterangepicker/daterangepicker-range-buttons/daterangepicker-range-buttons.ts
  src/app/scheduling/scheduling-routes-data.ts
  src/app/scheduling/scheduling-routing.module.ts
  src/app/scheduling/scheduling.module.ts
Labels: status: verified, date-range-picker, squash-merge

#2807 chore(*): DockManager update to 1.6.0-beta.1
  package-lock.json
  package.json
Labels: dock manager

#2814 feat(i18n): add norwegian (nb) language
  package-lock.json
  package.json
  src/app/services/localization-samples/localization-all-resources/localization-all-resources.component.ts
Labels: i18n, version: 12.2.x

#2815 feat(i18n): add norwegian (nb) language
  package-lock.json
  package.json
  src/app/services/localization-samples/localization-all-resources/localization-all-resources.component.ts
Labels: version: 12.1.x, i18n
