Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2021-03, with the labels that each got.

#2494 Fix errors in the Tree Grid cell selection sample - vNext - 1705
  live-editing/configs/TreeGridConfigGenerator.ts
Labels: status: verified, tree-grid, version: 12.0.x

#2495 Fix errors in the Tree Grid cell selection sample - master - 1705
  live-editing/configs/TreeGridConfigGenerator.ts
Labels: status: verified, tree-grid, version: 11.1.x

#2496 nalipiev/update-11-1-1
  package-lock.json
  package.json
Labels: status: verified, version: 11.1.x

#2497 FinJS sample performance improvements
  package-lock.json
  package.json
  projects/app-lob/src/app/grid-finjs/controllers.component.ts
  projects/app-lob/src/app/grid-finjs/grid-finjs.component.html
  projects/app-lob/src/app/grid-finjs/grid-finjs.component.ts
  projects/app-lob/src/app/grid-finjs/localData.service.ts
  projects/app-lob/src/app/grid-finjs/main.component.scss
  projects/app-lob/src/app/grid-finjs/main.component.ts
Labels: finjs-grid, status: in-test

#2493 Expose RTL support sample -vnext
  live-editing/configs/CalendarConfigGenerator.ts
  src/app/scheduling/calendar/calendar-rtl-sample/calendar-rtl-sample.component.html
  src/app/scheduling/calendar/calendar-rtl-sample/calendar-rtl-sample.component.scss
  src/app/scheduling/calendar/calendar-rtl-sample/calendar-rtl-sample.component.ts
  src/app/scheduling/scheduling-routes-data.ts
  src/app/scheduling/scheduling-routing.module.ts
  src/app/scheduling/scheduling.module.ts
Labels: calendar, status: verified

#2506 Expose RTL support sample -master
  live-editing/configs/CalendarConfigGenerator.ts
  src/app/scheduling/calendar/calendar-rtl-sample/calendar-rtl-sample.component.html
  src/app/scheduling/calendar/calendar-rtl-sample/calendar-rtl-sample.component.scss
  src/app/scheduling/calendar/calendar-rtl-sample/calendar-rtl-sample.component.ts
  src/app/scheduling/scheduling-routes-data.ts
  src/app/scheduling/scheduling-routing.module.ts
  src/app/scheduling/scheduling.module.ts
Labels: calendar, status: verified

#2491 Add i18n sample utilizing i18n package - localize app
  live-editing/configs/LocalizationConfigGenerator.ts
  package-lock.json
  package.json
  src/app/services/localization-samples/localization-all-resources/localization-all-resources.component.html
  src/app/services/localization-samples/localization-all-resources/localization-all-resources.component.scss
  src/app/services/localization-samples/localization-all-resources/localization-all-resources.component.ts
  src/app/services/services-routes-data.ts
  src/app/services/services-routing.module.ts
  src/app/services/services.module.ts
Labels: enhancement, status: verified, version: 12.0.x

#2492 Add i18n sample utilizing i18n package - localize app - 11.1.x
  live-editing/configs/LocalizationConfigGenerator.ts
  package-lock.json
  package.json
  src/app/services/localization-samples/localization-all-resources/localization-all-resources.component.html
  src/app/services/localization-samples/localization-all-resources/localization-all-resources.component.scss
  src/app/services/localization-samples/localization-all-resources/localization-all-resources.component.ts
  src/app/services/services-routes-data.ts
  src/app/services/services-routing.module.ts
  src/app/services/services.module.ts
Labels: enhancement, status: awaiting-test, status: verified, version: 11.1.x

#2509 Update dv packages
  package-lock.json
  package.json
Labels: status: verified

#2511 Change finjs routes - vnext
  live-editing/Routes.ts
  projects/app-lob/src/app/app-routing.module.ts
  projects/app-lob/src/app/index/index.component.ts
  src/app/app-routing.module.ts
Labels: status: verified

#2512 Change finjs routes - master
  live-editing/Routes.ts
  projects/app-lob/src/app/app-routing.module.ts
  projects/app-lob/src/app/index/index.component.ts
  src/app/app-routing.module.ts
Labels: status: verified

#2505 fix(toast): update toast methods names
  src/app/data-entries/dropdown/drop-down-remote-virtual/drop-down-remote.component.ts
  src/app/grid/grid-editing-events/grid-editing-events.component.ts
  src/app/grid/grid-editing-sample/grid-editing-sample.component.ts
  src/app/hierarchical-grid/hierarchical-grid-editing-events/hierarchical-grid-editing-events.component.ts
  src/app/layouts/expansion-panel/expansion-sample-2/expansion-sample-2.component.ts
  src/app/lists/combo/combo-remote/combo-remote.component.ts
  src/app/lists/combo/combo-styling/combo-styling.component.ts
  src/app/lists/list/list-sample-7/list-sample-7.component.ts
  src/app/lists/list/list-sample-8/list-sample-8.component.ts
  src/app/notifications/banner/banner-advanced-sample/banner-advanced-sample.component.ts
  src/app/notifications/banner/banner-styling/banner-styling.component.ts
  src/app/notifications/toast/toast-sample-1/toast-sample-1.component.html
  src/app/notifications/toast/toast-sample-1/toast-sample-1.component.ts
  src/app/notifications/toast/toast-sample-2/toast-sample-2.component.html
  src/app/notifications/toast/toast-sample-3/toast-sample-3.component.html
  src/app/notifications/toast/toast-sample-4/toast-sample-4.component.html
  src/app/notifications/toast/toast-sample-5/toast-sample-5.component.html
  src/app/notifications/toast/toast-sample-5/toast-sample-5.component.ts
  src/app/notifications/toast/toast-style/toast-style.component.html
  src/app/notifications/toast/toast-style/toast-style.component.ts
  src/app/scheduling/timepicker/timepicker-sample-4/timepicker-sample-4.component.ts
  src/app/tree-grid/tree-grid-editing-events/tree-grid-editing-events.component.ts
Labels: status: verified, toast, version: 11.1.x

#2514 fix(toast): update toast methods names
  src/app/data-entries/dropdown/drop-down-remote-virtual/drop-down-remote.component.ts
  src/app/grid/grid-editing-events/grid-editing-events.component.ts
  src/app/grid/grid-editing-sample/grid-editing-sample.component.ts
  src/app/hierarchical-grid/hierarchical-grid-editing-events/hierarchical-grid-editing-events.component.ts
  src/app/layouts/expansion-panel/expansion-sample-2/expansion-sample-2.component.ts
  src/app/lists/combo/combo-remote/combo-remote.component.ts
  src/app/lists/combo/combo-styling/combo-styling.component.ts
  src/app/lists/list/list-sample-7/list-sample-7.component.ts
  src/app/lists/list/list-sample-8/list-sample-8.component.ts
  src/app/notifications/banner/banner-advanced-sample/banner-advanced-sample.component.ts
  src/app/notifications/banner/banner-styling/banner-styling.component.ts
  src/app/notifications/toast/toast-sample-1/toast-sample-1.component.html
  src/app/notifications/toast/toast-sample-1/toast-sample-1.component.ts
  src/app/notifications/toast/toast-sample-2/toast-sample-2.component.html
  src/app/notifications/toast/toast-sample-3/toast-sample-3.component.html
  src/app/notifications/toast/toast-sample-4/toast-sample-4.component.html
  src/app/notifications/toast/toast-sample-5/toast-sample-5.component.html
  src/app/notifications/toast/toast-sample-5/toast-sample-5.component.ts
  src/app/notifications/toast/toast-style/toast-style.component.html
  src/app/notifications/toast/toast-style/toast-style.component.ts
  src/app/scheduling/timepicker/timepicker-sample-4/timepicker-sample-4.component.ts
  src/app/tree-grid/tree-grid-editing-events/tree-grid-editing-events.component.ts
Labels: status: verified, toast, version: 12.0.x

#2516 Fix live editing for Live-data grid - vnext
  live-editing/configs/app-dv-configs/DVGridConfig.ts
Labels: status: verified

#2517 Fix live editing for Live-data grid - master
  live-editing/configs/app-dv-configs/DVGridConfig.ts
  package.json
  projects/app-lob/src/app/grid-finjs/grid-finjs.component.ts
Labels: status: verified

#2525 Update to 11.1.4 - master
  package-lock.json
  package.json
Labels: status: verified

#2526 Update dockmanager to 1.4.0-beta.0
  package-lock.json
  package.json
Labels: status: verified

#2520 tree grid group by ui
  projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.html
  projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.scss
  projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
  projects/app-lob/src/app/treegrid-finjs/tree-grid-group-area.component.html
  projects/app-lob/src/app/treegrid-finjs/tree-grid-group-area.component.scss
  projects/app-lob/src/app/treegrid-finjs/tree-grid-group-area.component.ts
  projects/app-lob/src/app/treegrid-finjs/tree-grid-grouping.pipe.ts
  projects/app-lob/src/app/treegrid-finjs/treegrid-finjs.module.ts
Labels: enhancement, status: verified, tree-grid

#2524 FinJS sample with Dock Manager
  projects/app-lob/src/app/app-routing.module.ts
  projects/app-lob/src/app/grid-finjs-dockManager/grid-finjs-dock-manager-routes-data.ts
  projects/app-lob/src/app/grid-finjs-dockManager/grid-finjs-dock-manager-routing.module.ts
  projects/app-lob/src/app/grid-finjs-dockManager/grid-finjs-dock-manager.component.html
  projects/app-lob/src/app/grid-finjs-dockManager/grid-finjs-dock-manager.component.scss
  projects/app-lob/src/app/grid-finjs-dockManager/grid-finjs-dock-manager.component.ts
  projects/app-lob/src/app/grid-finjs-dockManager/grid-finjs-dock-manager.module.ts
  projects/app-lob/src/app/index/index.component.ts
  projects/app-lob/src/app/services/signal-r.service.ts
  projects/app-lob/src/styles.scss
Labels: finjs-grid, status: verified

#2529 Add config for live editing - master
  live-editing/Routes.ts
  live-editing/configs/app-dv-configs/DVGridConfig.ts
  live-editing/configs/app-dv-configs/DVTreeGridConfig.ts
  package-lock.json
  package.json
  projects/app-lob/src/app/app-routing.module.ts
  projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/data-analysis-dock-manager.component.html
  projects/app-lob/src/app/grid-dynamic-chart-data/grid-dynamic-chart-data.component.html
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager-routes-data.ts
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager-routing.module.ts
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.html
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.scss
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.ts
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.module.ts
  projects/app-lob/src/app/grid-finjs/controllers.component.html
  projects/app-lob/src/app/grid-finjs/controllers.component.ts
  projects/app-lob/src/app/grid-finjs/grid-finjs.component.html
  projects/app-lob/src/app/grid-finjs/grid-finjs.component.scss
  projects/app-lob/src/app/grid-finjs/grid-finjs.component.ts
  projects/app-lob/src/app/grid-finjs/grid-finjs.module.ts
  projects/app-lob/src/app/grid-finjs/localData.service.ts
  projects/app-lob/src/app/grid-finjs/main.component.html
  projects/app-lob/src/app/grid-finjs/main.component.scss
  projects/app-lob/src/app/grid-finjs/main.component.ts
  projects/app-lob/src/app/index/index.component.ts
  projects/app-lob/src/app/services/financialData.ts
  projects/app-lob/src/app/services/signal-r.service.ts
  projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.html
  projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
  projects/app-lob/src/styles.scss
Labels: status: verified

#2532 fix tree grid finjs sample aggregations
  projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
  projects/app-lob/src/app/treegrid-finjs/tree-grid-group-area.component.ts
Labels: status: verified, tree-grid

#2531 Add config for live-editing - vnext
  live-editing/Routes.ts
  live-editing/configs/app-dv-configs/DVGridConfig.ts
  projects/app-lob/src/app/app-routing.module.ts
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager-routes-data.ts
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager-routing.module.ts
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.html
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.scss
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.ts
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.module.ts
  projects/app-lob/src/app/index/index.component.ts
Labels: status: verified

#2536 Fix pinned pane size in finjs with dock manager sample
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.html
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.ts
Labels: status: verified

#2537 Fix pinned pane size in finjs with dock manager sample --master
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.html
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.ts
Labels: status: verified

#2542 FinJS sample with DockManager enhancements
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.html
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.ts
  projects/app-lob/src/app/services/signal-r.service.ts
Labels: status: verified

#2543 FinJS sample with DockManager enhancements --master
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.html
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.ts
  projects/app-lob/src/app/services/signal-r.service.ts
Labels: status: awaiting-test

#2533 Tree grid finjs sample group by - master
  projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.scss
  projects/app-lob/src/app/treegrid-finjs/tree-grid-finjs-sample.component.ts
  projects/app-lob/src/app/treegrid-finjs/tree-grid-group-area.component.html
  projects/app-lob/src/app/treegrid-finjs/tree-grid-group-area.component.scss
  projects/app-lob/src/app/treegrid-finjs/tree-grid-group-area.component.ts
  projects/app-lob/src/app/treegrid-finjs/tree-grid-grouping.pipe.ts
  projects/app-lob/src/app/treegrid-finjs/treegrid-finjs.module.ts
Labels: status: verified

#2544 Fix excel style filtering dialog position
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.html
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.ts
Labels: status: in-test

#2548 Prevent all data update when using local data --vNext
  projects/app-lob/src/app/services/signal-r.service.ts
Labels: status: verified

#2553 Change Dock Manager theme inclusion (vnext)
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.scss
  src/styles.scss
Labels: status: verified

#2554 Change Dock Manager theme inclusion (master)
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.scss
  projects/app-lob/src/styles.scss
Labels: status: awaiting-test

#2546 Enable samples to start with prod -vnext
  angular.json
  package.json
  projects/app-lob/src/main.ts
Labels: status: verified

#2547 Enable samples to start with prod -master
  angular.json
  package.json
Labels: status: verified

#2562 chore(*): update to 11.2 alpha 2
  package-lock.json
  package.json
  projects/app-crm/src/app/grid-crm/grid-crm.component.scss
  projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/data-analysis-dock-manager.component.scss
  projects/app-lob/src/app/grid-dynamic-chart-data/grid-dynamic-chart-data.component.scss
  src/app/data-display/icon/material-icons-extended/material-icons-extended.component.scss
  src/app/data-entries/buttons/buttons-roundness-sample/buttons-roundness-sample.scss
  src/app/data-entries/buttons/buttons-style/buttons-style.component.scss
  src/app/data-entries/dropdown/dropdown-styling/dropdown-styling.component.scss
  src/app/grid/custom-grid-paging-style/custom-grid-paging-style.component.scss
  src/app/grid/grid-advanced-filtering-style/grid-advanced-filtering-style.component.scss
  src/app/grid/grid-column-hiding-toolbar-style/grid-column-hiding-toolbar-style.component.scss
  src/app/grid/grid-editing-style-sample/grid-editing-style-sample.component.scss
  src/app/grid/grid-excel-style-filtering-style/grid-excel-style-filtering-style.component.scss
  src/app/grid/grid-filtering-style/grid-filtering-style.component.scss
  src/app/grid/grid-toolbar-style/grid-toolbar-style.component.scss
  src/app/hierarchical-grid/hierarchical-grid-advanced-filtering-style/hierarchical-grid-advanced-filtering-style.component.scss
  src/app/hierarchical-grid/hierarchical-grid-column-hiding-toolbar-style/hierarchical-grid-column-hiding-toolbar-style.component.scss
  src/app/hierarchical-grid/hierarchical-grid-editing-style/hierarchical-grid-editing-style.component.scss
  src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-style/hierarchical-grid-excel-style-filtering-style.component.scss
  src/app/hierarchical-grid/hierarchical-grid-filtering-style/hierarchical-grid-filtering-style.component.scss
  src/app/hierarchical-grid/hierarchical-grid-paging-style/hierarchical-grid-paging-style.component.scss
  src/app/hierarchical-grid/hierarchical-grid-toolbar-style/hierarchical-grid-toolbar-style.component.scss
  src/app/interactions/dialog/dialog-styling-sample/dialog-styling-sample.component.scss
  src/app/interactions/drag-drop/kanban-sample/kanban-sample.component.scss
  src/app/interactions/drag-drop/list-reorder-sample/list-reorder-sample.component.scss
  src/app/layouts/avatar/avatar-css-variables/avatar-css-variables.component.scss
  src/app/layouts/avatar/avatar-styling/avatar-styling.component.scss
  src/app/layouts/expansion-panel/expansion-styling/expansion-styling.component.scss
  src/app/notifications/banner/banner-sample-4/banner-sample-4.component.scss
  src/app/scheduling/timepicker/timepicker-styling/timepicker-styling.component.scss
  src/app/theming/animations/animations-sample-1/animations-sample-1.component.scss
  src/app/theming/shadows/card-sample-shadow/card-sample-shadow.scss
  src/app/theming/shadows/shadows-sample-1/shadows-sample.component.scss
  src/app/theming/styles/dark-theme-class.scss
  src/app/theming/styles/dark-theme.scss
  src/app/theming/styles/schemas.scss
  src/app/theming/styles/theme-classes.scss
  src/app/theming/styles/themes.scss
  src/app/tree-grid/tree-grid-advanced-filtering-style/tree-grid-advanced-filtering-style.component.scss
  src/app/tree-grid/tree-grid-column-hiding-toolbar-style/tree-grid-column-hiding-toolbar-style.component.scss
  src/app/tree-grid/tree-grid-editing-style/tree-grid-editing-sample.component.scss
  src/app/tree-grid/tree-grid-excel-style-filtering-style/tree-grid-excel-style-filtering-style.component.scss
  src/app/tree-grid/tree-grid-filtering-style/tree-grid-filtering-style.component.scss
  src/app/tree-grid/tree-grid-paging-style/tree-grid-paging-style-sample.component.scss
  src/app/tree-grid/tree-grid-toolbar-style/tree-grid-toolbar-style.component.scss
  src/styles.scss
Labels: status: verified
