Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2021-01, with the labels that each got.

#2413 chore(radio-group): add vertical alignment sample
  live-editing/configs/RadioConfigGenerator.ts
  package-lock.json
  package.json
  src/app/data-entries/data-entries-routes-data.ts
  src/app/data-entries/data-entries-routing.module.ts
  src/app/data-entries/data-entries.module.ts
  src/app/data-entries/radio/radio-group-sample/radio-group-sample.component.html
  src/app/data-entries/radio/radio-group-sample/radio-group-sample.component.scss
  src/app/data-entries/radio/radio-group-vertical/radio-group-vertical.component.html
  src/app/data-entries/radio/radio-group-vertical/radio-group-vertical.component.scss
  src/app/data-entries/radio/radio-group-vertical/radio-group-vertical.component.ts
Labels: radio, version: 11.1.x

#2403 Update library version to 11.0.9 - master
  package-lock.json
  package.json
Labels: status: verified

#2411 Add OG properties -vnext
  projects/app-lob/src/app/app.component.ts
  projects/app-lob/src/app/seo.service.ts
Labels: status: verified

#2412 Add OG properties -master
  projects/app-lob/src/app/app.component.ts
  projects/app-lob/src/app/seo.service.ts
Labels: status: verified

#2415 Formatting app.module.ts live editing output file
  live-editing/generators/SampleAssetsGenerator.ts
  live-editing/templates/app.module.ts.template
Labels: status: verified

#2417 format app module ts file ngImports (live-editing master)
  live-editing/generators/SampleAssetsGenerator.ts
  live-editing/templates/app.module.ts.template
Labels: status: verified

#2422 Fix heights on FinJS
  projects/app-lob/src/app/grid-finjs/grid-finjs.component.scss
  projects/app-lob/src/app/grid-finjs/main.component.scss
  projects/app-lob/src/app/grid-finjs/main.component.ts
Labels: status: awaiting-test

#2419 Add og:title and meta desc to CRM vnext
  projects/app-crm/src/app/app.component.ts
Labels: SEO

#2427 Substituting the FormControl() call with ["", Validators.required]
  src/app/data-entries/input-group/reactive-forms/reactive-forms.component.ts
Labels: input, input-group, status: verified

#2426 Substituting the FormControl() call with ["", Validators.required],
  src/app/data-entries/input-group/reactive-forms/reactive-forms.component.ts
Labels: input, input-group, status: verified

#2420 Add og:title and meta desc to CRM master
  projects/app-crm/src/app/app.component.ts
Labels: SEO, status: verified

#2421 fix(theming): missing components roundness sample
  live-editing/configs/ButtonConfigGenerator.ts
  src/app/data-entries/buttons/buttons-roundness-sample/buttons-roundness-sample.html
  src/app/data-entries/buttons/buttons-roundness-sample/buttons-roundness-sample.scss
  src/app/data-entries/buttons/buttons-roundness-sample/buttons-roundness-sample.ts
  src/app/data-entries/data-entries-routes-data.ts
  src/app/data-entries/data-entries-routing.module.ts
  src/app/data-entries/data-entries.module.ts
Labels: status: verified, version: 11.0.x

#2433 fix(theming): missing components roundness sample
  live-editing/configs/ButtonConfigGenerator.ts
  src/app/data-entries/buttons/buttons-roundness-sample/buttons-roundness-sample.html
  src/app/data-entries/buttons/buttons-roundness-sample/buttons-roundness-sample.scss
  src/app/data-entries/buttons/buttons-roundness-sample/buttons-roundness-sample.ts
  src/app/data-entries/data-entries-routes-data.ts
  src/app/data-entries/data-entries-routing.module.ts
  src/app/data-entries/data-entries.module.ts
Labels: status: verified, version: 11.1.x

#2418 chore(theming): add animations sample
  live-editing/configs/ThemingConfigGenerator.ts
  src/app/theming/animations/animations-sample-1/animations-sample-1.component.html
  src/app/theming/animations/animations-sample-1/animations-sample-1.component.scss
  src/app/theming/animations/animations-sample-1/animations-sample-1.component.ts
  src/app/theming/animations/animations-sample-2/animations-sample-2.component.html
  src/app/theming/animations/animations-sample-2/animations-sample-2.component.scss
  src/app/theming/animations/animations-sample-2/animations-sample-2.component.ts
  src/app/theming/theming-routes-data.ts
  src/app/theming/theming-routing.module.ts
  src/app/theming/theming.module.ts
Labels: status: awaiting-test, styling, version: 11.1.x

#2432 Update dockmanager to 1.3.0-beta.0
  package-lock.json
  package.json
  src/app/layouts/dock-manager/dock-manager-sample/dock-manager.component.html
  src/app/layouts/dock-manager/dock-manager-sample/dock-manager.component.ts
Labels: status: verified

#2436 refactor(igx-dialog): samples
  projects/app-lob/src/app/grid-finjs/main.component.html
  src/app/grid/grid-editing-sample/grid-editing-sample.component.scss
  src/app/grid/grid-row-drag/planet/planet.component.scss
  src/app/hierarchical-grid/hierarchical-grid-batch-editing/hierarchical-grid-batch-editing.component.scss
  src/app/hierarchical-grid/hierarchical-grid-editing/hierarchical-grid-editing.component.scss
  src/app/interactions/dialog/dialog-sample-3/dialog-sample-3.component.html
  src/app/interactions/dialog/dialog-sample-3/dialog-sample-3.component.scss
  src/app/interactions/dialog/dialog-styling-sample/dialog-styling-sample.component.scss
  src/app/theming/default-theme-sample/default-theme-sample.component.scss
  src/app/tree-grid/tree-grid-editing-sample/tree-grid-editing-sample.component.scss
Labels: dialog, status: awaiting-test, styling, version: 11.0.x

#2435 refactor(igx-dialog) samples
  projects/app-lob/src/app/grid-finjs/main.component.html
  src/app/grid/grid-editing-sample/grid-editing-sample.component.scss
  src/app/grid/grid-row-drag/planet/planet.component.scss
  src/app/hierarchical-grid/hierarchical-grid-batch-editing/hierarchical-grid-batch-editing.component.scss
  src/app/hierarchical-grid/hierarchical-grid-editing/hierarchical-grid-editing.component.scss
  src/app/interactions/dialog/dialog-sample-3/dialog-sample-3.component.html
  src/app/interactions/dialog/dialog-sample-3/dialog-sample-3.component.scss
  src/app/interactions/dialog/dialog-styling-sample/dialog-styling-sample.component.scss
  src/app/theming/default-theme-sample/default-theme-sample.component.scss
  src/app/tree-grid/tree-grid-editing-sample/tree-grid-editing-sample.component.scss
Labels: dialog, status: awaiting-test, styling, version: 11.1.x

#2441 Fix one pixel misalignment - vNext
  projects/app-crm/src/app/grid-crm/grid-crm.component.scss
Labels: status: verified

#2447 Fix applying dark theme on finjs sample
  projects/app-lob/src/app/grid-finjs/main.component.html
  projects/app-lob/src/app/grid-finjs/main.component.ts
Labels: status: verified

#2446 Fix applying dark theme on finjs sample
  projects/app-lob/src/app/grid-finjs/main.component.html
  projects/app-lob/src/app/grid-finjs/main.component.ts
Labels: status: in-test, version: 11.1.x

#2449 Update dock manager to 1.3.0
  package-lock.json
  package.json
Labels: status: verified

#2450 Update dock manager to 1.3.0 - master
  package-lock.json
  package.json
Labels: status: verified

#2451 samples(dockmanager): add more tabs
  src/app/layouts/dock-manager/dock-manager-sample/dock-manager.component.html
  src/app/layouts/dock-manager/dock-manager-sample/dock-manager.component.ts
Labels: status: verified

#2443 Refactor samples with new toolbar -vnext
  projects/app-lob/src/app/grid-finjs/grid-finjs.component.html
  projects/app-lob/src/app/tree-grid/tree-grid-childdatakey-sample/tree-grid-childdatakey-sample.component.html
  src/app/grid/grid-column-hiding-toolbar-sample/grid-column-hiding-toolbar-sample.component.html
  src/app/grid/grid-column-hiding-toolbar-style/grid-column-hiding-toolbar-style.component.html
  src/app/grid/grid-excel-style-filtering-load-on-demand/grid-excel-style-filtering-load-on-demand.component.html
  src/app/grid/grid-excel-style-filtering-sample-1/grid-excel-style-filtering-sample-1.component.html
  src/app/grid/grid-excel-style-filtering-sample-2/grid-excel-style-filtering-sample-2.component.html
  src/app/grid/grid-excel-style-filtering-sample-3/grid-excel-style-filtering-sample-3.component.html
  src/app/grid/grid-external-excel-style-filtering/grid-external-excel-style-filtering.component.html
  src/app/grid/grid-external-outlet-sample/grid-external-outlet-sample.component.html
  src/app/grid/grid-groupby-summary-styling-sample/grid-groupby-summary-styling-sample.component.html
  src/app/grid/grid-multi-row-layout/grid-multi-row-layout.component.html
  src/app/grid/grid-sample-pinning/grid-toolbar-pinning.component.html
  src/app/grid/grid-sample-right-pinning/grid-right-pinning.component.html
  src/app/grid/grid-save-state/grid-state.component.html
  src/app/grid/grid-sorting-sample/grid-sorting-sample.component.html
  src/app/hierarchical-grid/hierarchical-grid-column-hiding-toolbar-style/hierarchical-grid-column-hiding-toolbar-style.component.html
  src/app/hierarchical-grid/hierarchical-grid-column-hiding/hierarchical-grid-hiding.component.html
  src/app/hierarchical-grid/hierarchical-grid-column-pinning/hierarchical-grid-toolbar-pinning.component.html
  src/app/hierarchical-grid/hierarchical-grid-custom-kb-navigation/hierarchical-grid-custom-kb-navigation-sample.component.html
  src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-load-on-demand/hierarchical-grid-excel-style-filtering-load-on-demand.component.html
  src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-sample-1/hierarchical-grid-excel-style-filtering-sample-1.component.html
  src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-sample-2/hierarchical-grid-excel-style-filtering-sample-2.component.html
  src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-sample-3/hierarchical-grid-excel-style-filtering-sample-3.component.html
  src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-style/hierarchical-grid-excel-style-filtering-style.component.html
  src/app/hierarchical-grid/hierarchical-grid-external-excel-style-filtering/hierarchical-grid-external-excel-style-filtering.component.html
  src/app/hierarchical-grid/hierarchical-grid-external-outlet/hierarchical-grid-external-outlet-sample.component.html
  src/app/hierarchical-grid/hierarchical-grid-sample-right-pinning/hierarchical-grid-right-pinning.component.html
  src/app/hierarchical-grid/hierarchical-grid-save-state/hGrid-state.component.html
  src/app/tree-grid/tree-grid-column-hiding-toolbar-sample/tree-grid-column-hiding-toolbar-sample.component.html
  src/app/tree-grid/tree-grid-column-hiding-toolbar-style/tree-grid-column-hiding-toolbar-style.component.html
  src/app/tree-grid/tree-grid-column-pinning-sample/tree-grid-toolbar-pinning.component.html
  src/app/tree-grid/tree-grid-employees-sample/tree-grid-employees-sample.component.html
  src/app/tree-grid/tree-grid-excel-style-filtering-load-on-demand/tree-grid-excel-style-filtering-load-on-demand.component.html
  src/app/tree-grid/tree-grid-excel-style-filtering-sample-1/tree-grid-excel-style-filtering-sample-1.component.html
  src/app/tree-grid/tree-grid-excel-style-filtering-sample-2/tree-grid-excel-style-filtering-sample-2.component.html
  src/app/tree-grid/tree-grid-excel-style-filtering-sample-3/tree-grid-excel-style-filtering-sample-3.component.html
  src/app/tree-grid/tree-grid-external-outlet/tree-grid-external-outlet-sample.component.html
  src/app/tree-grid/tree-grid-keyboard-navigation/tree-grid-keyboard-navigation-sample.component.html
  src/app/tree-grid/tree-grid-multi-row-drag/tree-grid-multi-row-drag.component.html
  src/app/tree-grid/tree-grid-row-drag-base/tree-grid-row-drag-base.component.html
  src/app/tree-grid/tree-grid-row-drag/tree-grid-row-drag.component.html
  src/app/tree-grid/tree-grid-row-edit-style/tree-grid-row-edit-style.component.html
  src/app/tree-grid/tree-grid-row-edit/tree-grid-row-editing-sample.component.html
  src/app/tree-grid/tree-grid-sample-right-pinning/tree-grid-right-pinning.component.html
  src/app/tree-grid/tree-grid-save-state/tGrid-state.component.html
Labels: status: verified, toolbar

#2444 Refactor samples with new toolbar -master
  projects/app-lob/src/app/grid-finjs/grid-finjs.component.html
  projects/app-lob/src/app/tree-grid/tree-grid-childdatakey-sample/tree-grid-childdatakey-sample.component.html
  src/app/grid/grid-column-hiding-toolbar-sample/grid-column-hiding-toolbar-sample.component.html
  src/app/grid/grid-column-hiding-toolbar-style/grid-column-hiding-toolbar-style.component.html
  src/app/grid/grid-excel-style-filtering-load-on-demand/grid-excel-style-filtering-load-on-demand.component.html
  src/app/grid/grid-excel-style-filtering-sample-1/grid-excel-style-filtering-sample-1.component.html
  src/app/grid/grid-excel-style-filtering-sample-2/grid-excel-style-filtering-sample-2.component.html
  src/app/grid/grid-excel-style-filtering-sample-3/grid-excel-style-filtering-sample-3.component.html
  src/app/grid/grid-external-excel-style-filtering/grid-external-excel-style-filtering.component.html
  src/app/grid/grid-external-outlet-sample/grid-external-outlet-sample.component.html
  src/app/grid/grid-groupby-summary-styling-sample/grid-groupby-summary-styling-sample.component.html
  src/app/grid/grid-multi-row-layout/grid-multi-row-layout.component.html
  src/app/grid/grid-sample-pinning/grid-toolbar-pinning.component.html
  src/app/grid/grid-sample-right-pinning/grid-right-pinning.component.html
  src/app/grid/grid-save-state/grid-state.component.html
  src/app/grid/grid-sorting-sample/grid-sorting-sample.component.html
  src/app/hierarchical-grid/hierarchical-grid-column-hiding-toolbar-style/hierarchical-grid-column-hiding-toolbar-style.component.html
  src/app/hierarchical-grid/hierarchical-grid-column-hiding/hierarchical-grid-hiding.component.html
  src/app/hierarchical-grid/hierarchical-grid-column-pinning/hierarchical-grid-toolbar-pinning.component.html
  src/app/hierarchical-grid/hierarchical-grid-custom-kb-navigation/hierarchical-grid-custom-kb-navigation-sample.component.html
  src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-load-on-demand/hierarchical-grid-excel-style-filtering-load-on-demand.component.html
  src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-sample-1/hierarchical-grid-excel-style-filtering-sample-1.component.html
  src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-sample-2/hierarchical-grid-excel-style-filtering-sample-2.component.html
  src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-sample-3/hierarchical-grid-excel-style-filtering-sample-3.component.html
  src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-style/hierarchical-grid-excel-style-filtering-style.component.html
  src/app/hierarchical-grid/hierarchical-grid-external-excel-style-filtering/hierarchical-grid-external-excel-style-filtering.component.html
  src/app/hierarchical-grid/hierarchical-grid-external-outlet/hierarchical-grid-external-outlet-sample.component.html
  src/app/hierarchical-grid/hierarchical-grid-sample-right-pinning/hierarchical-grid-right-pinning.component.html
  src/app/hierarchical-grid/hierarchical-grid-save-state/hGrid-state.component.html
  src/app/tree-grid/tree-grid-column-hiding-toolbar-sample/tree-grid-column-hiding-toolbar-sample.component.html
  src/app/tree-grid/tree-grid-column-hiding-toolbar-style/tree-grid-column-hiding-toolbar-style.component.html
  src/app/tree-grid/tree-grid-column-pinning-sample/tree-grid-toolbar-pinning.component.html
  src/app/tree-grid/tree-grid-employees-sample/tree-grid-employees-sample.component.html
  src/app/tree-grid/tree-grid-excel-style-filtering-load-on-demand/tree-grid-excel-style-filtering-load-on-demand.component.html
  src/app/tree-grid/tree-grid-excel-style-filtering-sample-1/tree-grid-excel-style-filtering-sample-1.component.html
  src/app/tree-grid/tree-grid-excel-style-filtering-sample-2/tree-grid-excel-style-filtering-sample-2.component.html
  src/app/tree-grid/tree-grid-excel-style-filtering-sample-3/tree-grid-excel-style-filtering-sample-3.component.html
  src/app/tree-grid/tree-grid-external-outlet/tree-grid-external-outlet-sample.component.html
  src/app/tree-grid/tree-grid-keyboard-navigation/tree-grid-keyboard-navigation-sample.component.html
  src/app/tree-grid/tree-grid-multi-row-drag/tree-grid-multi-row-drag.component.html
  src/app/tree-grid/tree-grid-row-drag-base/tree-grid-row-drag-base.component.html
  src/app/tree-grid/tree-grid-row-drag/tree-grid-row-drag.component.html
  src/app/tree-grid/tree-grid-row-edit-style/tree-grid-row-edit-style.component.html
  src/app/tree-grid/tree-grid-row-edit/tree-grid-row-editing-sample.component.html
  src/app/tree-grid/tree-grid-sample-right-pinning/tree-grid-right-pinning.component.html
  src/app/tree-grid/tree-grid-save-state/tGrid-state.component.html
Labels: status: verified, toolbar

#2453 do nothing if dragged row and targeted row are same
  src/app/tree-grid/tree-grid-row-reorder/tree-grid-row-reorder.component.ts
Labels: row-drag, status: verified, version: 11.1.x

#2438 chore(avatar): css-variables-usage-sample
  live-editing/configs/AvatarConfigGenerator.ts
  src/app/layouts/avatar/avatar-css-variables/avatar-css-variables.component.html
  src/app/layouts/avatar/avatar-css-variables/avatar-css-variables.component.scss
  src/app/layouts/avatar/avatar-css-variables/avatar-css-variables.component.ts
  src/app/layouts/layouts-routes-data.ts
  src/app/layouts/layouts-routing.module.ts
  src/app/layouts/layouts.module.ts
Labels: avatar, status: awaiting-test, theming, version: 11.1.x

#2448 do nothing if dragged row and targeted row are same
  src/app/tree-grid/tree-grid-row-reorder/tree-grid-row-reorder.component.ts
Labels: row-drag, status: verified, version: 11.0.x
