Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2023-02, with the labels that each got.

#3254 build(ci): test without always-auth option
  azure-pipelines.yml
Labels: squash-merge

#3257 fix(grid height): add height to grid and light-dark mode
  src/app/grid/grid-sample-pinning/grid-toolbar-pinning.component.html
  src/app/grid/grid-sample-pinning/grid-toolbar-pinning.component.ts
  src/app/hierarchical-grid/hierarchical-grid-column-pinning/hierarchical-grid-toolbar-pinning.component.html
  src/app/hierarchical-grid/hierarchical-grid-column-pinning/hierarchical-grid-toolbar-pinning.component.scss
  src/app/hierarchical-grid/hierarchical-grid-column-pinning/hierarchical-grid-toolbar-pinning.component.ts
  src/app/tree-grid/tree-grid-column-pinning-sample/tree-grid-toolbar-pinning.component.html
  src/app/tree-grid/tree-grid-column-pinning-sample/tree-grid-toolbar-pinning.component.ts
Labels: status: verified, pinning, hierarchical-grid

#3258 fix(hierarchical grid): add richer data and a few new columns
  src/app/data/hierarchical-data.ts
  src/app/grid/grid-sample-pinning/grid-toolbar-pinning.component.html
  src/app/grid/grid-sample-pinning/grid-toolbar-pinning.component.ts
  src/app/hierarchical-grid/hierarchical-grid-column-pinning/hierarchical-grid-toolbar-pinning.component.html
  src/app/hierarchical-grid/hierarchical-grid-column-pinning/hierarchical-grid-toolbar-pinning.component.ts
  src/app/tree-grid/tree-grid-column-pinning-sample/tree-grid-toolbar-pinning.component.html
  src/app/tree-grid/tree-grid-column-pinning-sample/tree-grid-toolbar-pinning.component.ts
Labels: status: awaiting-test

#3248 fix(combo): remove duplicate igx-combo in template sample
  src/app/lists/combo/combo-template/combo-template.component.html
Labels: status: verified
