Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2023-05, with the labels that each got.

#3304 feat(*): updating to angular 16
  .eslintrc.json
  .github/workflows/build-app-crm.yml
  .github/workflows/build-app-lob.yml
  azure-pipelines.yml
  package-lock.json
  package.json
  projects/app-crm/src/app/app.module.ts
  projects/app-lob/src/app/app.module.ts
  projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/data-analysis-dock-manager.component.html
  projects/app-lob/src/app/grid-dynamic-chart-data/grid-dynamic-chart-data.component.html
  projects/app-lob/src/app/grid-dynamic-chart-data/grid-dynamic-chart-data.module.ts
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.html
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.module.ts
  projects/app-lob/src/app/grid-finjs/grid-finjs.component.html
  projects/app-lob/src/app/grid-finjs/grid-finjs.module.ts
  projects/app-lob/src/app/treegrid-finjs/treegrid-finjs.module.ts
  src/app/directives/prevent-scroll.directive.ts
  src/app/grid/grid-action-strip/grid-action-strip-sample.html
  src/app/grid/grid-row-pinning-drag/grid-row-pinning-drag.component.html
  src/app/grid/grid-row-pinning-extra-column/grid-row-pinning-extra-column.component.html
  src/app/grid/grid-sample-2/grid-sample-2.component.html
  src/app/grid/grid-sample-selection-template-excel/grid-sample-selection-template-excel.component.html
  src/app/grid/grid-sample-selection-template-numbers/grid-sample-selection-template-numbers.component.html
  src/app/grid/grid-sample-selection/grid-selection.component.html
  src/app/grid/grid-state-persistence-sample/grid-state-persistance-sample.component.html
  src/app/grid/grids.module.ts
  src/app/hierarchical-grid/hierarchical-grid-editing-events/hierarchical-grid-editing-events.component.ts
  src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-sample-1/hierarchical-grid-excel-style-filtering-sample-1.component.html
  src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-sample-2/hierarchical-grid-excel-style-filtering-sample-2.component.html
  src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-sample-3/hierarchical-grid-excel-style-filtering-sample-3.component.html
  src/app/hierarchical-grid/hierarchical-grid-excel-style-filtering-style/hierarchical-grid-excel-style-filtering-style.component.html
  src/app/hierarchical-grid/hierarchical-grid-external-excel-style-filtering/hierarchical-grid-external-excel-style-filtering.component.html
  src/app/hierarchical-grid/hierarchical-grid-external-outlet/hierarchical-grid-external-outlet-sample.component.html
  src/app/hierarchical-grid/hierarchical-grid-row-pinning-extra-column/hierarchical-grid-row-pinning-extra-column.component.html
  src/app/hierarchical-grid/hierarchical-grid.module.ts
  src/app/pivot-grid/pivot-grids.module.ts
  src/app/scheduling/calendar/calendar-sample-3/calendar-sample-3.component.ts
  src/app/scheduling/datepicker/datepicker-sample-8/datepicker-sample-8.component.ts
  src/app/services/services.module.ts
  src/app/tree-grid/tree-grid-virtualization-sample/tree-grid-virtualization-sample.component.html
  src/app/tree-grid/tree-grid.module.ts
Labels: status: verified

#3312 fix(simple-combo): add live editing config
  live-editing/configs/ComboConfigGenerator.ts
Labels: status: verified, simple-combo

#3313 16 rc bump
  package-lock.json
  package.json
  projects/app-lob/src/app/grid-dynamic-chart-data/data-analysis-dock-manager/data-analysis-dock-manager.component.ts
  src/app/grid/custom-grid-paging-style/custom-grid-paging-style.component.html
  src/app/grid/grid-keyboardnav-guide-sample/grid-keyboardnav-sample.component.ts
  src/app/hierarchical-grid/hgrid-keybarod-nav-guide-sample/hgrid-keyboard-guide.component.ts
  src/app/hierarchical-grid/hierarchical-grid-pager-sample/hierarchical-grid-pager-sample.component.html
  src/app/hierarchical-grid/hierarchical-grid-paging/hierarchical-grid-paging.component.html
  src/app/tree-grid/tgrid-keyboard-guide/tgrid-keyboardnav-guide.component.ts
  src/app/tree-grid/tree-grid-column-moving-sample/tree-grid-column-moving-sample.component.html
  src/app/tree-grid/tree-grid-pager-sample/tree-grid-pager-sample.component.html
Labels: status: in-test

#3319 chore(*): updating vnext deps to 16.0.0
  package-lock.json
  package.json
Labels: status: verified

#3316 fix(sorting): initial sort in AfterViewInit
  src/app/grid/grid-sorting-sample/grid-sorting-sample.component.ts
  src/app/tree-grid/tree-grid-sorting-sample/tree-grid-sorting-sample.component.ts
Labels: status: awaiting-test, grid, tree-grid

#3310 Set non-zero default value
  src/app/data-display/linear-progressbar/linear-dynamic-sample/linear-dynamic-sample.component.ts
Labels: status: verified, linear-progress

#3323 chore(*): update live editing package -vnext
  package-lock.json
  package.json
Labels: status: verified

#3325 chore(*): fix sample configs
  live-editing/configs/AccordionConfigGenerator.ts
  live-editing/configs/BannerConfigGenerator.ts
  live-editing/configs/CardConfigGenerator.ts
  live-editing/configs/DateRangePickerConfigGenerator.ts
  live-editing/configs/GridConfigGenerator.ts
  live-editing/configs/NavbarConfigGenerator.ts
  projects/app-lob/src/assets/images/carousel/ignite-ui-angular-charts.png
  projects/app-lob/src/assets/images/carousel/ignite-ui-angular-indigo-design.png
  projects/app-lob/src/assets/images/carousel/slider-image-chart.png
  projects/app-lob/src/assets/images/stepper/card-blue.png
  projects/app-lob/src/assets/images/stepper/card-gold.png
  projects/app-lob/src/assets/images/stepper/card-red.png
  src/app/layouts/carousel/carousel-animations-sample/carousel-animations-sample.component.html
  src/app/layouts/carousel/carousel-animations-sample/carousel-animations-sample.component.scss
Labels: status: verified

#3326 fix(dock-manager): change outlet's class when the theme is toggled
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.html
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.scss
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.module.ts
  projects/app-lob/src/styles.scss
Labels: status: verified

#3327 Updating PROD with latest fix and enhacements
  live-editing/configs/AccordionConfigGenerator.ts
  live-editing/configs/BannerConfigGenerator.ts
  live-editing/configs/CardConfigGenerator.ts
  live-editing/configs/DateRangePickerConfigGenerator.ts
  live-editing/configs/GridConfigGenerator.ts
  live-editing/configs/NavbarConfigGenerator.ts
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.html
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.component.scss
  projects/app-lob/src/app/grid-finjs-dock-manager/grid-finjs-dock-manager.module.ts
  projects/app-lob/src/assets/images/carousel/ignite-ui-angular-charts.png
  projects/app-lob/src/assets/images/carousel/ignite-ui-angular-indigo-design.png
  projects/app-lob/src/assets/images/carousel/slider-image-chart.png
  projects/app-lob/src/assets/images/stepper/card-blue.png
  projects/app-lob/src/assets/images/stepper/card-gold.png
  projects/app-lob/src/assets/images/stepper/card-red.png
  projects/app-lob/src/styles.scss
  src/app/layouts/carousel/carousel-animations-sample/carousel-animations-sample.component.html
  src/app/layouts/carousel/carousel-animations-sample/carousel-animations-sample.component.scss
Labels: enhancement, status: verified, version: 16.0.x

#3308 refactor(combo): add groupKey and igxComboHeaderItem template
  src/app/lists/combo/combo-template/combo-template.component.html
  src/app/lists/combo/combo-template/combo-template.component.scss
Labels: status: verified, combo
