Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2024-06, with the labels that each got.

#3481 fix(grid-sample): custom button theme issue
  src/app/grid/custom-grid-paging-style/custom-grid-paging-style.component.scss
Labels: status: awaiting-test, styling, icon-button, 18.0.x

#3485 fix calendar samples
  src/app/scheduling/calendar/calendar-days-view/calendar-days-view.component.scss
  src/app/scheduling/calendar/calendar-months-view/calendar-months-view.component.scss
  src/app/scheduling/calendar/calendar-rtl-sample/calendar-rtl-sample.component.scss
  src/app/scheduling/calendar/calendar-sample-1/calendar-sample-1.component.scss
  src/app/scheduling/calendar/calendar-sample-2/calendar-sample-2.component.scss
  src/app/scheduling/calendar/calendar-sample-3/calendar-sample-3.component.html
  src/app/scheduling/calendar/calendar-sample-3/calendar-sample-3.component.scss
  src/app/scheduling/calendar/calendar-sample-4/calendar-sample-4.component.scss
  src/app/scheduling/calendar/calendar-sample-5/calendar-sample-5.component.scss
  src/app/scheduling/calendar/calendar-sample-6/calendar-sample-6.component.scss
  src/app/scheduling/calendar/calendar-sample-7/calendar-sample-7.component.scss
  src/app/scheduling/calendar/calendar-sample-8/calendar-sample-8.component.scss
  src/app/scheduling/calendar/calendar-styling-sample/calendar-styling-sample.component.scss
  src/app/scheduling/calendar/calendar-years-view/calendar-years-view.component.scss
  src/app/scheduling/calendar/multiview/multiview.component.scss
  src/app/scheduling/monthpicker/monthpicker-sample-1/monthpicker-sample-1.component.scss
  src/app/scheduling/monthpicker/monthpicker-sample-3/monthpicker-sample-3.component.scss
  src/app/scheduling/monthpicker/monthpicker-styling/monthpicker-styling.component.scss
Labels: status: verified, calendar, month picker, 18.0.x

#3489 Grid - fix paging style samples
  src/app/grid/custom-grid-paging-style/custom-grid-paging-style.component.scss
  src/app/hierarchical-grid/hierarchical-grid-paging-style/hierarchical-grid-paging-style.component.scss
  src/app/tree-grid/tree-grid-paging-style/tree-grid-paging-style-sample.component.scss
Labels: status: verified, styling, paging, 18.0.x

#3491 update with official angular 18
  package-lock.json
  package.json
  src/app/lists/combo/combo-features/combo-features.component.html
  src/app/lists/combo/combo-remote/combo-remote.component.html
  src/app/lists/combo/combo-styling/combo-styling.component.html
Labels: 18.0.x

#3494 fix(reactive-forms-stepper): add live-editing reactive forms module
  live-editing/configs/StepperConfigGenerator.ts
Labels: status: awaiting-test

#3502 Fixed sample data issue #3487
  src/app/data/singersData.ts
Labels: status: verified, hierarchical-grid

#3500 Refactor Grid Cascading Combos sample to handle vritualized grid scenario
  src/app/grid/grid-cascading-combos/grid-cascading-combos.component.html
  src/app/grid/grid-cascading-combos/grid-cascading-combos.component.ts
Labels: status: verified, grid, simple-combo
