Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2024-07, with the labels that each got.

#3504 fix(mask): ensure single % appended on blur and removed on focus
  src/app/data-display/mask/mask-sample-4/mask-sample-4.component.html
  src/app/data-display/mask/mask-sample-4/mask-sample-4.component.ts
Labels: status: verified, mask

#3506 FIxed TreeGrid sample row deletion
  src/app/tree-grid/tree-grid-multi-row-drag/tree-grid-multi-row-drag.component.ts
Labels: status: verified, tree-grid

#3503 Fixing Tree Grid Filter View Sample
  src/app/tree-grid/tree-grid-tree-filter-view/tree-grid-tree-filter-view.component.html
  src/app/tree-grid/tree-grid-tree-filter-view/tree-grid-tree-filter-view.component.scss
  src/app/tree-grid/tree-grid-tree-filter-view/tree-grid-tree-filter-view.component.ts
Labels: status: verified, tree-grid

#3508 refactor(*): update samples related to the 18.1.x release
  live-editing/configs/IconConfigGenerator.ts
  package-lock.json
  package.json
  src/app/data-display/data-display-routes-data.ts
  src/app/data-display/data-display-routing.module.ts
  src/app/data-display/data-display.module.ts
  src/app/data-display/icon/icon-service-sample/icon-service-sample.component.html
  src/app/data-display/icon/icon-service-sample/icon-service-sample.component.scss
  src/app/data-display/icon/icon-service-sample/icon-service-sample.component.ts
  src/app/scheduling/calendar/calendar-styling-sample/calendar-styling-sample.component.scss
  src/app/scheduling/calendar/themes/google.scss
  src/app/scheduling/datepicker/datepicker-styling-sample/datepicker-styling-sample.component.scss
  src/app/scheduling/monthpicker/monthpicker-styling/monthpicker-styling.component.scss
  src/app/theming/styles/themes.scss
  src/assets/images/icons/partly_cloudy.svg
  src/assets/images/icons/sunny.svg
  src/assets/images/icons/thunderstorms.svg
Labels: status: verified, version: 18.1.x

#3501 fix(tree-grid): fixed external filtering sample window alignment
  src/app/grid/grid-external-excel-style-filtering/grid-external-excel-style-filtering.component.html
  src/app/grid/grid-external-excel-style-filtering/grid-external-excel-style-filtering.component.scss
  src/app/hierarchical-grid/hierarchical-grid-external-excel-style-filtering/hierarchical-grid-external-excel-style-filtering.component.html
  src/app/hierarchical-grid/hierarchical-grid-external-excel-style-filtering/hierarchical-grid-external-excel-style-filtering.component.scss
  src/app/tree-grid/tree-grid-external-excel-style-filtering/tree-grid-external-excel-style-filtering.component.html
  src/app/tree-grid/tree-grid-external-excel-style-filtering/tree-grid-external-excel-style-filtering.component.scss
Labels: status: verified

#3522 docs(tGrid): fixed about page routing
  src/app/pivot-grid/pivot-grids.module.ts
  src/app/tree-grid/tree-grid-save-state/about.component.html
Labels: status: verified

#3521 docs(grid): updated sample grid columns type
  src/app/grid/grid-row-editing-style/grid-row-editing-style.component.html
Labels: status: verified
