Repository IgniteUI/igniteui-angular-samples, pull requests merged in 2025-03, with the labels that each got.

#3615 chore(*): update extras package version
  package-lock.json
  package.json
Labels: status: verified

#3617 chore(*): update extras package version
  package-lock.json
  package.json
Labels: status: verified

#3620 fix(grid): rename iconNames in custom filtering operands demos
  src/app/grid/grid-custom-filtering/grid-custom-filtering.component.ts
  src/app/hierarchical-grid/hierarchical-grid-filtering/hierarchical-grid-custom-filtering.component.ts
  src/app/tree-grid/tree-grid-filtering-custom-sample/tree-grid-filtering-custom-sample.component.ts
Labels: status: verified, grid, tree-grid, hierarchical-grid

#3624 fix(transaction): add IgxTransactionService provider in the Transaction demo
  src/app/services/transaction/transaction-base/transaction-base.component.ts
Labels: status: verified, transaction

#3621 fix(overlay): fix combo binding in overlay styling demo
  src/app/interactions/overlay/overlay-styling/overlay-styling.component.html
Labels: status: verified, combo, overlay

#3640 refactor(grid-samples): update grid summary styling samples
  src/app/grid/grid-groupby-summary-styling-sample/grid-groupby-summary-styling-sample.component.scss
  src/app/hierarchical-grid/hierarchical-grid-summary-styling/hierarchical-grid-summary-styling.component.scss
Labels: status: verified, refactoring

#3648 QB sample requesting data from an endpoint
  src/app/interactions/interactions-routes-data.ts
  src/app/interactions/interactions.routes.ts
  src/app/interactions/query-builder/query-builder-request-sample/query-builder-request-sample.component.html
  src/app/interactions/query-builder/query-builder-request-sample/query-builder-request-sample.component.scss
  src/app/interactions/query-builder/query-builder-request-sample/query-builder-request-sample.component.ts
Labels: status: verified, query-builder

#3653 fix(grid-custom-filtering): samples not building
  src/app/grid/grid-custom-filtering/grid-custom-filtering.component.ts
  src/app/hierarchical-grid/hierarchical-grid-filtering/hierarchical-grid-custom-filtering.component.ts
  src/app/tree-grid/tree-grid-filtering-custom-sample/tree-grid-filtering-custom-sample.component.ts
Labels: status: verified

#3662 Adding a sample for Tile Manager
  live-editing/configs/TileManagerConfigGenerator.ts
  live-editing/generators/ConfigGenerators.ts
  package-lock.json
  package.json
  src/app/layouts/layouts-routes-data.ts
  src/app/layouts/layouts.routes.ts
  src/app/layouts/tile-manager/tile-manager-sample/tile-manager.component.html
  src/app/layouts/tile-manager/tile-manager-sample/tile-manager.component.scss
  src/app/layouts/tile-manager/tile-manager-sample/tile-manager.component.ts
  tsconfig.json
Labels: status: verified
